import type {
  FrameworkTrancheMilestone,
  TrancheExecutionLane,
} from './shared.ts';
import {
  DEFERRED_LIVE_EVIDENCE,
  NON_LIVE_ACCEPTANCE,
  NO_SECOND_TRUTH_AUTHORITY_BOUNDARY,
} from './shared.ts';

export const APP_SHELL_CONVERGENCE_STRUCTURE_READBACK = {
  status: 'closed_structure_gate_not_live_evidence',
  source_repo: 'gaofeng21cn/one-person-lab-app',
  absorbed_origin_main_sha: '9cb0196c06d1203a33d9aad20b9299eac6f36a0e',
  readback_command: 'npm run validate:shell-convergence',
  surface_kind: 'opl_app_shell_convergence_readback',
  mainline_shell: 'AionUI/opl-aion-shell',
  foreground_alternative: 'Hermes Desktop/hermes-codex',
  archived_technical_proof_only: 'AGUI/agui-codex',
  default_candidate_validation_scope: ['hermes-codex'],
  archived_technical_proofs: ['agui-codex'],
  false_ready_boundary: {
    active_shell_switch_allowed_by_this_readback: false,
    can_claim_active_shell_adopted: false,
    can_claim_app_release_ready: false,
    can_claim_production_ready: false,
    can_claim_live_user_path: false,
    can_claim_live_evidence: false,
    can_claim_packaged_gui_acceptance: false,
  },
  source_refs: [
    'one-person-lab-app:contracts/app-shell-adapter.json',
    'one-person-lab-app:contracts/app-shell-candidates.json',
    'one-person-lab-app:contracts/shell-adapters/hermes-codex.json',
    'one-person-lab-app:scripts/validate-shell-convergence.ts',
    'one-person-lab-app:tests/release/app-release-boundary-cases/shell-adapter-and-gui-contracts.ts',
    'one-person-lab-app:docs/status.md',
    'one-person-lab-app:docs/active/app-ideal-state-gap-plan.md',
  ],
};

export const CROSS_REPO_REF_INTEGRITY_GUARD = {
  surface_kind: 'opl_family_cross_repo_ref_integrity_guard',
  status: 'closed_structure_gate_not_live_evidence',
  owner: 'one-person-lab',
  guard_role:
    'tranche_backlog_cross_repo_refs_are_canonical_or_explicitly_forbidden_legacy_refs_not_runtime_truth',
  checked_repo_refs: [
    {
      repo: 'opl-doc',
      canonical_ref: 'contracts/support-repo-policy.json',
      consumed_by_milestone_id: 'support_repo_profile_no_resurrection',
      stale_or_forbidden_refs: [
        'contracts/support_repo_policy.json',
      ],
      source_readback_ref:
        'opl-doc:scripts/opl_doc_doctor.py family-plan --format json .support_profile_guard',
      integrity_state: 'canonical_ref_consumed_legacy_alias_forbidden',
    },
  ],
  no_second_truth_guard: {
    cross_repo_ref_guard_can_replace_repo_truth: false,
    cross_repo_ref_guard_can_create_missing_contract_alias: false,
    cross_repo_ref_guard_can_claim_support_repo_ready: false,
    cross_repo_ref_guard_can_claim_foundry_agent_truth_set_membership: false,
    cross_repo_ref_guard_can_claim_live_evidence_complete: false,
  },
  false_ready_guard: {
    canonical_ref_exists_can_claim_repo_ready: false,
    ref_integrity_pass_can_claim_plan_completion: false,
    support_profile_guard_can_claim_production_ready: false,
  },
};

export const CURRENT_TRANCHE_LANES: TrancheExecutionLane[] = [
  {
    lane_id: 'opl-doc-support-policy-ref-guard-20260621',
    repo: 'opl-doc',
    priority: 'P2',
    milestone_ids: ['support_repo_profile_no_resurrection'],
    lane_status: 'structure_gate_support_policy_canonical_ref_guard_non_live_evidence',
    write_set_class: 'support_repo_policy_no_resurrection_guard',
    required_surfaces: [
      'source',
      'contract',
      'CLI_readback',
      'docs',
      'tests',
    ],
    non_live_completion_evidence_required: [
      'support_policy_contract_uses_canonical_hyphen_ref',
      'legacy_underscore_support_policy_ref_forbidden_not_aliased',
      'family_plan_support_profile_guard_emits_canonical_ref_and_forbidden_legacy_ref',
      'native_check_and_verify_pass',
      'opl_doc_main_absorbed_push_and_remote_sha_readback',
    ],
    deferred_evidence: DEFERRED_LIVE_EVIDENCE,
    forbidden_scope: [
      'legacy_support_repo_policy_alias_file',
      'target_repo_truth_write',
      'Foundry_Agent_truth_set_membership_claim',
      'owner_receipt_or_quality_verdict_claim',
      'production_readiness_claim',
      'Live_Evidence_claim',
    ],
  },
  {
    lane_id: 'opl-cross-repo-ref-integrity-20260621',
    repo: 'one-person-lab',
    priority: 'P2',
    milestone_ids: ['support_repo_profile_no_resurrection'],
    lane_status: 'structure_gate_backlog_ref_integrity_consumer_lane_non_live_evidence',
    write_set_class: 'opl_framework_cross_repo_ref_integrity_guard',
    required_surfaces: [
      'source',
      'CLI_readback',
      'API_readback',
      'docs',
      'tests',
    ],
    non_live_completion_evidence_required: [
      'framework_tranche_backlog_consumes_opl_doc_canonical_support_policy_ref',
      'cross_repo_ref_integrity_guard_marks_legacy_underscore_ref_forbidden',
      'milestone_state_counts_open_zero_closed_structure_gate_seven',
      'framework_cli_surface_tests_typecheck_and_smoke_pass',
      'OPL_main_absorbed_push_and_remote_sha_readback',
    ],
    deferred_evidence: DEFERRED_LIVE_EVIDENCE,
    forbidden_scope: [
      'sibling_repo_writes_from_OPL_consumer_lane',
      'legacy_support_repo_policy_alias_file',
      'runtime_ledger_mutation',
      'domain_truth_write',
      'owner_receipt_or_typed_blocker_authority',
      'provider_long_soak_or_live_evidence_claim',
      'full_Plan_Completion_Audit_claim',
    ],
  },
];

export const FRAMEWORK_TRANCHE_MILESTONES: FrameworkTrancheMilestone[] = [
  {
    milestone_id: 'opl_primitive_runtime_owner_route_guard',
    priority: 'P0',
    state: 'closed_structure_gate',
    owner_repos: ['one-person-lab'],
    lane_role:
      'Upcollect OPL primitives for runtime env, owner route, typed blocker, ordinary path, and no-second-truth guard surfaces.',
    current_truth_refs: [
      'docs/active/current-state-vs-ideal-gap.md#active-planning-gap-register',
      'docs/status.md#durable-objective-current-reading',
      'contracts/opl-framework/runtime-environment-substrate-contract.json',
      'contracts/opl-framework/stage-route-scheduler-contract.json#stage_route_arbiter_substrate_contract.domain_progress_transition_runtime_first_slice',
      'contracts/opl-framework/target-operating-architecture-contract.json',
      'src/runtime-environment-substrate.ts',
      'src/family-runtime-domain-progress-transition-runtime.ts',
      'src/family-runtime-domain-progress-transition-runtime-parts/policy-adapter.ts',
      'src/framework-readiness.ts',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: DEFERRED_LIVE_EVIDENCE,
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'domain_pack_generated_hosted_surfaces',
    priority: 'P0',
    state: 'closed_structure_gate',
    owner_repos: ['one-person-lab', 'med-autogrant', 'redcube-ai', 'opl-meta-agent'],
    lane_role:
      'Converge standard domain agents onto declarative Domain Pack input plus OPL generated/hosted surface readbacks.',
    current_truth_refs: [
      'contracts/opl-framework/domain-pack-compiler-contract.json',
      'src/domain-pack-compiler.ts',
      'docs/active/current-state-vs-ideal-gap.md',
      'domain repos: contracts/private_functional_surface_policy.json',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: DEFERRED_LIVE_EVIDENCE,
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'strict_source_purity_private_wrapper_retirement',
    priority: 'P1',
    state: 'closed_structure_gate',
    owner_repos: ['med-autogrant', 'redcube-ai', 'opl-meta-agent'],
    lane_role:
      'Thin or retire private wrapper residue with source-purity gates, no-active-caller proof, tombstone/provenance, and false-ready guards.',
    current_truth_refs: [
      'med-autogrant:contracts/private_functional_surface_policy.json#/physical_source_morphology_policy/retirement_readback_cleanup_guard',
      'med-autogrant:src/med_autogrant/opl_standard_pack_source_policy.py',
      'med-autogrant:tests/product_entry_cases/test_physical_morphology_guard.py',
      'med-autogrant:docs/active/opl-private-implementation-migration-inventory.md',
      'redcube-ai:contracts/physical_source_morphology_policy.json',
      'redcube-ai:tests/opl-agent-pack-contracts-source-morphology.test.ts',
      'redcube-ai:tests/rca-legacy-name-allowance.test.ts',
      'redcube-ai:docs/active/opl-private-implementation-migration-inventory.md',
      'redcube-ai:docs/active/rca-ideal-state-gap-plan.md',
      'opl-meta-agent:contracts/script_to_pack_gate_receipt.json#script_morphology_policy.retirement_readback_cleanup_guard',
      'opl-meta-agent:runtime/authority_functions/meta-agent-authority-functions.json#script_morphology_policy',
      'opl-meta-agent:runtime/authority_functions/meta-agent-authority-functions.parts/script_morphology_policy/root.json',
      'opl-meta-agent:contracts/script_to_pack_gate_receipt.json#/machine_gate_inputs/source_ref_integrity_guard',
      'opl-meta-agent:tests/source-purity.test.ts',
      'opl-meta-agent:docs/active/opl-private-implementation-migration-inventory.md',
      'OPL docs/active/current-state-vs-ideal-gap.md',
      'MAG source-ref integrity commit 3848284b64b282ed5b5ec380cbd5a57c72ac47a0',
      'OMA source-ref integrity commit 7b2d64a4456225a8e66c767281af4f706aed1fc7',
      'RCA source-ref integrity commit 711292501cc670f97ed47e405bc2b58686eb0d37',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: [
      'default_caller_live_scaleout',
      'App_operator_sustained_consumption',
      'physical_delete_owner_receipt',
      ...DEFERRED_LIVE_EVIDENCE,
    ],
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'memory_artifact_lifecycle_functional_boundary',
    priority: 'P0',
    state: 'closed_structure_gate',
    owner_repos: ['one-person-lab'],
    lane_role:
      'Keep memory/artifact/lifecycle as refs-only intake, evidence readback, and owner-route work-order projection without body authority.',
    current_truth_refs: [
      'src/memory-artifact-lifecycle-evidence-ledger.ts',
      'src/memory-artifact-lifecycle-readback.ts',
      'src/runtime-tray-app-operator-drilldown-parts/memory-artifact-lifecycle-evidence.ts',
      'src/cli/cases/runtime-memory-artifact-lifecycle-evidence-command-spec.ts',
      'docs/active/current-state-vs-ideal-gap.md',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: [
      'domain_memory_receipt_followthrough',
      'artifact_mutation_receipt_followthrough',
      'package_export_owner_acceptance',
      ...DEFERRED_LIVE_EVIDENCE,
    ],
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'oma_script_to_pack_hygiene',
    priority: 'P2',
    state: 'closed_structure_gate',
    owner_repos: ['opl-meta-agent'],
    lane_role:
      'Keep retained scripts machine-classified with active callers, OPL-surface consumption policy, retirement gates, and reciprocal consumption guard.',
    current_truth_refs: [
      'opl-meta-agent:contracts/script_to_pack_gate_receipt.json',
      'opl-meta-agent:runtime/authority_functions/meta-agent-authority-functions.json#script_morphology_policy',
      'opl-meta-agent:tests/source-purity.test.ts',
      'opl-meta-agent:docs/active/opl-private-implementation-migration-inventory.md',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: [
      'OPL_primitive_parity_receipt',
      'script_physical_retirement_no_active_caller_receipt',
      'target_agent_live_patch_loop',
      ...DEFERRED_LIVE_EVIDENCE,
    ],
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'app_active_shell_hermes_convergence',
    priority: 'P2',
    state: 'closed_structure_gate',
    owner_repos: ['one-person-lab-app'],
    lane_role:
      'Keep AionUI/opl-aion-shell as the App mainline and Hermes Desktop as the only foreground alternative while AGUI remains archived technical proof.',
    current_truth_refs: [
      'one-person-lab-app@9cb0196c06d1203a33d9aad20b9299eac6f36a0e:scripts/validate-shell-convergence.ts',
      'one-person-lab-app@9cb0196c06d1203a33d9aad20b9299eac6f36a0e:contracts/app-shell-adapter.json',
      'one-person-lab-app@9cb0196c06d1203a33d9aad20b9299eac6f36a0e:contracts/app-shell-candidates.json',
      'one-person-lab-app@9cb0196c06d1203a33d9aad20b9299eac6f36a0e:tests/release/app-release-boundary-cases/shell-adapter-and-gui-contracts.ts',
      'one-person-lab-app@9cb0196c06d1203a33d9aad20b9299eac6f36a0e:docs/status.md',
      'OPL docs/status.md',
      'contracts/opl-framework/family-product-operator-projection.json',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: [
      'App_release_cohort',
      'real_user_path',
      'packaged_gui_acceptance',
      'active_shell_adoption_decision',
      ...DEFERRED_LIVE_EVIDENCE,
    ],
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'support_repo_profile_no_resurrection',
    priority: 'P2',
    state: 'closed_structure_gate',
    owner_repos: ['opl-doc'],
    lane_role:
      'Keep support repos extension-only, outside default family repo truth, and guarded against authority resurrection.',
    current_truth_refs: [
      'opl-doc:contracts/support-repo-policy.json',
      'opl-doc:scripts/opl_doc_doctor.py',
      'OPL docs/active/current-state-vs-ideal-gap.md',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: DEFERRED_LIVE_EVIDENCE,
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
];
