import type {
  FrameworkTrancheMilestone,
  TrancheExecutionLane,
} from './shared.ts';
import {
  DEFERRED_LIVE_EVIDENCE,
  NON_LIVE_ACCEPTANCE,
  NO_SECOND_TRUTH_AUTHORITY_BOUNDARY,
} from './shared.ts';

export const APP_SHELL_CONVERGENCE_STRUCTURE_READBACK = {
  status: 'closed_structure_gate_not_live_evidence',
  source_repo: 'gaofeng21cn/one-person-lab-app',
  absorbed_origin_main_sha: '9cb0196c06d1203a33d9aad20b9299eac6f36a0e',
  readback_command: 'npm run validate:shell-convergence',
  surface_kind: 'opl_app_shell_convergence_readback',
  mainline_shell: 'AionUI/opl-aion-shell',
  foreground_alternative: 'Hermes Desktop/hermes-codex',
  archived_technical_proof_only: 'AGUI/agui-codex',
  default_candidate_validation_scope: ['hermes-codex'],
  archived_technical_proofs: ['agui-codex'],
  false_ready_boundary: {
    active_shell_switch_allowed_by_this_readback: false,
    can_claim_active_shell_adopted: false,
    can_claim_app_release_ready: false,
    can_claim_production_ready: false,
    can_claim_live_user_path: false,
    can_claim_live_evidence: false,
    can_claim_packaged_gui_acceptance: false,
  },
  source_refs: [
    'one-person-lab-app:contracts/app-shell-adapter.json',
    'one-person-lab-app:contracts/app-shell-candidates.json',
    'one-person-lab-app:contracts/shell-adapters/hermes-codex.json',
    'one-person-lab-app:scripts/validate-shell-convergence.ts',
    'one-person-lab-app:tests/release/app-release-boundary-cases/shell-adapter-and-gui-contracts.ts',
    'one-person-lab-app:docs/status.md',
    'one-person-lab-app:docs/active/app-ideal-state-gap-plan.md',
  ],
};

export const CROSS_REPO_REF_INTEGRITY_GUARD = {
  surface_kind: 'opl_family_cross_repo_ref_integrity_guard',
  status: 'closed_structure_gate_not_live_evidence',
  owner: 'one-person-lab',
  guard_role:
    'tranche_backlog_cross_repo_refs_are_canonical_or_explicitly_forbidden_legacy_refs_not_runtime_truth',
  checked_repo_refs: [
    {
      repo: 'opl-doc',
      canonical_ref: 'contracts/support-repo-policy.json',
      consumed_by_milestone_id: 'support_repo_profile_no_resurrection',
      stale_or_forbidden_refs: [
        'contracts/support_repo_policy.json',
      ],
      source_readback_ref:
        'opl-doc:scripts/opl_doc_doctor.py family-plan --format json .support_profile_guard',
      integrity_state: 'canonical_ref_consumed_legacy_alias_forbidden',
    },
  ],
  no_second_truth_guard: {
    cross_repo_ref_guard_can_replace_repo_truth: false,
    cross_repo_ref_guard_can_create_missing_contract_alias: false,
    cross_repo_ref_guard_can_claim_support_repo_ready: false,
    cross_repo_ref_guard_can_claim_foundry_agent_truth_set_membership: false,
    cross_repo_ref_guard_can_claim_live_evidence_complete: false,
  },
  false_ready_guard: {
    canonical_ref_exists_can_claim_repo_ready: false,
    ref_integrity_pass_can_claim_plan_completion: false,
    support_profile_guard_can_claim_production_ready: false,
  },
};

export const CURRENT_TRANCHE_LANES: TrancheExecutionLane[] = [
  {
    lane_id: 'mag-morphology-public-readback-20260622',
    repo: 'med-autogrant',
    priority: 'P1',
    milestone_ids: ['strict_source_purity_private_wrapper_retirement'],
    lane_status: 'structure_gate_public_morphology_readback_no_second_truth_guard_non_live_evidence',
    write_set_class: 'strict_source_purity_private_wrapper_public_readback_retirement_guard',
    required_surfaces: [
      'source',
      'contract',
      'CLI_readback',
      'docs',
      'tests',
    ],
    non_live_completion_evidence_required: [
      'MAG_authority_morphology_guard_public_readback_replaces_product_physical_morphology_guard_refs',
      'MAG_strict_source_purity_and_source_ref_integrity_readbacks_expose_authority_morphology_guard_refs',
      'MAG_private_surface_policy_and_OPL_standard_pack_policy_consume_public_readback_refs',
      'MAG_focused_pytest_and_authority_morphology_guard_CLI_readback_pass',
      'framework_tranche_backlog_current_tranche_selects_MAG_morphology_public_readback_lane',
      'MAG_main_absorbed_push_and_remote_sha_readback',
    ],
    deferred_evidence: DEFERRED_LIVE_EVIDENCE,
    forbidden_scope: [
      'physical_delete_authorization_by_MAG_or_OPL_guard',
      'owner_receipt_signature',
      'typed_blocker_instance_creation_by_guard',
      'default_caller_cutover_claim',
      'grant_ready_or_submission_ready_claim',
      'App_operator_live_consumption_claim',
      'Live_Evidence_claim',
      'full_Plan_Completion_Audit_claim',
    ],
  },
  {
    lane_id: 'oma-source-structure-json-readback-20260622',
    repo: 'opl-meta-agent',
    priority: 'P1',
    milestone_ids: ['oma_script_to_pack_hygiene'],
    lane_status: 'structure_gate_source_structure_json_readback_script_to_pack_receipt_guard_non_live_evidence',
    write_set_class: 'oma_script_to_pack_source_structure_json_readback_guard',
    required_surfaces: [
      'source',
      'contract',
      'package_script_readback',
      'JSON_readback',
      'generated_authority_aggregate',
      'docs',
      'tests',
    ],
    non_live_completion_evidence_required: [
      'OMA_source_structure_json_readback_exposes_line_budget_and_script_to_pack_guard_status',
      'OMA_source_structure_strict_json_readback_passes_without_line_or_script_guard_violations',
      'OMA_source_structure_policy_declares_json_readback_command_and_false_authority_boundary',
      'OMA_authority_functions_generated_aggregate_consumes_new_source_structure_readback_refs',
      'OMA_source_structure_and_source_purity_focused_smoke_pass',
      'framework_tranche_backlog_current_tranche_selects_OMA_source_structure_json_readback_lane',
      'OMA_main_absorbed_push_and_remote_sha_readback',
    ],
    deferred_evidence: DEFERRED_LIVE_EVIDENCE,
    forbidden_scope: [
      'target_domain_truth_write',
      'target_owner_receipt_body_write',
      'owner_receipt_signature',
      'typed_blocker_instance_creation_by_guard',
      'script_physical_retirement_authorization',
      'OPL_primitive_parity_claim',
      'target_agent_ready_claim',
      'domain_ready_claim',
      'production_ready_claim',
      'Live_Evidence_claim',
      'full_Plan_Completion_Audit_claim',
    ],
  },
];

export const FRAMEWORK_TRANCHE_MILESTONES: FrameworkTrancheMilestone[] = [
  {
    milestone_id: 'opl_primitive_runtime_owner_route_guard',
    priority: 'P0',
    state: 'closed_structure_gate',
    owner_repos: ['one-person-lab'],
    lane_role:
      'Upcollect OPL primitives for runtime env, owner route, typed blocker, ordinary path, and no-second-truth guard surfaces.',
    current_truth_refs: [
      'docs/active/current-state-vs-ideal-gap.md#active-planning-gap-register',
      'docs/status.md#durable-objective-current-reading',
      'contracts/opl-framework/runtime-environment-substrate-contract.json',
      'contracts/opl-framework/stage-route-scheduler-contract.json#stage_route_arbiter_substrate_contract.domain_progress_transition_runtime_first_slice',
      'contracts/opl-framework/target-operating-architecture-contract.json',
      'src/runtime-environment-substrate.ts',
      'src/family-runtime-domain-progress-transition-runtime.ts',
      'src/family-runtime-domain-progress-transition-runtime-parts/policy-adapter.ts',
      'src/framework-readiness.ts',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: DEFERRED_LIVE_EVIDENCE,
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'domain_pack_generated_hosted_surfaces',
    priority: 'P0',
    state: 'closed_structure_gate',
    owner_repos: ['one-person-lab', 'med-autogrant', 'redcube-ai', 'opl-meta-agent'],
    lane_role:
      'Converge standard domain agents onto declarative Domain Pack input plus OPL generated/hosted surface readbacks.',
    current_truth_refs: [
      'contracts/opl-framework/domain-pack-compiler-contract.json',
      'src/domain-pack-compiler.ts',
      'docs/active/current-state-vs-ideal-gap.md',
      'domain repos: contracts/private_functional_surface_policy.json',
      'redcube-ai@b0603a1a:contracts/generated_surface_handoff.json#OPL_GENERATED_SURFACE_EXIT_GATE.false_ready_guard',
      'redcube-ai@b0603a1a:contracts/functional_privatization_audit.json',
      'redcube-ai@b0603a1a:contracts/runtime-program/current-program.json',
      'redcube-ai@b0603a1a:tests/opl-agent-pack-contracts-generated-surface.test.ts',
      'redcube-ai@b0603a1a:docs/status.md',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: DEFERRED_LIVE_EVIDENCE,
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'strict_source_purity_private_wrapper_retirement',
    priority: 'P1',
    state: 'closed_structure_gate',
    owner_repos: ['med-autogrant', 'redcube-ai', 'opl-meta-agent'],
    lane_role:
      'Thin or retire private wrapper residue with source-purity gates, no-active-caller proof, tombstone/provenance, and false-ready guards.',
    current_truth_refs: [
      'med-autogrant:contracts/private_functional_surface_policy.json#/physical_source_morphology_policy/retirement_readback_cleanup_guard',
      'med-autogrant:contracts/private_functional_surface_policy.json#/physical_source_morphology_policy/strict_source_purity_no_second_truth_guard',
      'med-autogrant:authority morphology-guard#strict_source_purity_no_second_truth_guard',
      'med-autogrant:authority morphology-guard#source_ref_integrity_guard',
      'med-autogrant:src/med_autogrant/opl_standard_pack_source_policy.py',
      'med-autogrant:tests/product_entry_cases/test_physical_morphology_guard.py',
      'med-autogrant:docs/active/opl-private-implementation-migration-inventory.md',
      'redcube-ai:contracts/physical_source_morphology_policy.json',
      'redcube-ai:tests/opl-agent-pack-contracts-source-morphology.test.ts',
      'redcube-ai:tests/rca-legacy-name-allowance.test.ts',
      'redcube-ai:docs/active/opl-private-implementation-migration-inventory.md',
      'redcube-ai:docs/active/rca-ideal-state-gap-plan.md',
      'opl-meta-agent:contracts/script_to_pack_gate_receipt.json#script_morphology_policy.retirement_readback_cleanup_guard',
      'opl-meta-agent:contracts/script_to_pack_gate_receipt.json#script_morphology_policy.generic_materializer_no_resurrection_guard',
      'opl-meta-agent:runtime/authority_functions/meta-agent-authority-functions.json#source_purity_scan_receipt.generic_script_materializer_scan',
      'opl-meta-agent:runtime/authority_functions/meta-agent-authority-functions.json#script_morphology_policy',
      'opl-meta-agent:runtime/authority_functions/meta-agent-authority-functions.parts/script_morphology_policy/root.json',
      'opl-meta-agent:contracts/script_to_pack_gate_receipt.json#/machine_gate_inputs/source_ref_integrity_guard',
      'opl-meta-agent:contracts/source_structure_policy.json#script_to_pack_receipt_guard.json_readback_command_ref',
      'opl-meta-agent:npm run source-structure:json --silent',
      'opl-meta-agent:npm run source-structure:strict:json --silent',
      'opl-meta-agent:tests/source-purity.test.ts',
      'opl-meta-agent:tests/source-structure-lane.test.ts',
      'opl-meta-agent:docs/active/opl-private-implementation-migration-inventory.md',
      'OPL docs/active/current-state-vs-ideal-gap.md',
      'MAG morphology public readback commit 6182a75ae01eb636d639a21d674db917e77da6dc',
      'OMA source-structure JSON readback commit b902ed0b0e1da4cf2ce559d03cb50ce2edcbe255',
      'RCA active source resurrection guard commit a857539e2f045ef9d83dd83a265ede2f250982a4',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: [
      'default_caller_live_scaleout',
      'App_operator_sustained_consumption',
      'physical_delete_owner_receipt',
      ...DEFERRED_LIVE_EVIDENCE,
    ],
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'standard_agent_landing_acceptance_guard',
    priority: 'P0',
    state: 'closed_structure_gate',
    owner_repos: ['one-person-lab'],
    lane_role:
      'Expose standard-agent landing acceptance, private-platform residue owner-decision, OMA target-agent guard, and negative conformance as one tranche-level readback without completion authority.',
    current_truth_refs: [
      'contracts/opl-framework/standard-agent-landing-acceptance-contract.json',
      'contracts/opl-framework/standard-agent-landing-evidence-status.json',
      'contracts/opl-framework/private-platform-residue-owner-decisions.json',
      'contracts/opl-framework/standard-agent-negative-conformance-samples.json',
      'src/framework-tranche-backlog-parts/standard-agent-landing-guard.ts',
      'src/private-platform-residue-owner-decisions.ts',
      'tests/src/standard-agent-landing-acceptance-contract.test.ts',
      'tests/src/cli/cases/framework-readiness-cli-surface.test.ts',
      'OPL docs/active/current-state-vs-ideal-gap.md',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: [
      'generated_surface_production_consumption_owner_evidence',
      'OMA_target_agent_real_owner_closeout',
      'cross_agent_negative_conformance_scaleout',
      'long_soak_real_user_path_owner_evidence',
      ...DEFERRED_LIVE_EVIDENCE,
    ],
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'memory_artifact_lifecycle_functional_boundary',
    priority: 'P0',
    state: 'closed_structure_gate',
    owner_repos: ['one-person-lab'],
    lane_role:
      'Keep memory/artifact/lifecycle as refs-only intake, evidence readback, and owner-route work-order projection without body authority.',
    current_truth_refs: [
      'src/memory-artifact-lifecycle-evidence-ledger.ts',
      'src/memory-artifact-lifecycle-readback.ts',
      'src/runtime-tray-app-operator-drilldown-parts/memory-artifact-lifecycle-evidence.ts',
      'src/cli/cases/runtime-memory-artifact-lifecycle-evidence-command-spec.ts',
      'opl-bookforge@17d184c:contracts/artifact_lifecycle_handoff.json',
      'opl-bookforge@17d184c:contracts/workspace_lifecycle_policy.json',
      'opl-bookforge@17d184c:runtime/native_helpers/bookforge_project_hygiene.py',
      'opl-bookforge@17d184c:runtime/native_helpers/bookforge_project_hygiene_parts/opl_lifecycle.py',
      'opl-bookforge@17d184c:docs/active/bookforge-ideal-state-gap-plan.md',
      'docs/active/current-state-vs-ideal-gap.md',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: [
      'domain_memory_receipt_followthrough',
      'artifact_mutation_receipt_followthrough',
      'package_export_owner_acceptance',
      ...DEFERRED_LIVE_EVIDENCE,
    ],
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'oma_script_to_pack_hygiene',
    priority: 'P2',
    state: 'closed_structure_gate',
    owner_repos: ['opl-meta-agent'],
    lane_role:
      'Keep retained scripts machine-classified with active callers, OPL-surface consumption policy, retirement gates, and reciprocal consumption guard.',
    current_truth_refs: [
      'opl-meta-agent:contracts/script_to_pack_gate_receipt.json',
      'opl-meta-agent:runtime/authority_functions/meta-agent-authority-functions.json#script_morphology_policy',
      'opl-meta-agent:runtime/authority_functions/meta-agent-authority-functions.json#source_purity_scan_receipt.active_script_caller_scan',
      'opl-meta-agent:contracts/source_structure_policy.json#script_to_pack_receipt_guard.json_readback_command_ref',
      'opl-meta-agent:package.json#scripts.source-structure:json',
      'opl-meta-agent:package.json#scripts.source-structure:strict:json',
      'opl-meta-agent:scripts/check-source-structure.ts#oma_source_structure_readback',
      'opl-meta-agent:npm run source-structure:json --silent',
      'opl-meta-agent:npm run source-structure:strict:json --silent',
      'opl-meta-agent:tests/source-purity.test.ts',
      'opl-meta-agent:tests/source-structure-lane.test.ts',
      'opl-meta-agent:docs/active/opl-private-implementation-migration-inventory.md',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: [
      'OPL_primitive_parity_receipt',
      'script_physical_retirement_no_active_caller_receipt',
      'target_agent_live_patch_loop',
      ...DEFERRED_LIVE_EVIDENCE,
    ],
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'app_active_shell_hermes_convergence',
    priority: 'P2',
    state: 'closed_structure_gate',
    owner_repos: ['one-person-lab-app'],
    lane_role:
      'Keep AionUI/opl-aion-shell as the App mainline and Hermes Desktop as the only foreground alternative while AGUI remains archived technical proof.',
    current_truth_refs: [
      'one-person-lab-app@9cb0196c06d1203a33d9aad20b9299eac6f36a0e:scripts/validate-shell-convergence.ts',
      'one-person-lab-app@9cb0196c06d1203a33d9aad20b9299eac6f36a0e:contracts/app-shell-adapter.json',
      'one-person-lab-app@9cb0196c06d1203a33d9aad20b9299eac6f36a0e:contracts/app-shell-candidates.json',
      'one-person-lab-app@9cb0196c06d1203a33d9aad20b9299eac6f36a0e:tests/release/app-release-boundary-cases/shell-adapter-and-gui-contracts.ts',
      'one-person-lab-app@9cb0196c06d1203a33d9aad20b9299eac6f36a0e:docs/status.md',
      'OPL docs/status.md',
      'contracts/opl-framework/family-product-operator-projection.json',
      'opl-hermes-shell:contracts/opl-hermes-candidate-profile.json',
      'opl-hermes-shell:scripts/validate-hermes-codex-candidate.cjs',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: [
      'App_release_cohort',
      'real_user_path',
      'packaged_gui_acceptance',
      'active_shell_adoption_decision',
      ...DEFERRED_LIVE_EVIDENCE,
    ],
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'support_repo_profile_no_resurrection',
    priority: 'P2',
    state: 'closed_structure_gate',
    owner_repos: ['opl-doc'],
    lane_role:
      'Keep support repos extension-only, outside default family repo truth, and guarded against authority resurrection.',
    current_truth_refs: [
      'opl-doc:contracts/support-repo-policy.json',
      'opl-doc:scripts/opl_doc_doctor.py',
      'OPL docs/active/current-state-vs-ideal-gap.md',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: DEFERRED_LIVE_EVIDENCE,
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
];
