export const AGENT_LAB_AUTHORITY_BOUNDARY = {
  opl: 'agent_lab_eval_improvement_control_plane_refs_only',
  domain: 'truth_quality_artifact_memory_body_and_owner_receipt_authority',
  can_write_domain_truth: false,
  can_write_memory_body: false,
  can_accept_or_reject_memory_writeback: false,
  can_authorize_domain_ready: false,
  can_authorize_quality_verdict: false,
  can_authorize_export_verdict: false,
  can_mutate_domain_artifact: false,
  can_write_owner_receipt: false,
  can_modify_managed_runtime: false,
  can_promote_default_agent_without_gate: false,
  can_write_shared_submission_action: false,
  can_push_shared_submission_action: false,
  can_authorize_submission_action: false,
};

export const FORBIDDEN_TRUE_AUTHORITY_FLAGS = [
  'can_write_domain_truth',
  'can_write_memory_body',
  'can_accept_or_reject_memory_writeback',
  'can_authorize_domain_ready',
  'can_authorize_quality_verdict',
  'can_authorize_export_verdict',
  'can_mutate_domain_artifact',
  'can_write_owner_receipt',
  'can_modify_managed_runtime',
  'can_promote_default_agent_without_gate',
  'can_write_shared_submission_action',
  'can_push_shared_submission_action',
  'can_authorize_submission_action',
  'opl_can_write_domain_truth',
  'opl_can_write_memory_body',
  'opl_can_write_owner_receipt',
  'opl_can_modify_managed_runtime',
  'opl_can_authorize_domain_ready',
  'opl_can_authorize_quality_verdict',
  'opl_can_authorize_export_verdict',
  'opl_can_write_shared_submission_action',
  'opl_can_push_shared_submission_action',
  'opl_can_authorize_submission_action',
];
