import { AGENT_LAB_AUTHORITY_BOUNDARY } from './agent-lab-authority.ts';
import type { AgentLabSuite, AgentLabTaskManifest } from './agent-lab.ts';

function commonAuthorityBoundary() {
  return {
    ...AGENT_LAB_AUTHORITY_BOUNDARY,
  };
}

function stageCompletionPolicy(policyRef: string) {
  return {
    surface_kind: 'domain_stage_completion_policy',
    policy_ref: policyRef,
    completion_judgment_owner: 'domain_stage',
    closeout_packet_required: false,
    raw_artifact_sufficient_for_progress: true,
    provider_completion_is_domain_completion: false,
    opl_content_judgment_allowed: false,
    next_stage_transition_owner: 'codex_cli',
    required_closeout_outcomes: [
      'completed_and_continue',
      'completed_and_wait_owner',
      'route_back',
      'blocked',
      'rejected',
    ],
    accepted_closeout_ref_fields: [
      'owner_receipt_ref',
      'typed_blocker_ref',
      'human_gate_ref',
      'route_back_ref',
    ],
    authority_boundary: {
      ...commonAuthorityBoundary(),
      opl_can_decide_domain_completion: false,
      provider_completion_counts_as_stage_complete: false,
    },
  };
}

function task(input: Omit<AgentLabTaskManifest, 'authority_boundary'>): AgentLabTaskManifest {
  return {
    ...input,
    stage_completion_policy: input.stage_completion_policy
      ?? stageCompletionPolicy(`stage-completion-policy:${input.domain_id}/${input.task_family}`),
    authority_boundary: commonAuthorityBoundary(),
    trajectory: {
      ...input.trajectory,
      authority_boundary: commonAuthorityBoundary(),
    },
    scorecard: {
      ...input.scorecard,
      authority_boundary: commonAuthorityBoundary(),
    },
    improvement_candidate: {
      ...input.improvement_candidate,
      authority_boundary: commonAuthorityBoundary(),
    },
    promotion_gate: {
      ...input.promotion_gate,
      authority_boundary: commonAuthorityBoundary(),
    },
  };
}

export function buildSampleAgentLabSuite(): AgentLabSuite {
  return {
    suite_id: 'opl-agent-lab-sample-suite',
    authority_boundary: commonAuthorityBoundary(),
    tasks: [
      task({
        task_id: 'agent-lab-task:mas/paper-repair-smoke',
        domain_id: 'med-autoscience',
        task_family: 'research_foundry_paper_repair',
        environment: {
          environment_kind: 'fixture',
          workspace_locator_ref: 'workspace-locator:mas/sample-paper-repair',
          sandbox_policy: 'fixture_only_no_artifact_mutation',
          network_policy: 'offline',
          resource_limits: { max_minutes: 15, max_stage_attempts: 3 },
        },
        instructions_ref: 'instructions:mas/paper-repair-smoke',
        agent_entry_ref: 'domain-agent-entry:med-autoscience',
        stage_refs: ['stage:mas/review-repair', 'stage:mas/guarded-apply'],
        oracle_refs: ['oracle:mas/publication-eval-fixture'],
        scorer_refs: ['scorer:mas/publication-quality-ref'],
        recovery_probes: [
          {
            probe_ref: 'recovery-probe:common/resume-after-interruption',
            probe_kind: 'resume_after_interruption',
            expected_status: 'passed',
            observed_status: 'passed',
            source_refs: ['receipt:mas/resume-fixture'],
          },
          {
            probe_ref: 'recovery-probe:mas/human-gate-resume',
            probe_kind: 'human_gate_resume',
            expected_status: 'passed',
            observed_status: 'passed',
            source_refs: ['human-gate:mas/reviewer-decision-fixture'],
          },
        ],
        trajectory: {
          trajectory_ref: 'trajectory:mas/paper-repair-smoke',
          run_ref: 'run:mas/paper-repair-smoke',
          agent_executor: 'codex_cli',
          stage_attempt_refs: ['stage-attempt:mas/paper-repair-smoke'],
          tool_call_refs: ['tool-call:mas/study-state-read'],
          artifact_refs: ['artifact-ref:mas/revision-package-fixture'],
          receipt_refs: ['owner-receipt:mas/publication-eval-fixture'],
          repair_refs: ['repair-ref:mas/reviewer-recheck'],
          trace_refs: ['trace-ref:inspect/mas-paper-repair'],
          command_refs: ['command-ref:codex/mas-paper-repair-smoke'],
          file_refs: ['file-ref:mas/current-package-fixture'],
          subagent_refs: ['subagent-ref:codex/mas-reviewer-repair'],
          worktree_refs: ['worktree-ref:codex/mas-paper-repair-smoke'],
          test_refs: ['test-ref:mas/paper-autonomy-smoke'],
          web_source_refs: ['source-ref:mas/reviewer-guideline-fixture'],
          typed_blocker_refs: ['typed-blocker-ref:agent-lab/mas/no-current-blocker-fixture'],
          review_receipt_refs: ['review-receipt-ref:mas/ai-reviewer-fixture'],
          next_run_falsification_refs: ['next-run-falsification-ref:mas/reviewer-repair-prompt'],
        },
        scorecard: {
          scorecard_ref: 'quality-scorecard:mas/paper-repair-smoke',
          domain_owned: true,
          opl_scorecard_role: 'scorecard_ref_projection_only',
          passed: true,
          metric_refs: ['metric-ref:mas/evidence-backed-claims'],
          evidence_refs: ['evidence-ref:mas/publication-eval-fixture'],
          review_refs: ['review-ref:mas/ai-reviewer-fixture'],
          quality_gate_refs: ['quality-gate:mas/publication-owner'],
        },
        improvement_candidate: {
          candidate_ref: 'improvement-candidate:mas/reviewer-repair-prompt',
          candidate_kind: 'prompt',
          target_ref: 'prompt-ref:mas/reviewer-repair',
          evidence_refs: ['failure-taxonomy:mas/no-current-failure-fixture'],
          allowed_change_scope: 'branch_only',
          promotion_gate_ref: 'promotion-gate:mas/paper-repair-smoke',
        },
        promotion_gate: {
          gate_ref: 'promotion-gate:mas/paper-repair-smoke',
          gate_status: 'passed',
          required_refs: ['quality-scorecard:mas/paper-repair-smoke'],
          regression_suite_refs: ['regression-suite:mas/paper-autonomy-smoke'],
          no_forbidden_write_proof_refs: ['no-forbidden-write:mas/agent-lab-fixture'],
        },
      }),
      task({
        task_id: 'agent-lab-task:mag/grant-section-smoke',
        domain_id: 'med-autogrant',
        task_family: 'grant_foundry_section_revision',
        environment: {
          environment_kind: 'fixture',
          workspace_locator_ref: 'workspace-locator:mag/sample-grant-section',
          sandbox_policy: 'fixture_only_no_artifact_mutation',
          network_policy: 'offline',
        },
        instructions_ref: 'instructions:mag/grant-section-smoke',
        agent_entry_ref: 'domain-agent-entry:med-autogrant',
        stage_refs: ['stage:mag/strategy-review', 'stage:mag/section-revision'],
        oracle_refs: ['oracle:mag/fundability-fixture'],
        scorer_refs: ['scorer:mag/fundability-quality-ref'],
        recovery_probes: [
          {
            probe_ref: 'recovery-probe:mag/retry-after-tool-failure',
            probe_kind: 'retry_after_tool_failure',
            expected_status: 'passed',
            observed_status: 'passed',
            source_refs: ['receipt:mag/retry-fixture'],
          },
        ],
        trajectory: {
          trajectory_ref: 'trajectory:mag/grant-section-smoke',
          run_ref: 'run:mag/grant-section-smoke',
          agent_executor: 'codex_cli',
          stage_attempt_refs: ['stage-attempt:mag/grant-section-smoke'],
          tool_call_refs: ['tool-call:mag/intake-read'],
          artifact_refs: ['artifact-ref:mag/section-draft-fixture'],
          receipt_refs: ['owner-receipt:mag/fundability-fixture'],
          repair_refs: ['repair-ref:mag/strategy-tightening'],
          trace_refs: ['trace-ref:codex/mag-grant-section-smoke'],
          command_refs: ['command-ref:codex/mag-grant-section-smoke'],
          file_refs: ['file-ref:mag/section-draft-fixture'],
          subagent_refs: ['subagent-ref:codex/mag-strategy-review'],
          worktree_refs: ['worktree-ref:codex/mag-grant-section-smoke'],
          test_refs: ['test-ref:mag/grant-stage-smoke'],
          web_source_refs: ['source-ref:mag/funder-guidance-fixture'],
          typed_blocker_refs: ['typed-blocker-ref:agent-lab/mag/no-current-blocker-fixture'],
          review_receipt_refs: ['review-receipt-ref:mag/domain-review-fixture'],
          next_run_falsification_refs: ['next-run-falsification-ref:mag/stage-policy-tightening'],
        },
        scorecard: {
          scorecard_ref: 'quality-scorecard:mag/grant-section-smoke',
          domain_owned: true,
          opl_scorecard_role: 'scorecard_ref_projection_only',
          passed: true,
          metric_refs: ['metric-ref:mag/specific-aim-fit'],
          evidence_refs: ['evidence-ref:mag/fundability-fixture'],
          review_refs: ['review-ref:mag/domain-review-fixture'],
          quality_gate_refs: ['quality-gate:mag/fundability-owner'],
        },
        improvement_candidate: {
          candidate_ref: 'improvement-candidate:mag/stage-policy-tightening',
          candidate_kind: 'stage_policy',
          target_ref: 'stage-policy-ref:mag/section-revision',
          evidence_refs: ['failure-taxonomy:mag/no-current-failure-fixture'],
          allowed_change_scope: 'branch_only',
          promotion_gate_ref: 'promotion-gate:mag/grant-section-smoke',
        },
        promotion_gate: {
          gate_ref: 'promotion-gate:mag/grant-section-smoke',
          gate_status: 'passed',
          required_refs: ['quality-scorecard:mag/grant-section-smoke'],
          regression_suite_refs: ['regression-suite:mag/grant-stage-smoke'],
          no_forbidden_write_proof_refs: ['no-forbidden-write:mag/agent-lab-fixture'],
        },
      }),
      task({
        task_id: 'agent-lab-task:rca/visual-deliverable-smoke',
        domain_id: 'redcube-ai',
        task_family: 'presentation_foundry_visual_delivery',
        environment: {
          environment_kind: 'fixture',
          workspace_locator_ref: 'workspace-locator:rca/sample-visual-deliverable',
          sandbox_policy: 'fixture_only_no_artifact_mutation',
          network_policy: 'offline',
        },
        instructions_ref: 'instructions:rca/visual-deliverable-smoke',
        agent_entry_ref: 'domain-agent-entry:redcube-ai',
        stage_refs: ['stage:rca/source-intake', 'stage:rca/render-review'],
        oracle_refs: ['oracle:rca/no-regression-fixture'],
        scorer_refs: ['scorer:rca/visual-quality-ref'],
        recovery_probes: [
          {
            probe_ref: 'recovery-probe:rca/artifact-restore',
            probe_kind: 'artifact_restore',
            expected_status: 'passed',
            observed_status: 'passed',
            source_refs: ['restore-proof:rca/visual-fixture'],
          },
          {
            probe_ref: 'recovery-probe:rca/dead-letter-repair',
            probe_kind: 'dead_letter_repair',
            expected_status: 'passed',
            observed_status: 'passed',
            source_refs: ['repair-receipt:rca/render-retry-fixture'],
          },
        ],
        trajectory: {
          trajectory_ref: 'trajectory:rca/visual-deliverable-smoke',
          run_ref: 'run:rca/visual-deliverable-smoke',
          agent_executor: 'codex_cli',
          stage_attempt_refs: ['stage-attempt:rca/visual-deliverable-smoke'],
          tool_call_refs: ['tool-call:rca/render-html'],
          artifact_refs: ['artifact-ref:rca/visual-package-fixture'],
          receipt_refs: ['owner-receipt:rca/no-regression-fixture'],
          repair_refs: ['repair-ref:rca/render-review-retry'],
          trace_refs: ['trace-ref:codex/rca-visual-deliverable-smoke'],
          command_refs: ['command-ref:codex/rca-visual-deliverable-smoke'],
          file_refs: ['file-ref:rca/visual-package-fixture'],
          subagent_refs: ['subagent-ref:codex/rca-render-review'],
          worktree_refs: ['worktree-ref:codex/rca-visual-deliverable-smoke'],
          test_refs: ['test-ref:rca/visual-no-regression-smoke'],
          web_source_refs: ['source-ref:rca/brand-source-fixture'],
          typed_blocker_refs: ['typed-blocker-ref:agent-lab/rca/no-current-blocker-fixture'],
          review_receipt_refs: ['review-receipt-ref:rca/visual-review-fixture'],
          next_run_falsification_refs: ['next-run-falsification-ref:rca/render-policy-tightening'],
        },
        scorecard: {
          scorecard_ref: 'quality-scorecard:rca/visual-deliverable-smoke',
          domain_owned: true,
          opl_scorecard_role: 'scorecard_ref_projection_only',
          passed: true,
          metric_refs: ['metric-ref:rca/block-content-fit'],
          evidence_refs: ['evidence-ref:rca/screenshot-review-fixture'],
          review_refs: ['review-ref:rca/visual-review-fixture'],
          quality_gate_refs: ['quality-gate:rca/visual-owner'],
        },
        improvement_candidate: {
          candidate_ref: 'improvement-candidate:rca/render-policy-tightening',
          candidate_kind: 'tool_policy',
          target_ref: 'tool-policy-ref:rca/render-review',
          evidence_refs: ['failure-taxonomy:rca/no-current-failure-fixture'],
          allowed_change_scope: 'branch_only',
          promotion_gate_ref: 'promotion-gate:rca/visual-route-smoke',
        },
        promotion_gate: {
          gate_ref: 'promotion-gate:rca/visual-route-smoke',
          gate_status: 'passed',
          required_refs: ['quality-scorecard:rca/visual-deliverable-smoke'],
          regression_suite_refs: ['regression-suite:rca/visual-no-regression-smoke'],
          no_forbidden_write_proof_refs: ['no-forbidden-write:rca/agent-lab-fixture'],
        },
      }),
    ],
  };
}
