export const STAGE_RUN_CANARY_EVIDENCE = {
  surface_kind: 'opl_stage_run_controlled_canary_evidence',
  version: 'stage-run-controlled-canary.v1',
  evidence_scope: 'controlled_fixture_not_live_domain_progress',
  domain_id: 'sample-domain',
  canary_id: 'sample-domain.controlled-stage-run-canary.v1',
  stage_id: 'domain_intake',
  stage_run_ref: 'stage-run-ref:sample-domain/controlled-canary',
  stage_manifest_ref: 'stage-manifest-ref:sample-domain/controlled-canary',
  current_pointer_ref: 'stage-current-pointer-ref:sample-domain/controlled-canary',
  strategy_trace: {
    candidate_generation: ['candidate-pool-ref:sample-domain/controlled-canary'],
    grounded_reflection: ['reflection-review-ref:sample-domain/controlled-canary'],
    comparative_selection: ['ranking-selection-ref:sample-domain/controlled-canary'],
    evolution_and_revision: ['revision-lineage-ref:sample-domain/controlled-canary'],
    strategy_retrospective: ['strategy-retrospective-ref:sample-domain/controlled-canary'],
    independent_quality_gate: ['independent-gate-ref:sample-domain/controlled-canary'],
  },
  role_artifact_refs: {
    candidate_pool_ref: 'candidate-pool-ref:sample-domain/controlled-canary',
    reflection_review_ref: 'reflection-review-ref:sample-domain/controlled-canary',
    ranking_selection_ref: 'ranking-selection-ref:sample-domain/controlled-canary',
    revision_lineage_ref: 'revision-lineage-ref:sample-domain/controlled-canary',
    strategy_retrospective_ref: 'strategy-retrospective-ref:sample-domain/controlled-canary',
    independent_gate_ref: 'independent-gate-ref:sample-domain/controlled-canary',
  },
  closeout: {
    terminal_outcome: 'typed_blocker',
    typed_blocker_ref: 'typed-blocker-ref:sample-domain/controlled-canary',
    owner_receipt_ref: null,
    same_attempt_self_review: false,
  },
  authority_boundary: {
    refs_only: true,
    controlled_canary_claims_live_domain_progress: false,
    provider_completion_counts_as_closeout: false,
    file_presence_counts_as_closeout: false,
    read_model_counts_as_closeout: false,
    conformance_pass_counts_as_closeout: false,
    opl_can_write_domain_truth: false,
    opl_can_mutate_artifact_body: false,
    opl_can_sign_owner_receipt: false,
    opl_can_create_typed_blocker: false,
    opl_can_authorize_quality_or_export: false,
  },
} as const;

export function buildStageRunCanaryEvidence(domainId: string, stageId: string) {
  return {
    ...STAGE_RUN_CANARY_EVIDENCE,
    domain_id: domainId,
    canary_id: `${domainId}.controlled-stage-run-canary.v1`,
    stage_id: stageId,
    stage_run_ref: `stage-run-ref:${domainId}/controlled-canary`,
    stage_manifest_ref: `stage-manifest-ref:${domainId}/controlled-canary`,
    current_pointer_ref: `stage-current-pointer-ref:${domainId}/controlled-canary`,
    strategy_trace: {
      candidate_generation: [`candidate-pool-ref:${domainId}/controlled-canary`],
      grounded_reflection: [`reflection-review-ref:${domainId}/controlled-canary`],
      comparative_selection: [`ranking-selection-ref:${domainId}/controlled-canary`],
      evolution_and_revision: [`revision-lineage-ref:${domainId}/controlled-canary`],
      strategy_retrospective: [`strategy-retrospective-ref:${domainId}/controlled-canary`],
      independent_quality_gate: [`independent-gate-ref:${domainId}/controlled-canary`],
    },
    role_artifact_refs: {
      candidate_pool_ref: `candidate-pool-ref:${domainId}/controlled-canary`,
      reflection_review_ref: `reflection-review-ref:${domainId}/controlled-canary`,
      ranking_selection_ref: `ranking-selection-ref:${domainId}/controlled-canary`,
      revision_lineage_ref: `revision-lineage-ref:${domainId}/controlled-canary`,
      strategy_retrospective_ref: `strategy-retrospective-ref:${domainId}/controlled-canary`,
      independent_gate_ref: `independent-gate-ref:${domainId}/controlled-canary`,
    },
    closeout: {
      terminal_outcome: 'typed_blocker',
      typed_blocker_ref: `typed-blocker-ref:${domainId}/controlled-canary`,
      owner_receipt_ref: null,
      same_attempt_self_review: false,
    },
  };
}
