import type { AgentWorkspaceNormContract } from '../../../../src/types.ts';

export const MINIMAL_AGENT_WORKSPACE_NORM_CONTRACT: AgentWorkspaceNormContract = {
  surface_kind: 'opl_agent_workspace_norm_contract',
  version: 'agent-workspace-norm.v1',
  norm_id: 'opl.agent_workspace_norm.v1',
  owner: 'one-person-lab',
  scope: 'test fixture',
  machine_boundary: 'test fixture',
  supported_agents: ['mas', 'mag', 'rca', 'oma'],
  default_workspace_precondition: {
    action_id: 'opl_workspace_ensure',
    command: 'opl workspace ensure',
    app_action_id: 'workspace_ensure',
    required_inputs: ['agent_id'],
    optional_inputs: ['workspace_path_or_workspace_root', 'workspace_id', 'project_id', 'mode', 'title', 'dry_run', 'force', 'bind'],
    must_run_before_domain_task_when_no_active_binding: true,
    reuse_active_binding_first: true,
    initialize_missing_workspace: true,
    append_missing_project_in_compatible_series_or_portfolio: true,
    default_entry_for_agents: true,
  },
  explicit_initialization: {
    command: 'opl workspace init',
    app_action_id: 'workspace_initialize',
    role: 'explicit_initialization_or_operator_override',
    default_entry_for_agents: false,
  },
  descriptor_delegates: {
    mcp: {
      tool_name: 'opl_workspace_ensure',
      execution: 'delegate_to_opl_cli',
      descriptor_only: true,
      public_runtime: false,
    },
    skill: {
      intent: 'ensure_opl_workspace',
      command_contract_id: 'opl_workspace_ensure',
    },
    openai: {
      tool_name: 'opl_workspace_ensure',
    },
    ai_sdk: {
      tool_name: 'oplWorkspaceEnsure',
    },
  },
  topology_contract: {
    contract_ref: 'contracts/opl-framework/workspace-topology-profile.schema.json',
    profile_id: 'opl.workspace_topology_profile.v1',
    topology_model: ['workspace_group', 'project_unit', 'stage_artifact_unit', 'owner_receipt_or_typed_blocker'],
    project_stage_outputs_root: 'artifacts/stage_outputs',
    default_project_collection_path: 'deliverables',
    workspace_modes: ['one_off', 'series', 'portfolio'],
    series_capable_one_off_skeleton: true,
  },
  domain_topology_profiles: {
    mas: {
      profile: 'mas_portfolio',
      workspace_mode: 'portfolio',
      project_kind: 'study',
      project_collection_path: 'studies',
      shared_resource_roots: ['data', 'literature', 'memory', 'shared/sources'],
    },
    mag: {
      profile: 'one_off',
      workspace_mode: 'one_off',
      project_kind: 'grant_project',
      project_collection_path: 'deliverables',
      shared_resource_roots: ['shared/sources', 'shared/memory', 'shared/style_system'],
    },
    rca: {
      profile: 'rca_series',
      workspace_mode: 'series',
      project_kind: 'slide_deck',
      project_collection_path: 'deliverables',
      shared_resource_roots: ['shared/sources', 'shared/brand', 'shared/visual_memory', 'shared/style_system', 'shared/material_inventory'],
    },
    oma: {
      profile: 'one_off',
      workspace_mode: 'one_off',
      project_kind: 'agent_capability',
      project_collection_path: 'deliverables',
      shared_resource_roots: ['shared/sources', 'shared/memory', 'shared/style_system'],
    },
  },
  user_inspection: {
    ordinary_user_default_surface: 'workspace_local_project_stage_outputs',
    project_stage_outputs_pattern: '<project-root>/artifacts/stage_outputs/<stage-id>/',
    workspace_index_file: 'workspace_index.json',
    workspace_config_file: 'workspace.yaml',
    runtime_state_is_default_user_surface: false,
    product_views_are_stage_outputs: false,
  },
  registry_policy: {
    writes_opl_workspace_registry: true,
    binding_owner: 'one-person-lab',
    domain_repo_can_write_opl_registry: false,
  },
  runtime_state_boundary: {
    role: 'provider_backing_provenance_restore_audit',
    runtime_state_can_be_canonical_project_root: false,
    runtime_state_can_close_stage: false,
    runtime_state_can_replace_owner_receipt_or_typed_blocker: false,
  },
  authority_boundary: {
    opl_can_define_topology_contract: true,
    opl_can_project_workspace_refs: true,
    opl_can_write_domain_truth: false,
    opl_can_write_memory_body: false,
    opl_can_mutate_artifact_body: false,
    opl_can_create_owner_receipt: false,
    opl_can_create_typed_blocker: false,
    opl_can_authorize_quality_or_export: false,
    runtime_state_counts_as_user_default_surface: false,
    conformance_pass_counts_as_domain_ready: false,
  },
  conformance_policy: {
    family_conformance_must_report_workspace_norm: true,
    workspace_norm_pass_is_structural_only: true,
    workspace_norm_pass_can_claim_domain_ready: false,
    workspace_norm_pass_can_claim_artifact_or_quality_ready: false,
    blocked_reasons: [],
  },
};
