import { spawnSync } from 'node:child_process';

import { assert, fs, os, path, repoRoot, runCli, test } from '../helpers.ts';

test('agent-lab sample exposes a minimal framework read-model sample', () => {
  const output = runCli(['agent-lab', 'sample', '--json']);

  assert.equal(output.version, 'g2');
  assert.equal(output.agent_lab_sample.surface_id, 'opl_agent_lab_framework_sample');
  assert.equal(output.agent_lab_sample.sample_result.surface_kind, 'opl_agent_lab_suite_result');
  assert.equal(output.agent_lab_sample.sample_result.status, 'passed');
  assert.equal(output.agent_lab_sample.sample_result.summary.task_count, 3);
  assert.equal(output.agent_lab_sample.sample_result.summary.recovery_probe_count, 5);
  assert.deepEqual(output.agent_lab_sample.ref_summary.scorecard_refs, [
    'quality-scorecard:mas/paper-repair-smoke',
    'quality-scorecard:mag/grant-section-smoke',
    'quality-scorecard:rca/visual-deliverable-smoke',
  ]);
  assert.equal(output.agent_lab_sample.authority_boundary.can_authorize_quality_verdict, false);
  assert.equal(output.agent_lab_sample.authority_boundary.can_write_memory_body, false);
});

test('agent-lab longline exposes the central cross-domain longline suite and repo test reduction guidance', () => {
  const output = runCli(['agent-lab', 'longline', '--json']);

  assert.equal(output.version, 'g2');
  assert.equal(output.agent_lab_longline.surface_id, 'opl_agent_lab_longline_suite');
  assert.equal(output.agent_lab_longline.suite_result.status, 'passed');
  assert.equal(output.agent_lab_longline.suite_result.suite_kind, 'agent_lab_longline_suite');
  assert.equal(output.agent_lab_longline.suite_result.longline_summary.longline_task_count, 3);
  assert.equal(output.agent_lab_longline.suite_result.longline_summary.ready_to_reduce_domain_longline_tests, true);
  assert.deepEqual(output.agent_lab_longline.suite_result.longline_summary.domain_ids, [
    'med-autoscience',
    'med-autogrant',
    'redcube-ai',
  ]);
  assert.equal(output.agent_lab_longline.authority_boundary.can_authorize_quality_verdict, false);
  assert.equal(output.agent_lab_longline.authority_boundary.can_write_domain_truth, false);
});

test('agent-lab complete exposes the complete eval, observability, and optimizer control plane', () => {
  const output = runCli(['agent-lab', 'complete', '--json']);

  assert.equal(output.version, 'g2');
  assert.equal(output.agent_lab_complete.surface_kind, 'opl_agent_lab_complete_control_plane');
  assert.equal(output.agent_lab_complete.status, 'ready_for_opl_native_use');
  assert.equal(output.agent_lab_complete.readiness.ready_to_connect_inspect_ai_adapter, true);
  assert.equal(output.agent_lab_complete.readiness.ready_to_emit_optimizer_candidate_refs, true);
  assert.equal(output.agent_lab_complete.readiness.automatic_model_training_ready, false);
  assert.equal(output.agent_lab_complete.readiness.automatic_default_agent_promotion_ready, false);
  assert.ok(output.agent_lab_complete.eval_adapters.some((entry: any) => entry.adapter_id === 'inspect-ai'));
  assert.ok(output.agent_lab_complete.observability_exports.some((entry: any) => entry.export_id === 'phoenix'));
});

test('agent-lab run accepts an external OPL-compatible suite generated by an OPL meta-agent', () => {
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'opl-agent-lab-external-suite-'));
  const suitePath = path.join(tmpDir, 'suite.json');
  const suite = {
    suite_id: 'opl-meta-agent-self-bootstrap-suite',
    suite_kind: 'agent_lab_external_suite',
    authority_boundary: {
      can_write_domain_truth: false,
      can_write_memory_body: false,
      can_authorize_quality_verdict: false,
      can_promote_default_agent_without_gate: false,
    },
    tasks: [
      {
        task_id: 'agent-lab-task:opl-meta-agent/sample-brief-agent-baseline',
        domain_id: 'opl-meta-agent',
        task_family: 'agent_building_baseline',
        environment: {
          environment_kind: 'fixture',
          workspace_locator_ref: 'workspace-locator:opl-meta-agent/sample-brief-agent',
          sandbox_policy: 'fixture_only_no_artifact_mutation',
          network_policy: 'offline',
        },
        instructions_ref: 'instructions:opl-meta-agent/sample-brief-agent',
        agent_entry_ref: 'domain-agent-entry:sample-brief-agent',
        stage_refs: ['stage:sample-brief-agent/intake', 'stage:sample-brief-agent/draft'],
        oracle_refs: ['oracle:opl-meta-agent/baseline-contract-valid'],
        scorer_refs: ['scorer:opl-meta-agent/baseline-acceptance'],
        recovery_probes: [
          {
            probe_ref: 'recovery-probe:opl-meta-agent/resume-after-interruption',
            probe_kind: 'resume_after_interruption',
            expected_status: 'passed',
            observed_status: 'passed',
            source_refs: ['receipt:opl-meta-agent/resume-fixture'],
          },
        ],
        trajectory: {
          trajectory_ref: 'trajectory:opl-meta-agent/sample-brief-agent-baseline',
          run_ref: 'run:opl-meta-agent/sample-brief-agent-baseline',
          agent_executor: 'codex_cli',
          stage_attempt_refs: ['stage-attempt:opl-meta-agent/sample-brief-agent-baseline'],
          tool_call_refs: ['tool-call:opl-agents-scaffold'],
          artifact_refs: ['artifact-ref:sample-brief-agent/package'],
          receipt_refs: ['owner-receipt:opl-meta-agent/baseline-delivery'],
          repair_refs: ['repair-ref:opl-meta-agent/no-current-repair'],
        },
        scorecard: {
          scorecard_ref: 'quality-scorecard:opl-meta-agent/baseline-acceptance',
          domain_owned: true,
          opl_scorecard_role: 'scorecard_ref_projection_only',
          passed: true,
          metric_refs: ['metric-ref:descriptor-valid', 'metric-ref:agent-lab-suite-valid'],
          evidence_refs: ['evidence-ref:sample-brief-agent/scaffold-validation'],
          review_refs: ['review-ref:opl-meta-agent/baseline-review'],
          quality_gate_refs: ['quality-gate:opl-meta-agent/baseline-owner'],
        },
        improvement_candidate: {
          candidate_ref: 'improvement-candidate:opl-meta-agent/rubric-gap-tightening',
          candidate_kind: 'rubric_gap',
          target_ref: 'quality-gate:opl-meta-agent/baseline-owner',
          evidence_refs: ['failure-taxonomy:opl-meta-agent/no-current-failure-fixture'],
          allowed_change_scope: 'branch_only',
          promotion_gate_ref: 'promotion-gate:opl-meta-agent/sample-brief-agent',
        },
        promotion_gate: {
          gate_ref: 'promotion-gate:opl-meta-agent/sample-brief-agent',
          gate_status: 'passed',
          required_refs: ['quality-scorecard:opl-meta-agent/baseline-acceptance'],
          regression_suite_refs: ['regression-suite:opl-meta-agent/self-bootstrap'],
          no_forbidden_write_proof_refs: ['no-forbidden-write:opl-meta-agent/self-bootstrap'],
        },
      },
    ],
  };

  try {
    fs.writeFileSync(suitePath, `${JSON.stringify(suite, null, 2)}\n`);
    const output = runCli(['agent-lab', 'run', '--suite', suitePath, '--json']);

    assert.equal(output.version, 'g2');
    assert.equal(output.agent_lab_run.surface_id, 'opl_agent_lab_external_suite_run');
    assert.equal(output.agent_lab_run.suite_result.status, 'passed');
    assert.equal(output.agent_lab_run.suite_result.suite_kind, 'agent_lab_external_suite');
    assert.deepEqual(output.agent_lab_run.suite_result.domain_summary.map((entry: any) => entry.domain_id), [
      'opl-meta-agent',
    ]);
    assert.ok(output.agent_lab_run.ref_summary.improvement_candidate_refs.includes(
      'improvement-candidate:opl-meta-agent/rubric-gap-tightening',
    ));
    assert.equal(output.agent_lab_run.authority_boundary.can_write_memory_body, false);
  } finally {
    fs.rmSync(tmpDir, { recursive: true, force: true });
  }
});

test('bin/opl routes agent-lab commands into the OPL CLI instead of Codex passthrough', () => {
  const result = spawnSync(
    path.join(repoRoot, 'bin', 'opl'),
    ['agent-lab', 'complete', '--json'],
    {
      cwd: repoRoot,
      encoding: 'utf8',
      env: {
        ...process.env,
        NODE_NO_WARNINGS: '1',
        OPL_SKIP_SKILL_SYNC: '1',
      },
    },
  );

  assert.equal(result.status, 0, result.stderr);
  const output = JSON.parse(result.stdout);
  assert.equal(output.agent_lab_complete.surface_kind, 'opl_agent_lab_complete_control_plane');
});

test('agent-lab command surface does not embed the independent meta-agent product', () => {
  const output = runCli(['help']);
  const commands = output.help.commands.map((entry: { command: string }) => entry.command);
  const examples = output.help.examples as string[];

  assert.equal(commands.some((command: string) => command.includes('meta-builder')), false);
  assert.equal(commands.some((command: string) => command.includes('meta-agent')), false);
  assert.equal(examples.some((example) => example.includes('meta-builder')), false);
  assert.equal(examples.some((example) => example.includes('meta-agent')), false);
});
