import type {
  AgentWorkspaceNormContract,
  BrandCliGovernanceContract,
  BrandModuleL5OperatingEvidenceContract,
  BrandModuleRegistryContract,
  BrandModuleSurfacesContract,
  BrandSystemProfileContract,
  PackOsContract,
  TargetOperatingArchitectureContract,
} from '../../../../src/types.ts';

export const MINIMAL_PACK_OS_CONTRACT: PackOsContract = {
  schema_version: 1,
  contract_id: 'opl-pack-os-contract.v1',
  owner: 'One Person Lab',
  purpose: 'test fixture',
  state: 'active_l4_structural_baseline',
  machine_boundary: 'test fixture',
  source_module: 'src/pack-os.ts',
  cli_surfaces: {
    inspect: 'opl pack os inspect --descriptor <path>',
    lock: 'opl pack os lock --descriptor <path>',
    validate: 'opl pack os validate --descriptor <path>',
    mas_display_smoke: 'opl pack os mas-display-smoke --contract <path>',
  },
  descriptor_contract: {
    surface_kind: 'opl_generic_capability_pack_descriptor',
    required_fields: [
      'pack_id',
      'version',
      'pack_kind',
      'owner',
      'capabilities',
      'resources',
      'artifact_lifecycle',
      'review_transport',
      'authority_boundary',
      'provenance',
    ],
    allowed_pack_kinds: [
      'display_pack',
      'domain_pack',
      'deck_pack',
      'report_pack',
      'app_ui_pack',
      'generic_capability_pack',
    ],
    resource_roles: [
      'descriptor',
      'template',
      'schema',
      'renderer',
      'style_tokens',
      'qc_profile',
      'golden',
      'exemplar_ref',
      'receipt_ref',
      'artifact_ref',
    ],
    relationship_to_domain_packs: 'test fixture',
  },
  lock_contract: {
    surface_kind: 'opl_generic_pack_lock',
    output_role: 'refs_only_pack_resolution_lock',
    required_fields: [
      'lock_id',
      'pack_id',
      'version',
      'pack_kind',
      'descriptor_ref',
      'descriptor_sha256',
      'resolved_resources',
      'artifact_lifecycle',
      'review_transport',
      'authority_boundary',
      'provenance',
    ],
    content_hash_algorithm: 'sha256',
    lock_projection_rule: 'test fixture',
  },
  lifecycle_model: {
    allowed_states: [
      'declared',
      'resolved',
      'locked',
      'cached',
      'artifact_refs_observed',
      'review_receipts_observed',
      'handoff_ready',
      'retained',
      'restored',
      'retired',
    ],
    hard_boundaries: [
      'content_hash_required_for_present_local_file',
      'artifact_body_not_stored_in_opl_contract',
      'review_receipt_transport_does_not_authorize_quality_verdict',
      'domain_owner_receipt_required_for_domain_truth_or_artifact_authority',
    ],
  },
  authority_boundary: {
    opl_can_resolve_pack_descriptor: true,
    opl_can_write_pack_lock: true,
    opl_can_cache_pack_assets: true,
    opl_can_project_artifact_locator_refs: true,
    opl_can_transport_review_receipt_refs: true,
    opl_can_write_domain_truth: false,
    opl_can_mutate_artifact_body: false,
    opl_can_sign_domain_owner_receipt: false,
    opl_can_authorize_quality_verdict: false,
    opl_can_authorize_publication_readiness: false,
    opl_can_authorize_grant_readiness: false,
    opl_can_authorize_visual_export_readiness: false,
    opl_can_authorize_app_release_readiness: false,
    provider_completion_is_pack_quality_ready: false,
  },
  domain_handoff: {
    mas_display_pack_v2: {
      source_contract_ref: 'med-autoscience:contracts/display-pack-contract.v2.json',
      transport_role: 'test fixture',
      domain_authority_owner: 'MedAutoScience',
      consumer_smoke_surface: 'opl pack os mas-display-smoke --contract <path>',
      audit_surface: 'opl_pack_os_mas_display_pack_v2_audit',
      forbidden_claim: 'test fixture',
    },
    future_family_packs: ['test fixture'],
  },
  forbidden_claims: [
    'pack_lock_is_domain_ready',
    'review_receipt_transport_is_quality_verdict',
    'artifact_locator_ref_is_artifact_authority',
    'provider_completion_is_pack_quality_ready',
    'OPL Pack OS owns MAS publication quality',
    'OPL Pack OS mutates domain artifact bodies',
  ],
  verification: {
    focused_tests: [
      'tests/src/pack-os.test.ts',
      'tests/src/cli/cases/pack-os-command-surface.test.ts',
    ],
    required_commands_when_changed: [
      'node --experimental-strip-types --test tests/src/pack-os.test.ts tests/src/cli/cases/pack-os-command-surface.test.ts',
      'npm run typecheck',
      'scripts/verify.sh',
    ],
  },
};

export const MINIMAL_TARGET_OPERATING_ARCHITECTURE_CONTRACT: TargetOperatingArchitectureContract = {
  contract_kind: 'opl_target_operating_architecture_contract.v1',
  schema_version: 'target-operating-architecture.v1',
  owner: 'one-person-lab',
  purpose: 'test fixture',
  state: 'active_contract',
  machine_boundary: 'test fixture',
  source_refs: ['human_doc:test_fixture'],
  design_principles: [
    'grip_big_release_small',
    'current_owner_delta_first',
    'single_writer_stage_transition_authority',
    'declarative_domain_pack_generated_surfaces_authority_abi',
    'passive_evidence_vault',
    'one_ordinary_golden_path_per_agent',
    'small_idempotent_reconcilers',
    'app_console_thin_default_surface',
    'agent_lab_refs_only_improvement_control_plane',
    'runway_control_loop_runtime_module',
  ],
  resource_model: {
    resource_shape: {
      required_fields: ['apiVersion', 'kind', 'metadata', 'spec', 'status', 'conditions', 'ownerRefs', 'finalizers'],
      spec_status_split_required: true,
      status_can_define_desired_state: false,
      conditions_are_status_not_truth: true,
    },
    resource_kinds: [
      { kind: 'Agent', owner: 'domain_owner', default_lane: 'ordinary', truth_boundary: 'test fixture' },
      { kind: 'DomainPack', owner: 'domain_owner', default_lane: 'ordinary', truth_boundary: 'test fixture' },
      { kind: 'WorkspaceGroup', owner: 'one-person-lab', default_lane: 'ordinary', truth_boundary: 'test fixture' },
      { kind: 'ProjectUnit', owner: 'domain_owner', default_lane: 'ordinary', truth_boundary: 'test fixture' },
      { kind: 'StageRun', owner: 'one-person-lab', default_lane: 'ordinary', truth_boundary: 'test fixture' },
      { kind: 'StageArtifactUnit', owner: 'domain_owner', default_lane: 'ordinary', truth_boundary: 'test fixture' },
      { kind: 'OwnerAnswer', owner: 'domain_or_human_owner', default_lane: 'ordinary', truth_boundary: 'test fixture' },
      { kind: 'EvidenceRef', owner: 'one-person-lab', default_lane: 'audit', truth_boundary: 'test fixture' },
      { kind: 'ReleaseCohort', owner: 'app_release_owner', default_lane: 'production_evidence', truth_boundary: 'test fixture' },
      { kind: 'ImprovementWorkOrder', owner: 'agent_lab', default_lane: 'advisory', truth_boundary: 'test fixture' },
      { kind: 'RunwayControlLoop', owner: 'one-person-lab', default_lane: 'ordinary', truth_boundary: 'test fixture' },
      { kind: 'ProgressReconciler', owner: 'one-person-lab', default_lane: 'ordinary', truth_boundary: 'test fixture' },
    ],
  },
  stage_transition_authority: {
    authority_owner: 'one-person-lab',
    single_writer: true,
    event_log_policy: 'append_only_authority_event_log',
    derived_state: [
      'stage_current_pointer',
      'stage_run_terminal_state',
      'current_owner_delta',
      'runway_control_loop_status',
      'progress_reconciler_projection',
    ],
    accepted_inputs: [
      'transition_intent',
      'provider_observation',
      'owner_answer',
      'typed_blocker',
      'human_gate_decision',
      'agent_lab_observation',
      'evidence_observation',
      'runtime_intent',
      'progress_reconciler_observation',
      'handoff_gate_decision',
      'recovery_repair_observation',
    ],
    forbidden_direct_writers: [
      'domain_agent',
      'runtime_provider',
      'one_person_lab_app',
      'agent_lab',
      'read_model',
      'evidence_vault',
      'worklist',
      'runway_control_loop',
      'progress_reconciler',
      'worker_supervisor',
      'temporal_workflow_history',
    ],
  },
  domain_pack_authority_abi: {
    default_agent_shape: 'declarative_domain_pack_plus_opl_generated_hosted_surfaces_plus_standard_authority_functions',
    domain_pack_must_declare: [
      'stage_graph',
      'ordinary_golden_path',
      'prompt_refs',
      'skill_refs',
      'tool_affordance_boundary_refs',
      'knowledge_refs',
      'quality_gate_refs',
      'artifact_policy',
      'memory_policy',
      'owner_answer_schema',
      'authority_functions',
      'fixtures',
      'tests',
    ],
    opl_generated_or_hosted_surfaces: [
      'cli',
      'mcp',
      'skill_plugin',
      'product_entry',
      'openai_tool',
      'ai_sdk',
      'status_read_model',
      'workbench',
      'functional_harness',
      'operator_projection',
    ],
    authority_functions: [
      'quality_or_export_verdict',
      'artifact_authority',
      'memory_accept_reject',
      'owner_receipt_signer',
      'typed_blocker_signer',
      'human_gate_signer',
    ],
    private_platform_residue_default_disposition: 'absorb_to_opl_primitive_or_tombstone_after_owner_decision',
  },
  surface_budget_compiler_policy: {
    ordinary_path_root: 'current_owner_delta',
    allowed_lanes: ['ordinary', 'advisory', 'audit', 'diagnostic', 'cleanup', 'production_evidence'],
    small_detail_default_lanes: ['advisory', 'audit', 'diagnostic', 'cleanup', 'production_evidence'],
    hard_blocker_upgrade_conditions: [
      'wrong_launch',
      'authority_violation',
      'not_recoverable',
      'not_auditable',
      'cannot_closeout',
      'invalid_owner_answer_shape',
      'irreversible_mutation',
    ],
    ordinary_path_must_not_be_overridden_by: [
      'raw_worklist',
      'evidence_ledger',
      'provider_trace',
      'route_variant_menu',
      'private_residue_inventory',
      'cleanup_delete_gate',
      'l5_evidence_ledger',
      'release_diagnostics',
    ],
    accepted_owner_answer_shapes: [
      'owner_receipt_ref',
      'domain_owner_receipt_ref',
      'quality_gate_receipt_ref',
      'human_gate_ref',
      'typed_blocker_ref',
      'no_regression_ref',
      'long_soak_ref',
      'route_back_ref',
      'route_back_evidence_ref',
      'physical_delete_authorization_ref',
      'keep_as_authority_adapter_ref',
    ],
  },
  reconciler_model: {
    loop_granularity: 'small_idempotent_reconcilers_with_runway_control_loop_runtime',
    required_loops: [
      'recovery_repair',
      'handoff_gate',
      'progress_reconciliation',
      'runtime_intent_admission',
      'admission',
      'execution_authorization',
      'provider_attempt',
      'closeout_binding',
      'owner_answer_intake',
      'evidence_verify',
      'cleanup_finalizer',
      'release_cohort_verify',
    ],
    loop_authority_boundary: {
      reconciler_can_generate_candidates: false,
      reconciler_can_evaluate_or_rank_candidates: false,
      reconciler_can_complete_stage: false,
      reconciler_can_sign_receipts: false,
      reconciler_can_create_typed_blocker: false,
      reconciler_can_write_domain_truth: false,
    },
    substrate_policy: {
      temporal_role: 'durable_workflow_history_activity_heartbeat_visibility_and_retry_substrate_only',
      worker_supervisor_role: 'process_liveness_restart_and_host_health_only',
      progress_reconciler_role: 'semantic_execution_loop_desired_current_reconciliation_and_next_owner_projection',
      false_authority_boundary: 'no_domain_truth_no_owner_receipt_no_typed_blocker_no_quality_verdict_no_artifact_or_memory_body',
    },
  },
  catalog_and_telemetry: {
    atlas_catalogs: ['agents', 'domain_packs', 'resources', 'surfaces', 'contracts', 'skills', 'mcp_tools', 'app_pages', 'release_channels'],
    vault_ref_streams: ['evidence_refs', 'receipt_refs', 'typed_blocker_refs', 'trace_refs', 'metric_refs', 'log_refs', 'artifact_lineage_refs'],
    vault_policy: 'record_everything_plan_from_nothing',
    telemetry_body_policy: 'refs_only_no_artifact_or_memory_body',
  },
  app_console_policy: {
    default_screen_fields: ['task', 'stage', 'current_owner', 'next_action', 'running_or_blocked_status', 'artifact_or_blocker', 'accepted_answer_shape'],
    drilldown_only_fields: ['provider_trace', 'attempt_ledger', 'release_diagnostics', 'cleanup_inventory', 'l5_evidence', 'raw_evidence', 'route_variant_menu'],
    gui_truth_owner: 'one-person-lab-app',
    framework_role: 'state_action_projection_producer_only',
  },
  agent_lab_improvement_plane: {
    role: 'refs_only_improvement_control_plane',
    may_produce: ['eval_ref', 'root_cause_ref', 'candidate_fix_ref', 'work_order_ref', 'promotion_proposal_ref', 'rollback_ref', 'reevaluation_ref'],
    must_not_produce: ['domain_quality_verdict', 'artifact_authority', 'memory_body', 'owner_receipt', 'typed_blocker', 'production_acceptance'],
  },
  authority_boundary: {
    can_claim_domain_ready: false,
    can_claim_quality_verdict: false,
    can_claim_artifact_authority: false,
    can_claim_production_ready: false,
    can_write_domain_truth: false,
    can_write_memory_body: false,
    can_mutate_artifact_body: false,
    can_sign_owner_receipt: false,
    can_create_typed_blocker: false,
    can_replace_domain_owner: false,
    can_replace_ai_executor_planning: false,
    can_replace_app_release_truth: false,
  },
  forbidden_claims: ['contract_validation_is_domain_ready'],
};

export const MINIMAL_AGENT_WORKSPACE_NORM_CONTRACT: AgentWorkspaceNormContract = {
  surface_kind: 'opl_agent_workspace_norm_contract',
  version: 'agent-workspace-norm.v1',
  norm_id: 'opl.agent_workspace_norm.v1',
  owner: 'one-person-lab',
  scope: 'test fixture',
  machine_boundary: 'test fixture',
  supported_agents: ['mas', 'mag', 'rca', 'oma'],
  default_workspace_precondition: {
    action_id: 'opl_workspace_ensure',
    command: 'opl workspace ensure',
    app_action_id: 'workspace_ensure',
    required_inputs: ['agent_id'],
    optional_inputs: ['workspace_path_or_workspace_root', 'workspace_id', 'project_id', 'mode', 'title', 'dry_run', 'force', 'bind'],
    must_run_before_domain_task_when_no_active_binding: true,
    reuse_active_binding_first: true,
    initialize_missing_workspace: true,
    append_missing_project_in_compatible_series_or_portfolio: true,
    default_entry_for_agents: true,
  },
  explicit_initialization: {
    command: 'opl workspace init',
    app_action_id: 'workspace_initialize',
    role: 'explicit_initialization_or_operator_override',
    default_entry_for_agents: false,
  },
  descriptor_delegates: {
    mcp: {
      tool_name: 'opl_workspace_ensure',
      execution: 'delegate_to_opl_cli',
      delegates_to_action_id: 'opl_workspace_ensure',
      descriptor_only: true,
      public_runtime: false,
    },
    skill: {
      intent: 'ensure_opl_workspace',
      command_contract_id: 'opl_workspace_ensure',
      delegates_to_action_id: 'opl_workspace_ensure',
      descriptor_only: true,
      public_runtime: false,
    },
    openai: {
      tool_name: 'opl_workspace_ensure',
      delegates_to_action_id: 'opl_workspace_ensure',
      descriptor_only: true,
      public_runtime: false,
    },
    ai_sdk: {
      tool_name: 'oplWorkspaceEnsure',
      delegates_to_action_id: 'opl_workspace_ensure',
      descriptor_only: true,
      public_runtime: false,
    },
  },
  topology_contract: {
    contract_ref: 'contracts/opl-framework/workspace-topology-profile.schema.json',
    profile_id: 'opl.workspace_topology_profile.v1',
    topology_model: ['workspace_group', 'project_unit', 'stage_artifact_unit', 'owner_receipt_or_typed_blocker'],
    canonical_project_collection_role: 'project_units',
    canonical_project_unit_semantics: {
      workspace_unit: 'workspace_group',
      project_collection_role: 'project_units',
      project_unit_kind: 'project_unit',
      stage_artifact_unit: 'stage_artifact_unit',
      owner_answer_unit: 'owner_receipt_or_typed_blocker',
      mas_studies_boundary: {
        project_collection_path: 'projects',
        legacy_project_collection_path: 'studies',
        alias_role: 'legacy_display_domain_alias',
        canonical_role: 'project_units',
        canonical_project_unit_kind: 'project_unit',
      },
    },
    project_stage_outputs_root: 'artifacts/stage_outputs',
    stage_output_root_protocol: {
      root: 'artifacts/stage_outputs',
      stage_folder_unit: 'stage_artifact_unit',
      stage_outputs_index_file: 'stage_outputs_index.json',
      current_stage_pointer_file: 'current_stage.json',
      stage_lifecycle_model: ['open', 'active', 'completed', 'blocked', 'superseded', 'archived'],
      required_stage_folder_shape: ['inputs', 'outputs', 'review', 'receipts', 'handoff', 'stage_manifest.json'],
    },
    default_project_collection_path: 'projects',
    legacy_project_collection_aliases: ['deliverables', 'studies'],
    workspace_modes: ['one_off', 'series', 'portfolio'],
    series_capable_one_off_skeleton: true,
  },
  domain_topology_profiles: {
    mas: {
      profile: 'mas_portfolio',
      workspace_mode: 'portfolio',
      project_kind: 'study',
      project_collection_path: 'projects',
      canonical_project_collection_role: 'project_units',
      project_collection_alias_role: 'legacy_display_alias',
      project_collection_display_label: 'studies',
      project_semantic_aliases: ['study', 'studies'],
      legacy_project_collection_aliases: ['studies'],
      user_inspection_roots: ['projects/<project-id>/artifacts/stage_outputs'],
      shared_resource_roots: ['data', 'literature', 'memory', 'shared/sources'],
    },
    mag: {
      profile: 'one_off',
      workspace_mode: 'one_off',
      project_kind: 'grant_project',
      project_collection_path: 'projects',
      canonical_project_collection_role: 'project_units',
      project_collection_alias_role: 'legacy_display_alias',
      project_collection_display_label: 'deliverables',
      project_semantic_aliases: ['grant_project', 'deliverable'],
      legacy_project_collection_aliases: ['deliverables'],
      user_inspection_roots: ['projects/<project-id>/artifacts/stage_outputs'],
      shared_resource_roots: ['shared/sources', 'shared/memory', 'shared/style_system'],
    },
    rca: {
      profile: 'rca_series',
      workspace_mode: 'series',
      project_kind: 'slide_deck',
      project_collection_path: 'projects',
      canonical_project_collection_role: 'project_units',
      project_collection_alias_role: 'legacy_display_alias',
      project_collection_display_label: 'deliverables',
      project_semantic_aliases: ['slide_deck', 'deck', 'deliverable'],
      legacy_project_collection_aliases: ['deliverables'],
      user_inspection_roots: ['projects/<project-id>/artifacts/stage_outputs'],
      shared_resource_roots: ['shared/sources', 'shared/brand', 'shared/visual_memory', 'shared/style_system', 'shared/material_inventory'],
    },
    oma: {
      profile: 'one_off',
      workspace_mode: 'one_off',
      project_kind: 'agent_capability',
      project_collection_path: 'projects',
      canonical_project_collection_role: 'project_units',
      project_collection_alias_role: 'legacy_display_alias',
      project_collection_display_label: 'deliverables',
      project_semantic_aliases: ['agent_capability', 'deliverable'],
      legacy_project_collection_aliases: ['deliverables'],
      user_inspection_roots: ['projects/<project-id>/artifacts/stage_outputs'],
      shared_resource_roots: ['shared/sources', 'shared/memory', 'shared/style_system'],
    },
  },
  user_inspection: {
    ordinary_user_default_surface: 'workspace_local_project_stage_outputs',
    project_stage_outputs_pattern: '<project-root>/artifacts/stage_outputs/<stage-id>/',
    workspace_index_file: 'workspace_index.json',
    workspace_config_file: 'workspace.yaml',
    canonical_generated_root: 'control/opl',
    canonical_projection_root: 'control/opl/projections',
    canonical_report_root: 'control/opl/reports',
    workspace_inspection_file: 'workspace_inspection.json',
    workspace_resource_inventory_file: 'workspace_resource_inventory.json',
    workspace_report_file: 'workspace_report.json',
    stage_outputs_index_file: 'stage_outputs_index.json',
    current_stage_pointer_file: 'current_stage.json',
    canonical_user_inspection_roots: [
      '<project-root>/artifacts/stage_outputs',
      '<project-root>/artifacts/stage_outputs/<stage-id>/inputs',
      '<project-root>/artifacts/stage_outputs/<stage-id>/outputs',
      '<project-root>/artifacts/stage_outputs/<stage-id>/review',
      '<project-root>/artifacts/stage_outputs/<stage-id>/receipts',
      '<project-root>/artifacts/stage_outputs/<stage-id>/handoff',
      '<project-root>/artifacts/stage_outputs/<stage-id>/stage_manifest.json',
    ],
    runtime_state_is_default_user_surface: false,
    product_views_are_stage_outputs: false,
  },
  registry_policy: {
    writes_opl_workspace_registry: true,
    binding_owner: 'one-person-lab',
    domain_repo_can_write_opl_registry: false,
  },
  runtime_state_boundary: {
    role: 'provider_backing_provenance_restore_audit',
    runtime_state_can_be_canonical_project_root: false,
    runtime_state_can_close_stage: false,
    runtime_state_can_replace_owner_receipt_or_typed_blocker: false,
  },
  authority_boundary: {
    opl_can_define_topology_contract: true,
    opl_can_project_workspace_refs: true,
    opl_can_write_domain_truth: false,
    opl_can_write_memory_body: false,
    opl_can_mutate_artifact_body: false,
    opl_can_create_owner_receipt: false,
    opl_can_create_typed_blocker: false,
    opl_can_authorize_quality_or_export: false,
    runtime_state_counts_as_user_default_surface: false,
    conformance_pass_counts_as_domain_ready: false,
  },
  workspace_governance_policy: {
    workspace_norm_projection_must_equal_contract_projection: true,
    profile_binding_required: true,
    profile_version: 'workspace-topology-profile.v2',
    profile_fingerprint: 'opl-workspace-topology-profile-v2-projects-stage-outputs',
    topology_events_required: true,
    canonical_generated_projection_root: 'control/opl/projections',
    root_projection_files_are_compatibility_mirrors: true,
    workspace_report_is_default_user_summary: true,
    generated_projection_currentness_is_repairable_structural_finding: true,
    generated_projection_currentness_blocks_default_execution: false,
  },
  workspace_diagnostic_policy: {
    surface_kind: 'opl_workspace_diagnostic_policy',
    policy_id: 'opl.workspace_diagnostics.contract_light.v1',
    default_execution_blocks_on: 'hard_blockers_only',
    hard_blocker_rule:
      'Only missing/invalid workspace identity, unsafe project shape, authority overclaim, runtime-state overclaim, and closeout-sensitive stage pointer/index shape drift stop default execution.',
    repairable_rule:
      'Generated metadata, profile binding, topology events, shared manifests, directory skeletons, root mirrors, reports, and missing stage projections are repairable through workspace upgrade.',
    advisory_rule: 'Advisory warnings are operator hints only and never block default execution.',
    auto_repair_command_template: 'opl workspace upgrade --workspace <path> --apply',
    repairable_findings_block_default_execution: false,
    advisory_warnings_block_default_execution: false,
    hard_blocker_codes: [
      'workspace_path_required',
      'workspace_root_missing',
      'workspace_root_not_directory',
      'workspace_index_missing',
      'workspace_index_invalid_json',
      'workspace_index_shape_invalid',
      'agent_metadata_missing',
      'workspace_topology_profile_missing',
      'domain_topology_profile_drift',
      'project_collection_missing',
      'indexed_projects_missing',
      'indexed_project_shape_invalid',
      'indexed_project_root_missing',
      'indexed_stage_outputs_index_drift',
      'indexed_current_stage_pointer_drift',
      'authority_boundary_overclaim',
      'runtime_state_boundary_overclaim',
    ],
    repairable_finding_codes: [
      'workspace_config_missing',
      'canonical_topology_missing',
      'canonical_topology_drift',
      'display_labels_missing',
      'display_labels_drift',
      'shared_resources_missing',
      'shared_resources_drift',
      'shared_resource_root_missing',
      'shared_resource_manifest_missing',
      'shared_resource_manifest_drift',
      'generated_refs_missing',
      'workspace_norm_missing',
      'workspace_norm_drift',
      'workspace_norm_projection_drift',
      'profile_binding_missing',
      'profile_binding_drift',
      'topology_events_missing',
      'indexed_project_config_missing',
      'indexed_project_index_missing',
      'indexed_project_index_drift',
      'indexed_inputs_root_missing',
      'indexed_exports_root_missing',
      'indexed_packages_root_missing',
      'indexed_archive_root_missing',
      'indexed_stage_outputs_root_missing',
      'indexed_stage_outputs_manifest_missing',
      'indexed_stage_outputs_manifest_drift',
      'indexed_stage_outputs_index_missing',
      'indexed_current_stage_pointer_missing',
      'indexed_control_root_missing',
      'indexed_review_root_missing',
      'indexed_handoff_root_missing',
      'workspace_map_missing',
      'workspace_map_drift',
      'workspace_health_missing',
      'workspace_health_drift',
      'workspace_inspection_missing',
      'workspace_inspection_drift',
      'workspace_resource_inventory_missing',
      'workspace_resource_inventory_drift',
      'workspace_report_missing',
      'workspace_report_drift',
      'canonical_generated_projection_missing',
      'canonical_generated_projection_drift',
      'interface_projection_missing',
    ],
    advisory_warning_codes: [],
  },
  domain_workspace_lifecycle_policy: {
    policy_ref: 'contracts/opl-framework/workspace-index.schema.json#/$defs/project/lifecycle',
    domain_repo_can_own_generic_workspace_lifecycle: false,
    domain_repo_must_declare_locator_not_lifecycle: true,
    opl_owns_lifecycle_projection: true,
    physical_delete_requires_domain_owner_receipt: true,
  },
  conformance_policy: {
    family_conformance_must_report_workspace_norm: true,
    workspace_norm_maturity_level: 'L4_structural_baseline',
    workspace_norm_pass_is_structural_only: true,
    workspace_norm_pass_can_claim_production_ready: false,
    workspace_norm_pass_can_claim_domain_ready: false,
    workspace_norm_pass_can_claim_artifact_or_quality_ready: false,
    l5_evidence_required: ['long_soak', 'release', 'user_path', 'owner_acceptance'],
    blocked_reasons: [
      'agent_workspace_norm_missing',
      'workspace_norm_projection_drift',
      'workspace_ensure_not_default_precondition',
      'workspace_ensure_descriptor_delegate_drift',
      'workspace_user_inspection_surface_drift',
      'workspace_runtime_state_boundary_drift',
      'workspace_authority_boundary_overclaim',
      'domain_generic_workspace_lifecycle_residue',
    ],
  },
};

const MINIMAL_BRAND_MODULE_IDS = [
  'charter',
  'atlas',
  'workspace',
  'pack',
  'stagecraft',
  'runway',
  'vault',
  'console',
  'foundry-lab',
  'connect',
] as const;

const MINIMAL_BRAND_MODULE_GATES = [
  'brand_doc_ref',
  'registry_entry',
  'contract_or_policy_ref',
  'cli_surface_ref',
  'app_or_operator_surface_ref',
  'descriptor_surface_ref',
  'validation_surface_ref',
  'status_or_maturity_doc_ref',
  'authority_boundary',
  'forbidden_claims',
];

const MINIMAL_BRAND_MODULE_L5_EVIDENCE_CLASSES = [
  'live_user_path',
  'cross_agent_scaleout',
  'long_soak_recovery',
  'release_install_evidence',
  'operator_repair_loop',
  'owner_acceptance',
  'no_second_truth_regression',
] as const;

export const MINIMAL_BRAND_MODULE_REGISTRY_CONTRACT: BrandModuleRegistryContract = {
  version: 'brand-modules.test',
  scope: 'opl_brand_module_registry',
  owner: 'one-person-lab',
  purpose: 'test fixture',
  state: 'test_fixture',
  machine_boundary: 'test fixture',
  baseline_module_id: 'workspace',
  maturity_model: [
    {
      level: 'L4_structural_baseline',
      definition: 'test fixture',
      required_gates: MINIMAL_BRAND_MODULE_GATES,
    },
  ],
  external_reference_principles: ['test fixture'],
  modules: MINIMAL_BRAND_MODULE_IDS.map((moduleId) => ({
    module_id: moduleId,
    brand_name: `OPL ${moduleId}`,
    owner: 'one-person-lab',
    purpose: 'test fixture',
    state: 'test_fixture',
    machine_boundary: 'test fixture',
    module_doc_ref: `human_doc:opl_brand_module_${moduleId.replace(/-/g, '_')}`,
    contract_refs: [
      'contracts/opl-framework/brand-module-surfaces.json',
      'contracts/opl-framework/brand-module-registry.json',
    ],
    cli_surfaces: [
      `opl ${moduleId} status --json`,
      `opl ${moduleId} inspect --json`,
      `opl ${moduleId} interfaces --json`,
      `opl ${moduleId} validate --json`,
      `opl ${moduleId} doctor --json`,
      'opl brand-modules list --json',
    ],
    app_surfaces: [
      `app_action:${moduleId.replace(/-/g, '_')}_status`,
      `app_action:${moduleId.replace(/-/g, '_')}_inspect`,
      'opl brand-modules interfaces --json#app',
    ],
    descriptor_surfaces: [
      `opl ${moduleId} interfaces --json`,
      `contracts/opl-framework/brand-module-surfaces.json#modules.${moduleId}`,
      'opl brand-modules interfaces --json#descriptor',
    ],
    validation_surfaces: [
      `opl ${moduleId} validate --json`,
      `opl ${moduleId} doctor --json`,
      'opl brand-modules validate --json',
    ],
    status_doc_refs: ['human_doc:opl_brand_module_maturity_against_workspace'],
    l4_gates: MINIMAL_BRAND_MODULE_GATES,
    maturity_level: 'L4_structural_baseline',
    authority_boundary: {
      can_claim_domain_ready: false,
      can_claim_quality_verdict: false,
      can_claim_artifact_authority: false,
      can_claim_production_ready: false,
      can_write_domain_truth: false,
      can_write_memory_body: false,
      can_mutate_artifact_body: false,
      can_sign_owner_receipt: false,
      can_create_typed_blocker: false,
      can_replace_domain_owner: false,
      can_replace_ai_executor_planning: false,
    },
    forbidden_claims: ['domain_ready'],
  })),
};

export const MINIMAL_BRAND_MODULE_SURFACES_CONTRACT: BrandModuleSurfacesContract = {
  version: 'brand-module-surfaces.test',
  scope: 'opl_brand_module_executable_surfaces',
  owner: 'one-person-lab',
  purpose: 'test fixture',
  state: 'test_fixture',
  machine_boundary: 'test fixture',
  baseline_module_id: 'workspace',
  required_native_subcommands: ['status', 'inspect', 'interfaces', 'validate', 'doctor'],
  required_gates: [
    'object_model',
    'native_cli_family',
    'app_read_model',
    'descriptor_surface',
    'validation',
    'doctor',
    'status',
    'authority_boundary',
    'forbidden_claims',
  ],
  modules: MINIMAL_BRAND_MODULE_IDS.map((moduleId) => ({
    module_id: moduleId,
    brand_name: `OPL ${moduleId}`,
    command_prefix: moduleId,
    surface_kind_prefix: `opl_${moduleId.replace(/-/g, '_')}`,
    state: 'L4_module_surface_baseline',
    module_doc_ref: `human_doc:opl_brand_module_${moduleId.replace(/-/g, '_')}`,
    object_model: {
      primary_objects: ['test_object'],
      canonical_contract_refs: ['contracts/opl-framework/brand-module-registry.json'],
      read_model_refs: [`opl ${moduleId} status --json`, `opl ${moduleId} inspect --json`],
    },
    native_cli_family: {
      status: `opl ${moduleId} status --json`,
      inspect: `opl ${moduleId} inspect --json`,
      interfaces: `opl ${moduleId} interfaces --json`,
      validate: `opl ${moduleId} validate --json`,
      doctor: `opl ${moduleId} doctor --json`,
      additional_commands: ['opl brand-modules list --json'],
    },
    app_read_model: {
      descriptors: [
        {
          action_id: `${moduleId.replace(/-/g, '_')}_status`,
          command: `opl ${moduleId} status --json`,
          mutation: false,
          descriptor_only: true,
        },
        {
          action_id: `${moduleId.replace(/-/g, '_')}_inspect`,
          command: `opl ${moduleId} inspect --json`,
          mutation: false,
          descriptor_only: true,
        },
        {
          action_id: `${moduleId.replace(/-/g, '_')}_doctor`,
          command: `opl ${moduleId} doctor --json`,
          mutation: false,
          descriptor_only: true,
        },
      ],
      projection_refs: ['opl brand-modules interfaces --json#app'],
    },
    descriptor_surface: {
      delegate_ids: [`${moduleId.replace(/-/g, '_')}_surface_contract`],
      descriptor_refs: [`opl ${moduleId} interfaces --json`],
    },
    validation: {
      commands: [`opl ${moduleId} validate --json`, `opl ${moduleId} doctor --json`],
      checks: ['module_surface_contract'],
      required_refs: [`contracts/opl-framework/brand-module-surfaces.json#modules.${moduleId}`],
    },
    doctor: {
      checks: ['surface_contract_loaded'],
      fail_closed_on: ['missing_surface_contract'],
    },
    status: {
      completion_level: 'L4_structural_baseline',
      evidence_refs: [`opl ${moduleId} validate --json`],
      not_claims: ['domain_ready'],
    },
    authority_boundary: {
      can_claim_domain_ready: false,
      can_claim_quality_verdict: false,
      can_claim_artifact_authority: false,
      can_claim_production_ready: false,
      can_write_domain_truth: false,
      can_write_memory_body: false,
      can_mutate_artifact_body: false,
      can_sign_owner_receipt: false,
      can_create_typed_blocker: false,
      can_replace_domain_owner: false,
      can_replace_ai_executor_planning: false,
    },
    forbidden_claims: ['domain_ready'],
    notes: 'test fixture',
  })),
};

export const MINIMAL_BRAND_MODULE_L5_OPERATING_EVIDENCE_CONTRACT: BrandModuleL5OperatingEvidenceContract = {
  version: 'brand-module-l5-operating-evidence.test',
  scope: 'opl_brand_module_l5_operating_evidence',
  owner: 'one-person-lab',
  purpose: 'test fixture',
  state: 'test_fixture',
  machine_boundary: 'test fixture',
  baseline_level: 'L4_structural_baseline',
  target_level: 'L5_production_operating_maturity',
  l5_claim_policy: {
    all_required_evidence_must_be_satisfied: true,
    docs_foldback_counts_as_l5: false,
    contract_validation_counts_as_l5: false,
    provider_completion_counts_as_l5: false,
    app_projection_counts_as_l5: false,
    conformance_pass_counts_as_l5: false,
  },
  evidence_ledger_surfaces: {
    record_command: 'opl runtime brand-module-l5-evidence record',
    verify_command: 'opl runtime brand-module-l5-evidence verify',
    list_command: 'opl runtime brand-module-l5-evidence list',
    ledger_file_name: 'brand-module-l5-evidence-ledger.json',
    refs_only: true,
    can_claim_l5_complete: false,
    can_create_owner_receipt: false,
    can_create_typed_blocker: false,
  },
  evidence_classes: MINIMAL_BRAND_MODULE_L5_EVIDENCE_CLASSES.map((classId) => ({
    class_id: classId,
    definition: 'test fixture',
    accepted_ref_shapes: ['typed_blocker_ref'],
  })),
  modules: MINIMAL_BRAND_MODULE_IDS.map((moduleId) => ({
    module_id: moduleId,
    brand_name: `OPL ${moduleId}`,
    current_level: 'L4_structural_baseline',
    l5_completion_status: 'evidence_required',
    l5_can_be_claimed: false,
    immediate_enabling_surfaces: [`${moduleId}_l5_fixture_gate`],
    evidence_requirements: MINIMAL_BRAND_MODULE_L5_EVIDENCE_CLASSES.map((classId) => ({
      class_id: classId,
      owner: 'one-person-lab',
      current_state: 'open',
    })),
    not_claims: ['production_ready'],
  })),
};

export const MINIMAL_BRAND_SYSTEM_PROFILE_CONTRACT: BrandSystemProfileContract = {
  version: 'brand-system-profile.test',
  scope: 'opl_brand_system_freeze_profile',
  owner: 'one-person-lab',
  purpose: 'test fixture',
  state: 'test_fixture',
  machine_boundary: 'test fixture',
  source_refs: ['contracts/opl-framework/brand-system-profile.json'],
  product_cognition_layers: [
    {
      layer_id: 'opl_framework',
      product_name: 'OPL Framework',
      user_understanding: 'test fixture',
      maintainer_understanding: 'test fixture',
      owner: 'one-person-lab',
      authority_boundary: ['test fixture'],
    },
    {
      layer_id: 'one_person_lab_app',
      product_name: 'One Person Lab App',
      user_understanding: 'test fixture',
      maintainer_understanding: 'test fixture',
      owner: 'one-person-lab-app',
      authority_boundary: ['test fixture'],
    },
    {
      layer_id: 'foundry_agents',
      product_name: 'Foundry Agents',
      user_understanding: 'test fixture',
      maintainer_understanding: 'test fixture',
      owner: 'domain-agent repositories',
      authority_boundary: ['test fixture'],
    },
  ],
  brand_module_product_grammar: {
    module_ids: [...MINIMAL_BRAND_MODULE_IDS],
    module_role_refs: MINIMAL_BRAND_MODULE_IDS.map((moduleId) => ({
      module_id: moduleId,
      product_grammar_role: 'test fixture',
      registry_ref: `contracts/opl-framework/brand-module-registry.json#modules.${moduleId}`,
      surface_contract_ref: `contracts/opl-framework/brand-module-surfaces.json#modules.${moduleId}`,
    })),
  },
  agent_naming: {
    family_label: 'One Person Lab Foundry Agent',
    public_name_policy: 'test fixture',
    machine_id_policy: 'test fixture',
    required_agent_ids: ['mas', 'mag', 'rca', 'oma'],
    foundry_series_contract_ref: 'contracts/opl-framework/foundry-agent-series-contract.json',
  },
  app_status_language: {
    default_terms: [
      'current owner',
      'next action',
      'artifact',
      'receipt',
      'typed blocker',
      'human gate',
    ],
    diagnostic_only_terms: ['ledger', 'provider'],
    forbidden_default_terms: ['domain ready'],
    default_state_ref: 'contracts/opl-framework/family-product-operator-projection.json',
    full_detail_policy_ref: 'contracts/opl-framework/family-product-operator-projection.json',
  },
  visual_system: {
    pattern_groups: [
      {
        group_id: 'design_tokens',
        purpose: 'test fixture',
        required_patterns: ['semantic_color_tokens'],
      },
      {
        group_id: 'icons',
        purpose: 'test fixture',
        required_patterns: ['module_icon_family'],
      },
      {
        group_id: 'cards',
        purpose: 'test fixture',
        required_patterns: ['agent_card'],
      },
      {
        group_id: 'status_patterns',
        purpose: 'test fixture',
        required_patterns: ['current_owner_status'],
      },
    ],
  },
  receipt_blocker_language: {
    success_shape: 'domain_owner_receipt_ref',
    blocked_shape: 'domain_owned_typed_blocker_ref',
    route_back_shape: 'route_back_or_human_gate_ref',
    owner_answer_schema_ref: 'contracts/opl-framework/owner-answer.schema.json',
    owner_receipt_schema_ref: 'contracts/opl-framework/stage-owner-receipt.schema.json',
    typed_blocker_schema_ref: 'contracts/opl-framework/stage-typed-blocker.schema.json',
    wording_rules: ['test fixture'],
  },
  authority_boundary: {
    can_claim_domain_ready: false,
    can_claim_quality_verdict: false,
    can_claim_artifact_authority: false,
    can_claim_production_ready: false,
    can_write_domain_truth: false,
    can_write_memory_body: false,
    can_mutate_artifact_body: false,
    can_sign_owner_receipt: false,
    can_create_typed_blocker: false,
    can_replace_domain_owner: false,
    can_replace_ai_executor_planning: false,
  },
  forbidden_claims: ['domain_ready'],
};

export const MINIMAL_BRAND_CLI_GOVERNANCE_CONTRACT: BrandCliGovernanceContract = {
  version: 'brand-cli-governance.test',
  scope: 'opl_brand_cli_governance',
  owner: 'one-person-lab',
  purpose: 'test fixture',
  state: 'test_fixture',
  machine_boundary: 'test fixture',
  platform_command_surfaces: MINIMAL_BRAND_MODULE_IDS.map((moduleId) => ({
    module_id: moduleId,
    command: `opl ${moduleId}`,
    operations: moduleId === 'workspace' ? ['status', 'inspect'] : ['status', 'inspect', 'interfaces', 'validate', 'doctor'],
  })),
  agent_internal_modules: {
    canonical_command_surface: 'opl agents modules',
    required_operations: ['list', 'inspect', 'interfaces', 'validate', 'doctor'],
    module_spine: MINIMAL_BRAND_MODULE_IDS.map((moduleId) => ({
      agent_module_id: `agent-${moduleId}`,
      platform_analogue_module_id: moduleId,
      purpose: 'test fixture',
      command_pattern: `opl agents modules inspect --domain <domain_id> --module agent-${moduleId}`,
    })),
    authority_boundary: {
      can_claim_domain_ready: false,
      can_claim_quality_verdict: false,
      can_claim_artifact_authority: false,
      can_claim_production_ready: false,
      can_write_domain_truth: false,
      can_write_memory_body: false,
      can_mutate_artifact_body: false,
      can_sign_owner_receipt: false,
      can_create_typed_blocker: false,
      can_replace_domain_owner: false,
      can_replace_ai_executor_planning: false,
    },
  },
  legacy_command_ownership: [
    {
      command_prefix: 'opl brand-modules',
      primary_module_id: 'charter',
      secondary_module_ids: ['atlas', 'workspace', 'stagecraft', 'runway', 'vault', 'console', 'foundry-lab', 'connect'],
      status: 'test_fixture',
      migration_target: 'test fixture',
      command_refs: ['opl brand-modules list --json'],
      rationale: 'test fixture',
    },
  ],
  drift_guards: ['test fixture'],
};
