import type {
  AgentWorkspaceNormContract,
  BrandCliGovernanceContract,
  BrandModuleL5OperatingEvidenceContract,
  BrandModuleRegistryContract,
  BrandModuleSurfacesContract,
  BrandSystemProfileContract,
} from '../../../../src/types.ts';

export const MINIMAL_AGENT_WORKSPACE_NORM_CONTRACT: AgentWorkspaceNormContract = {
  surface_kind: 'opl_agent_workspace_norm_contract',
  version: 'agent-workspace-norm.v1',
  norm_id: 'opl.agent_workspace_norm.v1',
  owner: 'one-person-lab',
  scope: 'test fixture',
  machine_boundary: 'test fixture',
  supported_agents: ['mas', 'mag', 'rca', 'oma'],
  default_workspace_precondition: {
    action_id: 'opl_workspace_ensure',
    command: 'opl workspace ensure',
    app_action_id: 'workspace_ensure',
    required_inputs: ['agent_id'],
    optional_inputs: ['workspace_path_or_workspace_root', 'workspace_id', 'project_id', 'mode', 'title', 'dry_run', 'force', 'bind'],
    must_run_before_domain_task_when_no_active_binding: true,
    reuse_active_binding_first: true,
    initialize_missing_workspace: true,
    append_missing_project_in_compatible_series_or_portfolio: true,
    default_entry_for_agents: true,
  },
  explicit_initialization: {
    command: 'opl workspace init',
    app_action_id: 'workspace_initialize',
    role: 'explicit_initialization_or_operator_override',
    default_entry_for_agents: false,
  },
  descriptor_delegates: {
    mcp: {
      tool_name: 'opl_workspace_ensure',
      execution: 'delegate_to_opl_cli',
      delegates_to_action_id: 'opl_workspace_ensure',
      descriptor_only: true,
      public_runtime: false,
    },
    skill: {
      intent: 'ensure_opl_workspace',
      command_contract_id: 'opl_workspace_ensure',
      delegates_to_action_id: 'opl_workspace_ensure',
      descriptor_only: true,
      public_runtime: false,
    },
    openai: {
      tool_name: 'opl_workspace_ensure',
      delegates_to_action_id: 'opl_workspace_ensure',
      descriptor_only: true,
      public_runtime: false,
    },
    ai_sdk: {
      tool_name: 'oplWorkspaceEnsure',
      delegates_to_action_id: 'opl_workspace_ensure',
      descriptor_only: true,
      public_runtime: false,
    },
  },
  topology_contract: {
    contract_ref: 'contracts/opl-framework/workspace-topology-profile.schema.json',
    profile_id: 'opl.workspace_topology_profile.v1',
    topology_model: ['workspace_group', 'project_unit', 'stage_artifact_unit', 'owner_receipt_or_typed_blocker'],
    canonical_project_collection_role: 'project_units',
    canonical_project_unit_semantics: {
      workspace_unit: 'workspace_group',
      project_collection_role: 'project_units',
      project_unit_kind: 'project_unit',
      stage_artifact_unit: 'stage_artifact_unit',
      owner_answer_unit: 'owner_receipt_or_typed_blocker',
      mas_studies_boundary: {
        project_collection_path: 'projects',
        legacy_project_collection_path: 'studies',
        alias_role: 'legacy_display_domain_alias',
        canonical_role: 'project_units',
        canonical_project_unit_kind: 'project_unit',
      },
    },
    project_stage_outputs_root: 'artifacts/stage_outputs',
    stage_output_root_protocol: {
      root: 'artifacts/stage_outputs',
      stage_folder_unit: 'stage_artifact_unit',
      stage_outputs_index_file: 'stage_outputs_index.json',
      current_stage_pointer_file: 'current_stage.json',
      stage_lifecycle_model: ['open', 'active', 'completed', 'blocked', 'superseded', 'archived'],
      required_stage_folder_shape: ['inputs', 'outputs', 'review', 'receipts', 'handoff', 'stage_manifest.json'],
    },
    default_project_collection_path: 'projects',
    legacy_project_collection_aliases: ['deliverables', 'studies'],
    workspace_modes: ['one_off', 'series', 'portfolio'],
    series_capable_one_off_skeleton: true,
  },
  domain_topology_profiles: {
    mas: {
      profile: 'mas_portfolio',
      workspace_mode: 'portfolio',
      project_kind: 'study',
      project_collection_path: 'projects',
      canonical_project_collection_role: 'project_units',
      project_collection_alias_role: 'legacy_display_alias',
      project_collection_display_label: 'studies',
      project_semantic_aliases: ['study', 'studies'],
      legacy_project_collection_aliases: ['studies'],
      user_inspection_roots: ['projects/<project-id>/artifacts/stage_outputs'],
      shared_resource_roots: ['data', 'literature', 'memory', 'shared/sources'],
    },
    mag: {
      profile: 'one_off',
      workspace_mode: 'one_off',
      project_kind: 'grant_project',
      project_collection_path: 'projects',
      canonical_project_collection_role: 'project_units',
      project_collection_alias_role: 'legacy_display_alias',
      project_collection_display_label: 'deliverables',
      project_semantic_aliases: ['grant_project', 'deliverable'],
      legacy_project_collection_aliases: ['deliverables'],
      user_inspection_roots: ['projects/<project-id>/artifacts/stage_outputs'],
      shared_resource_roots: ['shared/sources', 'shared/memory', 'shared/style_system'],
    },
    rca: {
      profile: 'rca_series',
      workspace_mode: 'series',
      project_kind: 'slide_deck',
      project_collection_path: 'projects',
      canonical_project_collection_role: 'project_units',
      project_collection_alias_role: 'legacy_display_alias',
      project_collection_display_label: 'deliverables',
      project_semantic_aliases: ['slide_deck', 'deck', 'deliverable'],
      legacy_project_collection_aliases: ['deliverables'],
      user_inspection_roots: ['projects/<project-id>/artifacts/stage_outputs'],
      shared_resource_roots: ['shared/sources', 'shared/brand', 'shared/visual_memory', 'shared/style_system', 'shared/material_inventory'],
    },
    oma: {
      profile: 'one_off',
      workspace_mode: 'one_off',
      project_kind: 'agent_capability',
      project_collection_path: 'projects',
      canonical_project_collection_role: 'project_units',
      project_collection_alias_role: 'legacy_display_alias',
      project_collection_display_label: 'deliverables',
      project_semantic_aliases: ['agent_capability', 'deliverable'],
      legacy_project_collection_aliases: ['deliverables'],
      user_inspection_roots: ['projects/<project-id>/artifacts/stage_outputs'],
      shared_resource_roots: ['shared/sources', 'shared/memory', 'shared/style_system'],
    },
  },
  user_inspection: {
    ordinary_user_default_surface: 'workspace_local_project_stage_outputs',
    project_stage_outputs_pattern: '<project-root>/artifacts/stage_outputs/<stage-id>/',
    workspace_index_file: 'workspace_index.json',
    workspace_config_file: 'workspace.yaml',
    canonical_generated_root: 'control/opl',
    canonical_projection_root: 'control/opl/projections',
    canonical_report_root: 'control/opl/reports',
    workspace_inspection_file: 'workspace_inspection.json',
    workspace_resource_inventory_file: 'workspace_resource_inventory.json',
    workspace_report_file: 'workspace_report.json',
    stage_outputs_index_file: 'stage_outputs_index.json',
    current_stage_pointer_file: 'current_stage.json',
    canonical_user_inspection_roots: [
      '<project-root>/artifacts/stage_outputs',
      '<project-root>/artifacts/stage_outputs/<stage-id>/inputs',
      '<project-root>/artifacts/stage_outputs/<stage-id>/outputs',
      '<project-root>/artifacts/stage_outputs/<stage-id>/review',
      '<project-root>/artifacts/stage_outputs/<stage-id>/receipts',
      '<project-root>/artifacts/stage_outputs/<stage-id>/handoff',
      '<project-root>/artifacts/stage_outputs/<stage-id>/stage_manifest.json',
    ],
    runtime_state_is_default_user_surface: false,
    product_views_are_stage_outputs: false,
  },
  registry_policy: {
    writes_opl_workspace_registry: true,
    binding_owner: 'one-person-lab',
    domain_repo_can_write_opl_registry: false,
  },
  runtime_state_boundary: {
    role: 'provider_backing_provenance_restore_audit',
    runtime_state_can_be_canonical_project_root: false,
    runtime_state_can_close_stage: false,
    runtime_state_can_replace_owner_receipt_or_typed_blocker: false,
  },
  authority_boundary: {
    opl_can_define_topology_contract: true,
    opl_can_project_workspace_refs: true,
    opl_can_write_domain_truth: false,
    opl_can_write_memory_body: false,
    opl_can_mutate_artifact_body: false,
    opl_can_create_owner_receipt: false,
    opl_can_create_typed_blocker: false,
    opl_can_authorize_quality_or_export: false,
    runtime_state_counts_as_user_default_surface: false,
    conformance_pass_counts_as_domain_ready: false,
  },
  workspace_governance_policy: {
    workspace_norm_projection_must_equal_contract_projection: true,
    profile_binding_required: true,
    profile_version: 'workspace-topology-profile.v2',
    profile_fingerprint: 'opl-workspace-topology-profile-v2-projects-stage-outputs',
    topology_events_required: true,
    canonical_generated_projection_root: 'control/opl/projections',
    root_projection_files_are_compatibility_mirrors: true,
    workspace_report_is_default_user_summary: true,
    generated_projection_currentness_is_structural_gate: true,
  },
  domain_workspace_lifecycle_policy: {
    policy_ref: 'contracts/opl-framework/workspace-index.schema.json#/$defs/project/lifecycle',
    domain_repo_can_own_generic_workspace_lifecycle: false,
    domain_repo_must_declare_locator_not_lifecycle: true,
    opl_owns_lifecycle_projection: true,
    physical_delete_requires_domain_owner_receipt: true,
  },
  conformance_policy: {
    family_conformance_must_report_workspace_norm: true,
    workspace_norm_maturity_level: 'L4_structural_baseline',
    workspace_norm_pass_is_structural_only: true,
    workspace_norm_pass_can_claim_production_ready: false,
    workspace_norm_pass_can_claim_domain_ready: false,
    workspace_norm_pass_can_claim_artifact_or_quality_ready: false,
    l5_evidence_required: ['long_soak', 'release', 'user_path', 'owner_acceptance'],
    blocked_reasons: [
      'agent_workspace_norm_missing',
      'workspace_norm_projection_drift',
      'workspace_ensure_not_default_precondition',
      'workspace_ensure_descriptor_delegate_drift',
      'workspace_user_inspection_surface_drift',
      'workspace_runtime_state_boundary_drift',
      'workspace_authority_boundary_overclaim',
      'workspace_profile_binding_drift',
      'workspace_generated_projection_currentness_drift',
      'domain_generic_workspace_lifecycle_residue',
    ],
  },
};

const MINIMAL_BRAND_MODULE_IDS = [
  'charter',
  'atlas',
  'workspace',
  'stagecraft',
  'runway',
  'vault',
  'console',
  'foundry-lab',
  'connect',
] as const;

const MINIMAL_BRAND_MODULE_GATES = [
  'brand_doc_ref',
  'registry_entry',
  'contract_or_policy_ref',
  'cli_surface_ref',
  'app_or_operator_surface_ref',
  'descriptor_surface_ref',
  'validation_surface_ref',
  'status_or_maturity_doc_ref',
  'authority_boundary',
  'forbidden_claims',
];

const MINIMAL_BRAND_MODULE_L5_EVIDENCE_CLASSES = [
  'live_user_path',
  'cross_agent_scaleout',
  'long_soak_recovery',
  'release_install_evidence',
  'operator_repair_loop',
  'owner_acceptance',
  'no_second_truth_regression',
] as const;

export const MINIMAL_BRAND_MODULE_REGISTRY_CONTRACT: BrandModuleRegistryContract = {
  version: 'brand-modules.test',
  scope: 'opl_brand_module_registry',
  owner: 'one-person-lab',
  purpose: 'test fixture',
  state: 'test_fixture',
  machine_boundary: 'test fixture',
  baseline_module_id: 'workspace',
  maturity_model: [
    {
      level: 'L4_structural_baseline',
      definition: 'test fixture',
      required_gates: MINIMAL_BRAND_MODULE_GATES,
    },
  ],
  external_reference_principles: ['test fixture'],
  modules: MINIMAL_BRAND_MODULE_IDS.map((moduleId) => ({
    module_id: moduleId,
    brand_name: `OPL ${moduleId}`,
    owner: 'one-person-lab',
    purpose: 'test fixture',
    state: 'test_fixture',
    machine_boundary: 'test fixture',
    module_doc_ref: `human_doc:opl_brand_module_${moduleId.replace(/-/g, '_')}`,
    contract_refs: [
      'contracts/opl-framework/brand-module-surfaces.json',
      'contracts/opl-framework/brand-module-registry.json',
    ],
    cli_surfaces: [
      `opl ${moduleId} status --json`,
      `opl ${moduleId} inspect --json`,
      `opl ${moduleId} interfaces --json`,
      `opl ${moduleId} validate --json`,
      `opl ${moduleId} doctor --json`,
      'opl brand-modules list --json',
    ],
    app_surfaces: [
      `app_action:${moduleId.replace(/-/g, '_')}_status`,
      `app_action:${moduleId.replace(/-/g, '_')}_inspect`,
      'opl brand-modules interfaces --json#app',
    ],
    descriptor_surfaces: [
      `opl ${moduleId} interfaces --json`,
      `contracts/opl-framework/brand-module-surfaces.json#modules.${moduleId}`,
      'opl brand-modules interfaces --json#descriptor',
    ],
    validation_surfaces: [
      `opl ${moduleId} validate --json`,
      `opl ${moduleId} doctor --json`,
      'opl brand-modules validate --json',
    ],
    status_doc_refs: ['human_doc:opl_brand_module_maturity_against_workspace'],
    l4_gates: MINIMAL_BRAND_MODULE_GATES,
    maturity_level: 'L4_structural_baseline',
    authority_boundary: {
      can_claim_domain_ready: false,
      can_claim_quality_verdict: false,
      can_claim_artifact_authority: false,
      can_claim_production_ready: false,
      can_write_domain_truth: false,
      can_write_memory_body: false,
      can_mutate_artifact_body: false,
      can_sign_owner_receipt: false,
      can_create_typed_blocker: false,
      can_replace_domain_owner: false,
      can_replace_ai_executor_planning: false,
    },
    forbidden_claims: ['domain_ready'],
  })),
};

export const MINIMAL_BRAND_MODULE_SURFACES_CONTRACT: BrandModuleSurfacesContract = {
  version: 'brand-module-surfaces.test',
  scope: 'opl_brand_module_executable_surfaces',
  owner: 'one-person-lab',
  purpose: 'test fixture',
  state: 'test_fixture',
  machine_boundary: 'test fixture',
  baseline_module_id: 'workspace',
  required_native_subcommands: ['status', 'inspect', 'interfaces', 'validate', 'doctor'],
  required_gates: [
    'object_model',
    'native_cli_family',
    'app_read_model',
    'descriptor_surface',
    'validation',
    'doctor',
    'status',
    'authority_boundary',
    'forbidden_claims',
  ],
  modules: MINIMAL_BRAND_MODULE_IDS.map((moduleId) => ({
    module_id: moduleId,
    brand_name: `OPL ${moduleId}`,
    command_prefix: moduleId,
    surface_kind_prefix: `opl_${moduleId.replace(/-/g, '_')}`,
    state: 'L4_module_surface_baseline',
    module_doc_ref: `human_doc:opl_brand_module_${moduleId.replace(/-/g, '_')}`,
    object_model: {
      primary_objects: ['test_object'],
      canonical_contract_refs: ['contracts/opl-framework/brand-module-registry.json'],
      read_model_refs: [`opl ${moduleId} status --json`, `opl ${moduleId} inspect --json`],
    },
    native_cli_family: {
      status: `opl ${moduleId} status --json`,
      inspect: `opl ${moduleId} inspect --json`,
      interfaces: `opl ${moduleId} interfaces --json`,
      validate: `opl ${moduleId} validate --json`,
      doctor: `opl ${moduleId} doctor --json`,
      additional_commands: ['opl brand-modules list --json'],
    },
    app_read_model: {
      descriptors: [
        {
          action_id: `${moduleId.replace(/-/g, '_')}_status`,
          command: `opl ${moduleId} status --json`,
          mutation: false,
          descriptor_only: true,
        },
        {
          action_id: `${moduleId.replace(/-/g, '_')}_inspect`,
          command: `opl ${moduleId} inspect --json`,
          mutation: false,
          descriptor_only: true,
        },
        {
          action_id: `${moduleId.replace(/-/g, '_')}_doctor`,
          command: `opl ${moduleId} doctor --json`,
          mutation: false,
          descriptor_only: true,
        },
      ],
      projection_refs: ['opl brand-modules interfaces --json#app'],
    },
    descriptor_surface: {
      delegate_ids: [`${moduleId.replace(/-/g, '_')}_surface_contract`],
      descriptor_refs: [`opl ${moduleId} interfaces --json`],
    },
    validation: {
      commands: [`opl ${moduleId} validate --json`, `opl ${moduleId} doctor --json`],
      checks: ['module_surface_contract'],
      required_refs: [`contracts/opl-framework/brand-module-surfaces.json#modules.${moduleId}`],
    },
    doctor: {
      checks: ['surface_contract_loaded'],
      fail_closed_on: ['missing_surface_contract'],
    },
    status: {
      completion_level: 'L4_structural_baseline',
      evidence_refs: [`opl ${moduleId} validate --json`],
      not_claims: ['domain_ready'],
    },
    authority_boundary: {
      can_claim_domain_ready: false,
      can_claim_quality_verdict: false,
      can_claim_artifact_authority: false,
      can_claim_production_ready: false,
      can_write_domain_truth: false,
      can_write_memory_body: false,
      can_mutate_artifact_body: false,
      can_sign_owner_receipt: false,
      can_create_typed_blocker: false,
      can_replace_domain_owner: false,
      can_replace_ai_executor_planning: false,
    },
    forbidden_claims: ['domain_ready'],
    notes: 'test fixture',
  })),
};

export const MINIMAL_BRAND_MODULE_L5_OPERATING_EVIDENCE_CONTRACT: BrandModuleL5OperatingEvidenceContract = {
  version: 'brand-module-l5-operating-evidence.test',
  scope: 'opl_brand_module_l5_operating_evidence',
  owner: 'one-person-lab',
  purpose: 'test fixture',
  state: 'test_fixture',
  machine_boundary: 'test fixture',
  baseline_level: 'L4_structural_baseline',
  target_level: 'L5_production_operating_maturity',
  l5_claim_policy: {
    all_required_evidence_must_be_satisfied: true,
    docs_foldback_counts_as_l5: false,
    contract_validation_counts_as_l5: false,
    provider_completion_counts_as_l5: false,
    app_projection_counts_as_l5: false,
    conformance_pass_counts_as_l5: false,
  },
  evidence_ledger_surfaces: {
    record_command: 'opl runtime brand-module-l5-evidence record',
    verify_command: 'opl runtime brand-module-l5-evidence verify',
    list_command: 'opl runtime brand-module-l5-evidence list',
    ledger_file_name: 'brand-module-l5-evidence-ledger.json',
    refs_only: true,
    can_claim_l5_complete: false,
    can_create_owner_receipt: false,
    can_create_typed_blocker: false,
  },
  evidence_classes: MINIMAL_BRAND_MODULE_L5_EVIDENCE_CLASSES.map((classId) => ({
    class_id: classId,
    definition: 'test fixture',
    accepted_ref_shapes: ['typed_blocker_ref'],
  })),
  modules: MINIMAL_BRAND_MODULE_IDS.map((moduleId) => ({
    module_id: moduleId,
    brand_name: `OPL ${moduleId}`,
    current_level: 'L4_structural_baseline',
    l5_completion_status: 'evidence_required',
    l5_can_be_claimed: false,
    immediate_enabling_surfaces: [`${moduleId}_l5_fixture_gate`],
    evidence_requirements: MINIMAL_BRAND_MODULE_L5_EVIDENCE_CLASSES.map((classId) => ({
      class_id: classId,
      owner: 'one-person-lab',
      current_state: 'open',
    })),
    not_claims: ['production_ready'],
  })),
};

export const MINIMAL_BRAND_SYSTEM_PROFILE_CONTRACT: BrandSystemProfileContract = {
  version: 'brand-system-profile.test',
  scope: 'opl_brand_system_freeze_profile',
  owner: 'one-person-lab',
  purpose: 'test fixture',
  state: 'test_fixture',
  machine_boundary: 'test fixture',
  source_refs: ['contracts/opl-framework/brand-system-profile.json'],
  product_cognition_layers: [
    {
      layer_id: 'opl_framework',
      product_name: 'OPL Framework',
      user_understanding: 'test fixture',
      maintainer_understanding: 'test fixture',
      owner: 'one-person-lab',
      authority_boundary: ['test fixture'],
    },
    {
      layer_id: 'one_person_lab_app',
      product_name: 'One Person Lab App',
      user_understanding: 'test fixture',
      maintainer_understanding: 'test fixture',
      owner: 'one-person-lab-app',
      authority_boundary: ['test fixture'],
    },
    {
      layer_id: 'foundry_agents',
      product_name: 'Foundry Agents',
      user_understanding: 'test fixture',
      maintainer_understanding: 'test fixture',
      owner: 'domain-agent repositories',
      authority_boundary: ['test fixture'],
    },
  ],
  brand_module_product_grammar: {
    module_ids: [...MINIMAL_BRAND_MODULE_IDS],
    module_role_refs: MINIMAL_BRAND_MODULE_IDS.map((moduleId) => ({
      module_id: moduleId,
      product_grammar_role: 'test fixture',
      registry_ref: `contracts/opl-framework/brand-module-registry.json#modules.${moduleId}`,
      surface_contract_ref: `contracts/opl-framework/brand-module-surfaces.json#modules.${moduleId}`,
    })),
  },
  agent_naming: {
    family_label: 'One Person Lab Foundry Agent',
    public_name_policy: 'test fixture',
    machine_id_policy: 'test fixture',
    required_agent_ids: ['mas', 'mag', 'rca', 'oma'],
    foundry_series_contract_ref: 'contracts/opl-framework/foundry-agent-series-contract.json',
  },
  app_status_language: {
    default_terms: [
      'current owner',
      'next action',
      'artifact',
      'receipt',
      'typed blocker',
      'human gate',
    ],
    diagnostic_only_terms: ['ledger', 'provider'],
    forbidden_default_terms: ['domain ready'],
    default_state_ref: 'contracts/opl-framework/family-product-operator-projection.json',
    full_detail_policy_ref: 'contracts/opl-framework/family-product-operator-projection.json',
  },
  visual_system: {
    pattern_groups: [
      {
        group_id: 'design_tokens',
        purpose: 'test fixture',
        required_patterns: ['semantic_color_tokens'],
      },
      {
        group_id: 'icons',
        purpose: 'test fixture',
        required_patterns: ['module_icon_family'],
      },
      {
        group_id: 'cards',
        purpose: 'test fixture',
        required_patterns: ['agent_card'],
      },
      {
        group_id: 'status_patterns',
        purpose: 'test fixture',
        required_patterns: ['current_owner_status'],
      },
    ],
  },
  receipt_blocker_language: {
    success_shape: 'domain_owner_receipt_ref',
    blocked_shape: 'domain_owned_typed_blocker_ref',
    route_back_shape: 'route_back_or_human_gate_ref',
    owner_answer_schema_ref: 'contracts/opl-framework/owner-answer.schema.json',
    owner_receipt_schema_ref: 'contracts/opl-framework/stage-owner-receipt.schema.json',
    typed_blocker_schema_ref: 'contracts/opl-framework/stage-typed-blocker.schema.json',
    wording_rules: ['test fixture'],
  },
  authority_boundary: {
    can_claim_domain_ready: false,
    can_claim_quality_verdict: false,
    can_claim_artifact_authority: false,
    can_claim_production_ready: false,
    can_write_domain_truth: false,
    can_write_memory_body: false,
    can_mutate_artifact_body: false,
    can_sign_owner_receipt: false,
    can_create_typed_blocker: false,
    can_replace_domain_owner: false,
    can_replace_ai_executor_planning: false,
  },
  forbidden_claims: ['domain_ready'],
};

export const MINIMAL_BRAND_CLI_GOVERNANCE_CONTRACT: BrandCliGovernanceContract = {
  version: 'brand-cli-governance.test',
  scope: 'opl_brand_cli_governance',
  owner: 'one-person-lab',
  purpose: 'test fixture',
  state: 'test_fixture',
  machine_boundary: 'test fixture',
  platform_frontdoors: MINIMAL_BRAND_MODULE_IDS.map((moduleId) => ({
    module_id: moduleId,
    command: `opl ${moduleId}`,
    operations: moduleId === 'workspace' ? ['status', 'inspect'] : ['status', 'inspect', 'interfaces', 'validate', 'doctor'],
  })),
  agent_internal_modules: {
    canonical_frontdoor: 'opl agents modules',
    required_operations: ['list', 'inspect', 'interfaces', 'validate', 'doctor'],
    module_spine: MINIMAL_BRAND_MODULE_IDS.map((moduleId) => ({
      agent_module_id: `agent-${moduleId}`,
      platform_analogue_module_id: moduleId,
      purpose: 'test fixture',
      command_pattern: `opl agents modules inspect --domain <domain_id> --module agent-${moduleId}`,
    })),
    authority_boundary: {
      can_claim_domain_ready: false,
      can_claim_quality_verdict: false,
      can_claim_artifact_authority: false,
      can_claim_production_ready: false,
      can_write_domain_truth: false,
      can_write_memory_body: false,
      can_mutate_artifact_body: false,
      can_sign_owner_receipt: false,
      can_create_typed_blocker: false,
      can_replace_domain_owner: false,
      can_replace_ai_executor_planning: false,
    },
  },
  legacy_command_ownership: [
    {
      command_prefix: 'opl brand-modules',
      primary_module_id: 'charter',
      secondary_module_ids: ['atlas', 'workspace', 'stagecraft', 'runway', 'vault', 'console', 'foundry-lab', 'connect'],
      status: 'test_fixture',
      migration_target: 'test fixture',
      command_refs: ['opl brand-modules list --json'],
      rationale: 'test fixture',
    },
  ],
  drift_guards: ['test fixture'],
};
