import { assert, runCli, test } from '../helpers.ts';

test('framework tranche backlog exposes standard agent and runtime primitive guards', () => {
  const readback = runCli(['framework', 'tranche-backlog', '--family-defaults']).framework_tranche_backlog;

  assert.equal(
    readback.standard_agent_landing_acceptance_guard.surface_kind,
    'opl_standard_agent_landing_acceptance_guard_readback',
  );
  assert.equal(
    readback.standard_agent_landing_acceptance_guard.status,
    'closed_structure_gate_not_live_evidence',
  );
  assert.equal(
    readback.standard_agent_landing_acceptance_guard.acceptance_summary.current_completion_status,
    'family_evidence_tail_open_not_complete',
  );
  assert.equal(
    readback.standard_agent_landing_acceptance_guard.acceptance_summary.completion_claim_authorized,
    false,
  );
  assert.equal(
    readback.standard_agent_landing_acceptance_guard.acceptance_summary.gate_status_counts.total,
    7,
  );
  assert.equal(
    readback.standard_agent_landing_acceptance_guard.acceptance_summary.gate_status_counts.can_claim_complete,
    0,
  );
  assert.ok(
    readback.standard_agent_landing_acceptance_guard.acceptance_summary.open_evidence_tail_ids.includes(
      'generated_surface_production_consumption',
    ),
  );
  assert.equal(
    readback.standard_agent_landing_acceptance_guard.private_residue_owner_decision_summary.ledger_state,
    'refs_only_owner_decision_ledger',
  );
  assert.equal(
    readback.standard_agent_landing_acceptance_guard.private_residue_owner_decision_summary.physical_delete_authorized,
    false,
  );
  assert.equal(
    readback.standard_agent_landing_acceptance_guard.private_residue_owner_decision_summary
      .invalid_owner_decision_count,
    0,
  );
  assert.equal(
    readback.standard_agent_landing_acceptance_guard.private_residue_owner_decision_summary
      .physical_delete_authorized_count,
    0,
  );
  assert.equal(
    readback.standard_agent_landing_acceptance_guard.negative_conformance_summary
      .can_claim_standard_agent_complete_count,
    0,
  );
  assert.equal(
    readback.standard_agent_landing_acceptance_guard.structural_closeout_guard
      .can_close_non_live_structure_gate,
    true,
  );
  assert.ok(
    readback.standard_agent_landing_acceptance_guard.structural_closeout_guard.cannot_claim.includes(
      'standard_agent_complete',
    ),
  );
  assert.ok(
    readback.standard_agent_landing_acceptance_guard.structural_closeout_guard.cannot_claim.includes(
      'physical_delete_authorized',
    ),
  );
  assert.equal(
    readback.standard_agent_landing_acceptance_guard.no_second_truth_guard
      .evidence_status_can_create_second_active_backlog,
    false,
  );
  assert.equal(
    readback.standard_agent_landing_acceptance_guard.authority_boundary
      .private_residue_decision_ledger_can_authorize_physical_delete,
    false,
  );
  assert.equal(
    readback.standard_agent_landing_acceptance_guard.false_ready_guard
      .acceptance_definition_landed_can_claim_standard_agent_complete,
    false,
  );
  assert.equal(
    readback.standard_agent_landing_acceptance_guard.false_ready_guard
      .residue_decision_ledger_can_authorize_physical_delete,
    false,
  );
  assert.equal(
    readback.domain_progress_transition_runtime_guard.surface_kind,
    'opl_domain_progress_transition_runtime_guard_readback',
  );
  assert.equal(
    readback.domain_progress_transition_runtime_guard.contract_identity.surface_kind,
    'opl_domain_progress_transition_runtime_first_slice',
  );
  assert.equal(
    readback.domain_progress_transition_runtime_guard.runtime_identity.runtime_id,
    'opl_domain_progress_transition_runtime',
  );
  assert.equal(
    readback.domain_progress_transition_runtime_guard.runtime_identity.runtime_owner,
    'one-person-lab',
  );
  assert.equal(
    readback.domain_progress_transition_runtime_guard.runtime_identity.not_a_new_brand_module,
    true,
  );
  assert.equal(
    readback.domain_progress_transition_runtime_guard
      .physical_persistence_refs.runtime_live_readback_api,
    'readDomainProgressTransitionRuntimeReadbackJsonl',
  );
  assert.equal(
    readback.domain_progress_transition_runtime_guard
      .physical_persistence_refs.live_readback_contract.complete_transaction_status,
    'complete_transaction',
  );
  assert.equal(
    readback.domain_progress_transition_runtime_guard
      .physical_persistence_refs.live_readback_contract.incomplete_transaction_outcome_kind,
    'blocked_incomplete_transaction',
  );
  assert.equal(
    readback.domain_progress_transition_runtime_guard
      .physical_persistence_refs.live_readback_contract
      .projection_metadata_consumable_only_when_transaction_complete,
    true,
  );
  assert.deepEqual(
    readback.domain_progress_transition_runtime_guard.allowed_transition_decisions,
    [
      'execute_current_owner_delta',
      'consume_terminal_closeout',
      'materialize_recovery_action',
      'wait_for_owner_with_resume_token',
      'stop_with_stable_typed_blocker',
      'stop_with_owner_receipt',
    ],
  );
  assert.equal(
    readback.domain_progress_transition_runtime_guard.decision_surface_policy.read_model_can_execute,
    false,
  );
  assert.equal(
    readback.domain_progress_transition_runtime_guard.policy_adapter_contract
      .source_export_matches_stage_route_scheduler_contract,
    true,
  );
  assert.equal(
    readback.domain_progress_transition_runtime_guard.policy_adapter_contract
      .normalized_request_surface,
    'mas_domain_progress_transition_request',
  );
  assert.ok(
    readback.domain_progress_transition_runtime_guard.policy_adapter_contract
      .fail_closed_reasons.includes('domain_progress_policy_adapter_authority_overclaim'),
  );
  assert.ok(
    readback.domain_progress_transition_runtime_guard.policy_adapter_contract
      .forbidden_domain_adapter_outputs.includes('typed_blocker'),
  );
  assert.equal(
    readback.domain_progress_transition_runtime_guard
      .authority_boundary.runtime_can_write_domain_truth,
    false,
  );
  assert.equal(
    readback.domain_progress_transition_runtime_guard
      .authority_boundary.runtime_can_sign_owner_receipt,
    false,
  );
  assert.equal(
    readback.domain_progress_transition_runtime_guard
      .authority_boundary.runtime_can_create_typed_blocker,
    false,
  );
  assert.equal(
    readback.domain_progress_transition_runtime_guard
      .authority_boundary.policy_adapter_can_create_owner_receipt,
    false,
  );
  assert.equal(
    readback.domain_progress_transition_runtime_guard
      .false_ready_guard.complete_transaction_can_claim_domain_ready,
    false,
  );
  assert.equal(
    readback.domain_progress_transition_runtime_guard
      .false_ready_guard.read_model_projection_consumable_can_claim_domain_progress,
    false,
  );
  assert.equal(
    readback.domain_progress_transition_runtime_guard
      .false_ready_guard.non_advancing_apply_can_claim_paper_progress,
    false,
  );
  assert.equal(
    readback.memory_artifact_lifecycle_boundary_guard.surface_kind,
    'opl_memory_artifact_lifecycle_boundary_guard_readback',
  );
  assert.equal(
    readback.memory_artifact_lifecycle_boundary_guard.target_surface,
    'memory_artifact_lifecycle',
  );
  assert.equal(
    readback.memory_artifact_lifecycle_boundary_guard.status,
    'closed_structure_gate_not_live_evidence',
  );
  assert.equal(
    readback.memory_artifact_lifecycle_boundary_guard.structural_closeout_guard
      .can_close_non_live_structure_gate,
    true,
  );
  assert.equal(
    readback.memory_artifact_lifecycle_boundary_guard.evidence_intake_policy.refs_only,
    true,
  );
  assert.deepEqual(
    readback.memory_artifact_lifecycle_boundary_guard.accepted_refs_only_result_shapes,
    [
      'memory_receipt_ref',
      'memory_writeback_receipt_ref',
      'artifact_mutation_receipt_ref',
      'package_lifecycle_receipt_ref',
      'export_lifecycle_receipt_ref',
      'cleanup_restore_retention_receipt_ref',
      'typed_blocker_ref',
      'owner_acceptance_ref',
    ],
  );
  assert.ok(
    readback.memory_artifact_lifecycle_boundary_guard.source_cli_readback_refs.includes(
      'opl runtime memory-artifact-lifecycle-evidence record|verify|list --json',
    ),
  );
  assert.ok(
    readback.memory_artifact_lifecycle_boundary_guard.source_api_readback_refs.includes(
      'buildMemoryArtifactLifecycleReadback',
    ),
  );
  assert.equal(
    readback.memory_artifact_lifecycle_boundary_guard.authority_boundary.can_write_memory_body,
    false,
  );
  assert.equal(
    readback.memory_artifact_lifecycle_boundary_guard.authority_boundary.can_mutate_artifact_body,
    false,
  );
  assert.equal(
    readback.memory_artifact_lifecycle_boundary_guard.authority_boundary.can_create_owner_receipt,
    false,
  );
  assert.equal(
    readback.memory_artifact_lifecycle_boundary_guard.authority_boundary.can_create_typed_blocker,
    false,
  );
  assert.equal(
    readback.memory_artifact_lifecycle_boundary_guard.authority_boundary.can_authorize_export_readiness,
    false,
  );
  assert.equal(
    readback.memory_artifact_lifecycle_boundary_guard.false_ready_guard
      .verified_refs_only_ledger_can_claim_memory_ready,
    false,
  );
  assert.equal(
    readback.memory_artifact_lifecycle_boundary_guard.false_ready_guard
      .verified_refs_only_ledger_can_claim_artifact_ready,
    false,
  );
  assert.equal(
    readback.memory_artifact_lifecycle_boundary_guard.false_ready_guard
      .verified_refs_only_ledger_can_claim_package_ready,
    false,
  );
  assert.equal(
    readback.memory_artifact_lifecycle_boundary_guard.false_ready_guard
      .owner_acceptance_ref_can_claim_domain_ready,
    false,
  );
  assert.equal(
    readback.memory_artifact_lifecycle_boundary_guard.false_ready_guard
      .review_repair_transport_passed_can_claim_repair_accepted,
    false,
  );
  assert.ok(
    readback.memory_artifact_lifecycle_boundary_guard.structural_closeout_guard.cannot_claim.includes(
      'artifact_body_mutated',
    ),
  );
  assert.ok(
    readback.memory_artifact_lifecycle_boundary_guard.structural_closeout_guard.cannot_claim.includes(
      'owner_receipt_signed',
    ),
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.surface_kind,
    'opl_runtime_environment_substrate_guard_readback',
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.readback_role,
    'runtime_environment_substrate_owner_policy_not_domain_ready_not_live_evidence_not_app_release_ready',
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.contract_identity.contract_id,
    'opl_runtime_environment_substrate_contract',
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.contract_identity.implementation_status,
    'runtime_lock_materializer_cache_prune_run_context_guard_available',
  );
  assert.deepEqual(
    readback.runtime_environment_substrate_guard.ordinary_path.steps,
    [
      'runtime_environment_descriptor',
      'runtime_lock',
      'content_addressed_layers',
      'runtime_bundle_manifest',
      'materialized_runtime_root',
      'receipt_cleanup_rollback',
    ],
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.ordinary_path.domain_agents_declare_dependency_intent_only,
    true,
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.materialization_policy.writes_development_checkout,
    false,
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.materialization_policy.writes_runtime_root_only_with_apply,
    true,
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.cache_policy.cache_hit_counts_as_ready,
    false,
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.cache_inventory_policy.deletes_domain_artifacts,
    false,
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.dependency_prepare_policy.writes_domain_truth,
    false,
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.dependency_prepare_policy
      .run_context_consumer_preflight,
    'fail_closed_on_missing_run_context_or_target_mismatch',
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.dependency_prepare_policy
      .host_environment_fallback_allowed,
    false,
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.run_context_consumer_policy.status,
    'fail_closed_consumer_preflight_available',
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.run_context_consumer_policy
      .run_context_exists_counts_as_provider_ready,
    false,
  );
  assert.ok(
    readback.runtime_environment_substrate_guard.readback_commands.includes(
      'opl runtime env verify --runtime-root <path>',
    ),
  );
  assert.ok(
    readback.runtime_environment_substrate_guard.required_readback_claim_fields.includes(
      'can_claim_runtime_ready',
    ),
  );
  assert.ok(
    readback.runtime_environment_substrate_guard.forbidden_claims.includes(
      'runtime_environment_receipt_means_domain_ready',
    ),
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.authority_boundary.can_write_domain_truth,
    false,
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.authority_boundary.can_sign_owner_receipt,
    false,
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.authority_boundary.can_create_typed_blocker,
    false,
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.authority_boundary.can_schedule_domain_stage,
    false,
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.false_ready_guard.materialization_receipt_can_claim_domain_ready,
    false,
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.false_ready_guard.verification_receipt_can_claim_app_release_ready,
    false,
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.false_ready_guard.runtime_environment_readback_can_create_typed_blocker,
    false,
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.false_ready_guard
      .missing_run_context_allows_host_environment_fallback,
    false,
  );
  assert.equal(
    readback.runtime_environment_substrate_guard.false_ready_guard
      .run_context_target_mismatch_allows_consumer_execution,
    false,
  );
  assert.equal(
    readback.ordinary_progress_guard.surface_kind,
    'opl_ordinary_progress_owner_route_guard_readback',
  );
  assert.equal(
    readback.ordinary_progress_guard.ordinary_route_policy.default_planning_root,
    'current_owner_delta',
  );
  assert.equal(
    readback.ordinary_progress_guard.owner_answer_admission_gate.surface_kind,
    'opl_owner_answer_admission_gate_readback',
  );
  assert.equal(
    readback.ordinary_progress_guard.owner_answer_admission_gate.source_schema.surface_kind,
    'opl_owner_answer',
  );
  assert.equal(
    readback.ordinary_progress_guard.owner_answer_admission_gate.source_schema.schema_version,
    'owner-answer.v1',
  );
  assert.equal(
    readback.ordinary_progress_guard.owner_answer_admission_gate
      .source_schema.owner_answer_required_fields_present,
    true,
  );
  assert.deepEqual(
    readback.ordinary_progress_guard.owner_answer_admission_gate.accepted_answer_kinds,
    [
      'owner_receipt',
      'typed_blocker',
      'human_decision',
      'route_back',
    ],
  );
  assert.equal(
    readback.ordinary_progress_guard.owner_answer_admission_gate
      .default_next_action_source_priority[0],
    'fresh_current_owner_delta',
  );
  assert.ok(
    readback.ordinary_progress_guard.owner_answer_admission_gate.rejected_default_roots.includes(
      'provider_trace',
    ),
  );
  assert.equal(
    readback.ordinary_progress_guard.owner_answer_admission_gate
      .authority_boundary.opl_can_sign_domain_owner_answer,
    false,
  );
  assert.equal(
    readback.ordinary_progress_guard.owner_answer_admission_gate
      .authority_boundary.opl_can_create_typed_blocker,
    false,
  );
  assert.equal(
    readback.ordinary_progress_guard.owner_answer_admission_gate
      .false_ready_guard.owner_answer_shape_valid_can_claim_domain_ready,
    false,
  );
  assert.equal(
    readback.ordinary_progress_guard.owner_route_schema.surface_kind,
    'family_owner_route',
  );
  assert.equal(
    readback.ordinary_progress_guard.owner_route_schema.version,
    'family-owner-route.v1',
  );
  assert.equal(
    readback.ordinary_progress_guard.owner_route_schema.owner_route_required_fields_present,
    true,
  );
  assert.equal(
    readback.ordinary_progress_guard.typed_blocker_schema.surface_kind,
    'opl_stage_typed_blocker',
  );
  assert.equal(
    readback.ordinary_progress_guard.typed_blocker_schema.schema_version,
    'stage-typed-blocker.v1',
  );
  assert.equal(
    readback.ordinary_progress_guard.typed_blocker_schema.typed_blocker_required_fields_present,
    true,
  );
  assert.equal(
    readback.ordinary_progress_guard.human_gate_boundary.opl_can_make_human_decision,
    false,
  );
  assert.equal(
    readback.ordinary_progress_guard.human_gate_boundary.source_schema.version,
    'family-human-gate.v1',
  );
  assert.equal(
    readback.ordinary_progress_guard.human_gate_boundary.source_schema
      .human_gate_required_fields_present,
    true,
  );
  assert.ok(
    readback.ordinary_progress_guard.human_gate_boundary.source_schema.required_fields.includes(
      'decision_options',
    ),
  );
  assert.equal(
    readback.ordinary_progress_guard.authority_boundary.evidence_worklist_can_override_current_owner_delta,
    false,
  );
  assert.equal(
    readback.ordinary_progress_guard.false_ready_guard.typed_blocker_ref_can_claim_stage_success,
    false,
  );
  assert.equal(
    readback.primitive_runtime_owner_route_guard.surface_kind,
    'opl_primitive_runtime_owner_route_guard_readback',
  );
  assert.equal(
    readback.primitive_runtime_owner_route_guard.status,
    'closed_structure_gate_not_live_evidence',
  );
  assert.equal(
    readback.primitive_runtime_owner_route_guard.structural_closeout_guard.can_close_non_live_structure_gate,
    true,
  );
  assert.equal(
    readback.primitive_runtime_owner_route_guard.runtime_environment_summary
      .host_environment_fallback_allowed,
    false,
  );
  assert.equal(
    readback.primitive_runtime_owner_route_guard.domain_progress_runtime_summary
      .policy_adapter_matches_contract,
    true,
  );
  assert.equal(
    readback.primitive_runtime_owner_route_guard.ordinary_route_summary.typed_blocker_schema_ready,
    true,
  );
  assert.equal(
    readback.primitive_runtime_owner_route_guard.ordinary_route_summary.human_gate_schema_ready,
    true,
  );
  assert.equal(
    readback.primitive_runtime_owner_route_guard.authority_boundary
      .primitive_guard_can_create_typed_blocker,
    false,
  );
  assert.equal(
    readback.primitive_runtime_owner_route_guard.authority_boundary
      .primitive_guard_can_make_human_decision,
    false,
  );
  assert.equal(
    readback.primitive_runtime_owner_route_guard.false_ready_guard
      .runtime_environment_guard_closed_can_claim_runtime_ready,
    false,
  );
  assert.equal(
    readback.primitive_runtime_owner_route_guard.false_ready_guard
      .no_second_truth_guard_ready_can_claim_full_goal_complete,
    false,
  );
  assert.ok(
    readback.primitive_runtime_owner_route_guard.structural_closeout_guard.cannot_claim.includes(
      'provider_long_soak_complete',
    ),
  );
});
