import './workspace-domain.registry.test.ts';
import './workspace-domain.launch.test.ts';
import './workspace-domain.actions.test.ts';
import './workspace-domain.stages.test.ts';
import './workspace-domain.agent-skeleton.test.ts';
import './workspace-domain.stages.real-smoke.test.ts';
import './workspace-domain.memory.test.ts';
import './workspace-domain.lifecycle-cleanup.test.ts';
import './workspace-domain.external-evidence.test.ts';
