export const STANDARD_STAGE_COMPLETION_POLICY = {
  surface_kind: 'domain_stage_completion_policy',
  version: 'domain-stage-completion-policy.v1',
  owner: 'one-person-lab',
  standard_agent_requirement:
    'codex_cli_routes_any_readable_artifact_to_any_declared_stage_quality_closeout_is_optional_for_progress',
  completion_judgment_owner: 'domain_stage',
  closeout_packet_required: false,
  closeout_packet_required_for_quality_acceptance: true,
  raw_artifact_sufficient_for_progress: true,
  provider_completion_is_domain_completion: false,
  opl_content_judgment_allowed: false,
  next_stage_transition_owner: 'codex_cli',
  framework_route_role: 'declared_stage_transport_and_passive_projection_only',
  required_closeout_outcomes: [
    'completed_and_continue',
    'completed_with_quality_debt',
    'completed_and_wait_owner',
    'route_back',
    'blocked',
    'rejected',
  ],
  accepted_closeout_ref_fields: [
    'progress_delta_receipt_ref',
    'consumable_artifact_ref',
    'quality_debt_ref',
    'owner_receipt_ref',
    'typed_blocker_ref',
    'human_gate_ref',
    'route_back_ref',
    'negative_result_ref',
    'no_output_or_failure_diagnostic_ref',
  ],
  quality_budget_exhaustion_blocks_route: false,
  owner_receipt_required_for_quality_or_ready_claims: true,
  zero_consumable_artifact_becomes_progress_diagnostic: true,
  corrupt_or_unreadable_artifact_becomes_progress_diagnostic: true,
  authority_boundary: {
    opl_can_decide_domain_completion: false,
    provider_completion_counts_as_stage_complete: false,
    readable_file_counts_as_stage_progress: true,
    framework_can_accept_reject_or_override_codex_route: false,
    suite_pass_counts_as_stage_complete: false,
    conformance_pass_counts_as_stage_complete: false,
    validated_consumable_artifact_progress_counts_as_stage_transition: true,
    quality_debt_counts_as_quality_acceptance: false,
  },
} as const;
