import {
  memoryArtifactLifecycleEvidenceAuthorityBoundary,
} from '../../ledger/index.ts';
import {
  MEMORY_ARTIFACT_LIFECYCLE_REF_SHAPES,
  NO_SECOND_TRUTH_AUTHORITY_BOUNDARY,
} from './shared.ts';

export function buildMemoryArtifactLifecycleBoundaryGuardReadback() {
  const evidenceAuthority = memoryArtifactLifecycleEvidenceAuthorityBoundary();
  const structuralChecks = [
    evidenceAuthority.refs_only === true,
    evidenceAuthority.can_write_domain_truth === false,
    evidenceAuthority.can_write_memory_body === false,
    evidenceAuthority.can_read_memory_body === false,
    evidenceAuthority.can_mutate_artifact_body === false,
    evidenceAuthority.can_authorize_package_readiness === false,
    evidenceAuthority.can_authorize_export_readiness === false,
    evidenceAuthority.can_create_owner_receipt === false,
    evidenceAuthority.can_generate_typed_blocker === false,
    MEMORY_ARTIFACT_LIFECYCLE_REF_SHAPES.includes('memory_receipt_ref'),
    MEMORY_ARTIFACT_LIFECYCLE_REF_SHAPES.includes('artifact_mutation_receipt_ref'),
    MEMORY_ARTIFACT_LIFECYCLE_REF_SHAPES.includes('typed_blocker_ref'),
    MEMORY_ARTIFACT_LIFECYCLE_REF_SHAPES.includes('owner_acceptance_ref'),
  ];
  return {
    surface_kind: 'opl_memory_artifact_lifecycle_boundary_guard_readback',
    readback_role:
      'memory_artifact_lifecycle_refs_only_boundary_not_memory_ready_not_artifact_ready_not_package_export_ready',
    owner: 'one-person-lab',
    target_surface: 'memory_artifact_lifecycle',
    milestone_id: 'memory_artifact_lifecycle_functional_boundary',
    status: structuralChecks.every(Boolean)
      ? 'closed_structure_gate_not_live_evidence'
      : 'blocked_structure_gate',
    source_refs: [
      'src/memory-artifact-lifecycle-evidence-ledger.ts',
      'src/memory-artifact-lifecycle-readback.ts',
      'src/runtime-tray-app-operator-drilldown-parts/memory-artifact-lifecycle-evidence.ts',
      'src/cli/cases/runtime-memory-artifact-lifecycle-evidence-command-spec.ts',
    ],
    source_api_readback_refs: [
      'memoryArtifactLifecycleEvidenceAuthorityBoundary',
      'buildMemoryArtifactLifecycleEvidenceProjection',
      'buildMemoryArtifactLifecycleReadback',
      'buildMemoryArtifactLifecycleEvidence',
      'recordMemoryArtifactLifecycleEvidenceReceipts',
      'verifyMemoryArtifactLifecycleEvidenceReceipt',
      'listMemoryArtifactLifecycleEvidenceReceipts',
    ],
    source_cli_readback_refs: [
      'opl runtime memory-artifact-lifecycle-evidence record|verify|list --json',
      'opl runtime memory-artifact-lifecycle --json .memory_artifact_lifecycle_readback',
      'opl runtime app-operator-drilldown --json .app_operator_drilldown.memory_artifact_lifecycle',
      'opl framework operating-maturity --family-defaults --json .framework_operating_maturity.memory_artifact_lifecycle',
      'opl framework tranche-backlog --family-defaults --json .framework_tranche_backlog.memory_artifact_lifecycle_boundary_guard',
    ],
    evidence_intake_policy: {
      refs_only: true,
      ledger_surface_kind: 'opl_memory_artifact_lifecycle_evidence_ledger',
      receipt_surface_kind: 'opl_memory_artifact_lifecycle_evidence_receipt',
      record_command_writes_opl_state_ledger_only: true,
      verify_command_marks_refs_only_receipt_only: true,
      record_or_verify_command_can_write_memory_body: false,
      record_or_verify_command_can_mutate_artifact_body: false,
      record_or_verify_command_can_create_owner_receipt: false,
      record_or_verify_command_can_create_typed_blocker: false,
      accepted_refs_only_result_shapes: [...MEMORY_ARTIFACT_LIFECYCLE_REF_SHAPES],
    },
    projection_policy: {
      readback_surface_kind: 'opl_memory_artifact_lifecycle_readback',
      app_drilldown_surface_kind: 'opl_app_drilldown_memory_artifact_lifecycle_evidence',
      projection_source:
        'runtime_app_operator_drilldown_plus_refs_only_evidence_projection',
      owner_work_order_surface_kind: 'opl_memory_artifact_lifecycle_owner_work_order',
      owner_work_order_lane_id: 'memory_artifact_lifecycle_apply',
      next_required_owner_action:
        'domain_owner_record_memory_artifact_lifecycle_receipt_or_typed_blocker',
      open_count_zero_authorizes_ready_claim: false,
      verified_refs_only_ledger_authorizes_ready_claim: false,
      typed_blocker_ref_without_owner_followthrough_closes_lane: false,
      owner_acceptance_ref_without_owner_native_receipt_closes_domain_ready: false,
    },
    workspace_transport_policy: {
      workspace_artifact_lifecycle_transport_ref:
        'opl workspace artifact-lifecycle --workspace <path> --project-id <id> --apply',
      source_handoff_ref: 'handoff/review-repair-transport.json',
      materialized_opl_projection_ref:
        'control/opl/artifact_lifecycle/review_repair_transport.json',
      transport_is_opaque_ref_projection: true,
      transport_can_parse_repair_semantics: false,
      transport_can_claim_repair_accepted: false,
      transport_can_authorize_physical_delete: false,
    },
    accepted_refs_only_result_shapes: [...MEMORY_ARTIFACT_LIFECYCLE_REF_SHAPES],
    structural_closeout_guard: {
      can_close_non_live_structure_gate: structuralChecks.every(Boolean),
      required_current_truth_surfaces: [
        'memory_artifact_lifecycle_evidence_ledger',
        'memory_artifact_lifecycle_readback',
        'app_operator_drilldown_memory_artifact_lifecycle',
        'framework_operating_maturity_memory_artifact_lifecycle',
        'workspace_artifact_lifecycle_review_repair_transport',
        'framework_tranche_backlog_memory_artifact_lifecycle_boundary_guard',
      ],
      cannot_claim: [
        'memory_body_saved_or_accepted',
        'memory_writeback_accepted_or_rejected',
        'artifact_body_mutated',
        'artifact_ready',
        'repair_accepted',
        'package_ready',
        'export_ready',
        'domain_ready',
        'App_release_ready',
        'production_ready',
        'provider_long_soak_complete',
        'owner_receipt_signed',
        'typed_blocker_created',
        'human_decision_made',
        'physical_delete_authorized',
        'full_goal_complete',
      ],
    },
    non_closing_inputs: [
      'app_projection',
      'verified_refs_only_ledger',
      'lifecycle_reconcile_zero_issue_count',
      'open_count_zero',
      'opl_cleanup_apply_available',
      'typed_blocker_ref_without_owner_followthrough',
      'owner_acceptance_ref_without_owner_native_receipt',
      'review_repair_transport_passed',
    ],
    forbidden_opl_claims: [
      'memory_body_saved_or_accepted',
      'memory_writeback_accepted_or_rejected',
      'artifact_body_mutated',
      'artifact_ready',
      'repair_accepted',
      'package_ready',
      'export_ready',
      'domain_ready',
      'production_ready',
      'domain_physical_delete_authorization',
    ],
    authority_boundary: {
      ...evidenceAuthority,
      ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY,
      can_project_refs: true,
      can_record_refs_only_evidence: true,
      can_verify_refs_only_evidence_receipt: true,
      can_emit_owner_work_order_projection: true,
      can_write_memory_body: false,
      can_read_memory_body: false,
      can_accept_or_reject_memory_writeback: false,
      can_read_artifact_body: false,
      can_mutate_artifact_body: false,
      can_parse_review_repair_semantics: false,
      can_authorize_repair_acceptance: false,
      can_authorize_package_readiness: false,
      can_authorize_export_readiness: false,
      can_execute_domain_physical_delete: false,
      can_create_owner_receipt: false,
      can_create_typed_blocker: false,
      can_claim_memory_ready: false,
      can_claim_artifact_ready: false,
      can_claim_package_ready: false,
      can_claim_export_ready: false,
      can_claim_domain_ready: false,
      can_claim_production_ready: false,
    },
    false_ready_guard: {
      refs_observed_can_claim_memory_ready: false,
      refs_observed_can_claim_artifact_ready: false,
      lifecycle_reconcile_clean_can_claim_ready: false,
      open_count_zero_can_claim_memory_ready: false,
      verified_refs_only_ledger_can_claim_memory_ready: false,
      verified_refs_only_ledger_can_claim_artifact_ready: false,
      verified_refs_only_ledger_can_claim_package_ready: false,
      verified_refs_only_ledger_can_claim_export_ready: false,
      typed_blocker_ref_can_claim_lane_closed: false,
      owner_acceptance_ref_can_claim_domain_ready: false,
      review_repair_transport_passed_can_claim_repair_accepted: false,
      opl_cleanup_apply_can_authorize_physical_delete: false,
      tranche_guard_can_claim_live_evidence_complete: false,
    },
  };
}
