import type {
  FrameworkTrancheMilestone,
  TrancheExecutionLane,
} from './shared.ts';
import {
  DEFERRED_LIVE_EVIDENCE,
  NON_LIVE_ACCEPTANCE,
  NO_SECOND_TRUTH_AUTHORITY_BOUNDARY,
} from './shared.ts';

export const APP_SHELL_CONVERGENCE_STRUCTURE_READBACK = {
  status: 'closed_structure_gate_not_live_evidence',
  source_repo: 'gaofeng21cn/one-person-lab-app',
  absorbed_origin_main_sha: '9cb0196c06d1203a33d9aad20b9299eac6f36a0e',
  readback_command: 'npm run validate:shell-convergence',
  surface_kind: 'opl_app_shell_convergence_readback',
  mainline_shell: 'AionUI/opl-aion-shell',
  foreground_alternative: 'Hermes Desktop/hermes-codex',
  archived_technical_proof_only: 'AGUI/agui-codex',
  default_candidate_validation_scope: ['hermes-codex'],
  archived_technical_proofs: ['agui-codex'],
  false_ready_boundary: {
    active_shell_switch_allowed_by_this_readback: false,
    can_claim_active_shell_adopted: false,
    can_claim_app_release_ready: false,
    can_claim_production_ready: false,
    can_claim_live_user_path: false,
    can_claim_live_evidence: false,
    can_claim_packaged_gui_acceptance: false,
  },
  source_refs: [
    'one-person-lab-app:contracts/app-shell-adapter.json',
    'one-person-lab-app:contracts/app-shell-candidates.json',
    'one-person-lab-app:contracts/shell-adapters/hermes-codex.json',
    'one-person-lab-app:scripts/validate-shell-convergence.ts',
    'one-person-lab-app:tests/release/app-release-boundary-cases/shell-adapter-and-gui-contracts.ts',
    'one-person-lab-app:docs/status.md',
    'one-person-lab-app:docs/active/app-ideal-state-gap-plan.md',
  ],
  hermes_candidate_functional_convergence_readback: {
    status: 'closed_structure_gate_not_live_evidence',
    source_repo: 'gaofeng21cn/opl-hermes-shell',
    absorbed_origin_main_sha: 'bd139d5e1bcb57e47defbd59f411032e0b240a60',
    readback_command: 'npm run validate:candidate',
    surface_kind: 'opl_hermes_candidate_functional_convergence_readback',
    state: 'technical_verification_candidate_not_active_shell',
    adapter_scope_ref: 'electron/opl-codex-gateway.cjs#describeOplCodexGatewayScope',
    candidate_profile_ref: 'contracts/opl-hermes-candidate-profile.json#functional_convergence_readback',
    false_ready_boundary: {
      can_claim_active_shell_adopted: false,
      can_claim_app_release_ready: false,
      can_claim_production_ready: false,
      can_claim_live_user_path: false,
      can_claim_packaged_gui_acceptance: false,
      can_claim_owner_receipt: false,
      can_claim_typed_blocker: false,
      can_claim_domain_truth: false,
    },
  },
  hermes_candidate_operator_functional_surface_readback: {
    status: 'closed_structure_gate_not_live_evidence',
    source_repo: 'gaofeng21cn/opl-hermes-shell',
    absorbed_origin_main_sha: 'bd139d5e1bcb57e47defbd59f411032e0b240a60',
    readback_command: 'npm run validate:candidate',
    surface_kind: 'opl_hermes_candidate_operator_functional_surface_readback',
    state: 'ordinary_operator_candidate_surface_available_not_active_shell',
    candidate_profile_ref:
      'contracts/opl-hermes-candidate-profile.json#operator_functional_surface_readback',
    gateway_scope_ref: 'electron/opl-codex-gateway.cjs#describeOplCodexGatewayScope',
    operator_surface_ids: [
      'domain_skill_catalog',
      'ordinary_session_prompt_path',
      'operator_settings_and_model_access',
      'composer_affordances',
    ],
    codex_skill_ids: ['mas', 'mag', 'rca', 'opl'],
    false_ready_boundary: {
      can_claim_active_shell_adopted: false,
      can_claim_app_release_ready: false,
      can_claim_production_ready: false,
      can_claim_live_user_path: false,
      can_claim_packaged_gui_acceptance: false,
      can_claim_owner_receipt: false,
      can_claim_typed_blocker: false,
      can_claim_domain_truth: false,
      can_claim_domain_route_authority: false,
      can_claim_app_operator_sustained_consumption: false,
    },
  },
};

export const CROSS_REPO_REF_INTEGRITY_GUARD = {
  surface_kind: 'opl_family_cross_repo_ref_integrity_guard',
  status: 'closed_structure_gate_not_live_evidence',
  owner: 'one-person-lab',
  guard_role:
    'tranche_backlog_cross_repo_refs_are_canonical_or_explicitly_forbidden_legacy_refs_not_runtime_truth',
  checked_repo_refs: [
    {
      repo: 'opl-doc',
      canonical_ref: 'contracts/support-repo-policy.json',
      consumed_by_milestone_id: 'support_repo_profile_no_resurrection',
      stale_or_forbidden_refs: [
        'contracts/support_repo_policy.json',
      ],
      source_readback_ref:
        'opl-doc:scripts/opl_doc_doctor.py native-check . --format json#support_profile_guard',
      support_profile_strict_readback_ref:
        'opl-doc:scripts/opl_doc_doctor.py support-profile-check . --format json',
      absorbed_origin_main_commit: '95b3cfaa4d35aa5791919d20052cb1c2d8d54841',
      integrity_state: 'canonical_ref_consumed_legacy_alias_forbidden',
    },
  ],
  no_second_truth_guard: {
    cross_repo_ref_guard_can_replace_repo_truth: false,
    cross_repo_ref_guard_can_create_missing_contract_alias: false,
    cross_repo_ref_guard_can_claim_support_repo_ready: false,
    cross_repo_ref_guard_can_claim_foundry_agent_truth_set_membership: false,
    cross_repo_ref_guard_can_claim_live_evidence_complete: false,
  },
  false_ready_guard: {
    canonical_ref_exists_can_claim_repo_ready: false,
    ref_integrity_pass_can_claim_plan_completion: false,
    support_profile_guard_can_claim_production_ready: false,
  },
};

export const MAS_CONFORMANCE_RESIDUE_CLOSEOUT_READBACK = {
  surface_kind: 'opl_family_mas_conformance_residue_closeout_readback',
  status: 'closed_structure_gate_not_live_evidence',
  owner: 'one-person-lab',
  guard_role:
    'mas_progress_portal_legacy_private_control_owner_delta_residue_is_suppressed_and_family_conformance_unblocked_without_domain_readiness_authority',
  source_repo: 'gaofeng21cn/med-autoscience',
  source_lane_id: 'mas-progress-portal-owner-delta-residue-20260622',
  source_closeout_origin_main_sha: '092ce099b2e196e08998f5ef5725c13d5896d217',
  latest_observed_origin_main_sha: 'b3d03a810b5f371b0887030fd8d5d9d1dc716b2c',
  source_closeout_is_ancestor_of_latest_observed_origin_main: true,
  source_readback_command:
    './bin/opl agents conformance --family-defaults --json',
  family_conformance_readback: {
    structural_conformance_status: 'passed',
    structural_contract_status: 'passed',
    ordinary_path_guard_status: 'passed',
    blocked_count: 0,
    passed_count: 5,
    residual_subreadback_scope:
      'foundry_agent_os_membership_uses_five_standard_members_not_mas_private_control_owner_delta_residue',
  },
  closed_residue_boundary: {
    source_marker_authority_ref:
      'med-autoscience:contracts/runtime/legacy-active-path-tombstones.json#/legacy_control_receipt_exclusion_policy/legacy_markers',
    progress_portal_summary_status:
      'suppressed_legacy_private_control_owner',
    active_fixture_owner:
      'one-person-lab',
    legacy_marker_literal_resurrection_allowed: false,
    progress_portal_can_report_legacy_private_control_owner_as_active_operator: false,
  },
  source_refs: [
    'med-autoscience:src/med_autoscience/controllers/progress_portal_parts/owner_delta_summary.py',
    'med-autoscience:contracts/runtime/legacy-active-path-tombstones.json',
    'med-autoscience:tests/test_progress_portal.py',
    'med-autoscience:tests/test_adapter_retirement_boundary.py',
    'med-autoscience:tests/test_study_runtime_execution_evidence_adoption_cases/test_standard_agent_purity_boundary.py',
    'med-autoscience:docs/runtime/display/progress_portal.md',
  ],
  non_live_evidence: [
    'MAS_progress_portal_legacy_private_control_owner_delta_suppression_landed',
    'MAS_progress_portal_fixture_owner_uses_ordinary_owner_route',
    'MAS_no_resurrection_regression_avoids_active_legacy_marker_literal',
    'MAS_progress_portal_and_standard_agent_purity_focused_tests_passed',
    'OPL_agents_conformance_family_defaults_structural_passed_blocked_count_zero_after_MAS_remote_readback',
  ],
  deferred_evidence: [
    'MAS_owner_chain_live_evidence',
    'MAS_provider_long_soak',
    'MAS_real_paper_project_run_evidence',
    ...DEFERRED_LIVE_EVIDENCE,
  ],
  authority_boundary: {
    ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY,
    can_write_mas_runtime_truth: false,
    can_sign_mas_owner_receipt: false,
    can_create_mas_typed_blocker: false,
    can_claim_mas_domain_ready: false,
    can_claim_mas_paper_ready: false,
    can_claim_foundry_agent_os_complete: false,
  },
  false_ready_guard: {
    conformance_pass_can_claim_mas_domain_ready: false,
    conformance_pass_can_claim_mas_paper_ready: false,
    progress_portal_suppression_can_claim_live_evidence_complete: false,
    remote_sha_readback_can_claim_foundry_agent_os_complete: false,
    blocked_count_zero_can_claim_plan_completion: false,
  },
};

export const FOUNDRY_STANDARD_AGENT_MEMBERSHIP_READBACK = {
  surface_kind: 'opl_foundry_standard_agent_membership_readback',
  status: 'closed_structure_gate_not_live_evidence',
  owner: 'one-person-lab',
  guard_role:
    'foundry_agent_standard_membership_is_not_split_by_generated_surface_opl_hosted_command_route_or_plugin_transport',
  cli_readback_command: './bin/opl agents conformance --family-defaults --json',
  standard_member_agent_ids: ['mas', 'mag', 'rca', 'oma', 'opl-bookforge'],
  public_projection_policy: {
    standard_membership_value: 'standard_domain_agent',
    generated_surface_or_hosted_route_is_membership_axis: false,
    generated_surface_or_hosted_route_is_status_axis: false,
    plugin_transport_source_kind_is_membership_axis: false,
    plugin_transport_source_kind_is_status_axis: false,
    list_and_inspect_must_match_current_public_field_allowlist: true,
    connect_skills_must_project_source_kind_as_transport_only: true,
  },
  readback_fields: [
    '.standard_domain_agent_conformance.foundry_agent_os_conformance.applies_to_domain_agents',
    '.standard_domain_agent_conformance.foundry_agent_os_conformance.observed_domain_agent_ids',
    '.standard_domain_agent_conformance.foundry_agent_os_conformance.standard_membership_policy',
    '.foundry_agents.agents[].series_membership',
    '.skill_catalog.packs[].agent_series_membership',
    '.skill_catalog.packs[].plugin_transport.source_kind_role',
  ],
  non_live_evidence: [
    'OPL_agents_conformance_classifies_BookForge_as_standard_domain_agent',
    'OPL_foundry_agent_os_observed_standard_agent_ids_include_five_standard_agents',
    'OPL_foundry_agent_list_and_inspect_match_current_public_field_allowlist',
    'OPL_connect_skills_source_kind_is_transport_detail_not_agent_membership',
    'OPL_foundry_agent_os_unknown_non_standard_agent_still_blocks',
    'OPL_agents_conformance_family_defaults_foundry_os_unblocked_without_any_domain_ready_claim',
  ],
  deferred_evidence: [
    'BookForge_domain_owner_acceptance',
    'BookForge_real_book_project_run_evidence',
    'generated_surface_production_consumption_owner_evidence',
    ...DEFERRED_LIVE_EVIDENCE,
  ],
  authority_boundary: {
    ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY,
    can_write_bookforge_domain_truth: false,
    can_claim_bookforge_domain_ready: false,
    can_claim_bookforge_production_ready: false,
    can_claim_foundry_agent_os_complete: false,
  },
  false_ready_guard: {
    standard_membership_can_claim_domain_ready: false,
    standard_membership_can_claim_production_ready: false,
    standard_membership_can_claim_full_goal_complete: false,
    generated_surface_or_hosted_route_can_claim_domain_ready: false,
  },
};

export const CURRENT_TRANCHE_LANES: TrancheExecutionLane[] = [
  {
    lane_id: 'opl-tranche-backlog-foldback-20260622c',
    repo: 'one-person-lab',
    priority: 'P0',
    milestone_ids: [
      'opl_primitive_runtime_owner_route_guard',
      'standard_agent_landing_acceptance_guard',
      'strict_source_purity_private_wrapper_retirement',
    ],
    lane_status:
      'closed_structure_gate_current_tranche_machine_foldback_non_live_evidence',
    write_set_class: 'opl_framework_tranche_backlog_current_selection_and_closeout_foldback',
    required_surfaces: [
      'source',
      'CLI_readback',
      'API_readback',
      'docs',
      'tests',
    ],
    non_live_completion_evidence_required: [
      'OPL_framework_tranche_backlog_current_tranche_reflects_MAG_RCA_OPL_tranche',
      'OPL_framework_tranche_backlog_remote_readbacks_reflect_MAG_and_RCA_origin_main_sha',
      'OPL_framework_tranche_backlog_keeps_previous_closed_tranche_archive_separate_from_current_work_order',
      'OPL_focused_tranche_backlog_tests_and_smoke_passed',
      'OPL_main_absorbed_push_and_remote_sha_readback_ff7a1b66ece98aaf7bcb17797caa321e88f90df7',
    ],
    deferred_evidence: DEFERRED_LIVE_EVIDENCE,
    forbidden_scope: [
      'MAS_MAG_RCA_OMA_domain_truth_write',
      'App_AionUI_or_Hermes_source_write',
      'AGUI_update_or_foreground_resurrection',
      'owner_receipt_signature',
      'typed_blocker_instance_creation',
      'physical_delete_authorization',
      'runtime_ready_claim',
      'domain_ready_claim',
      'App_release_ready_claim',
      'production_ready_claim',
      'Live_Evidence_claim',
      'full_Plan_Completion_Audit_claim',
    ],
  },
  {
    lane_id: 'mag-repo-shell-wrapper-source-purity-guard-20260622c',
    repo: 'med-autogrant',
    priority: 'P1',
    milestone_ids: ['strict_source_purity_private_wrapper_retirement'],
    lane_status:
      'absorbed_remote_repo_shell_wrapper_source_purity_guard_non_live_evidence',
    write_set_class: 'mag_repo_shell_wrapper_source_purity_guard',
    required_surfaces: [
      'source',
      'contract',
      'CLI_readback',
      'API_readback',
      'docs',
      'tests',
    ],
    non_live_completion_evidence_required: [
      'MAG_repo_shell_verification_wrapper_guard_landed_in_source_purity_readback',
      'MAG_authority_source_purity_CLI_and_package_API_expose_same_guard',
      'MAG_unclassified_or_stale_top_level_scripts_fail_closed',
      'MAG_meta_verify_passed',
      'MAG_main_absorbed_push_and_remote_sha_readback_7d35de2d2084054b014b3e9e1952845633c3369e',
    ],
    deferred_evidence: DEFERRED_LIVE_EVIDENCE,
    forbidden_scope: [
      'grant_truth_write',
      'owner_receipt_signature',
      'typed_blocker_instance_creation',
      'physical_delete_authorization',
      'default_caller_cutover_claim',
      'repo_shell_wrapper_physical_delete_claim',
      'grant_ready_claim',
      'submission_ready_claim',
      'domain_ready_claim',
      'production_ready_claim',
      'Live_Evidence_claim',
      'full_Plan_Completion_Audit_claim',
    ],
  },
  {
    lane_id: 'rca-active-source-resurrection-scan-20260622c',
    repo: 'redcube-ai',
    priority: 'P1',
    milestone_ids: ['strict_source_purity_private_wrapper_retirement'],
    lane_status:
      'absorbed_remote_active_source_resurrection_strict_readback_non_live_evidence',
    write_set_class: 'rca_private_platform_active_source_resurrection_scan_guard',
    required_surfaces: [
      'source',
      'contract',
      'CLI_readback',
      'API_readback',
      'docs',
      'tests',
    ],
    non_live_completion_evidence_required: [
      'RCA_active_source_resurrection_scan_landed_in_private_platform_readback',
      'RCA_private_platform_strict_and_default_caller_tail_strict_readbacks_include_guard',
      'RCA_guard_blocks_false_ready_true_claim_keys_in_active_source',
      'RCA_smoke_and_private_platform_strict_tests_passed',
      'RCA_main_absorbed_push_and_remote_sha_readback_328e1969e65e4b816483d12f4ea5a0554ca9389b',
    ],
    deferred_evidence: DEFERRED_LIVE_EVIDENCE,
    forbidden_scope: [
      'visual_truth_write',
      'artifact_blob_write',
      'memory_body_write',
      'review_or_export_verdict',
      'owner_receipt_signature',
      'typed_blocker_instance_creation',
      'physical_delete_authorization',
      'default_caller_cutover_claim',
      'visual_ready_or_exportable_claim',
      'domain_ready_claim',
      'production_ready_claim',
      'Live_Evidence_claim',
      'full_Plan_Completion_Audit_claim',
    ],
  },
];

export const NEXT_TRANCHE_SELECTED_LANES: TrancheExecutionLane[] = [
  {
    lane_id: 'opl-tranche-backlog-foldback-20260622d',
    repo: 'one-person-lab',
    priority: 'P0',
    milestone_ids: [
      'strict_source_purity_private_wrapper_retirement',
      'support_repo_profile_no_resurrection',
    ],
    lane_status:
      'closed_archive_tranche_backlog_machine_foldback_non_live_provenance',
    write_set_class: 'opl_framework_tranche_backlog_current_selection_and_closeout_foldback',
    required_surfaces: [
      'source',
      'CLI_readback',
      'API_readback',
      'docs',
      'tests',
    ],
    non_live_completion_evidence_required: [
      'OPL_framework_tranche_backlog_current_tranche_reflects_RCA_OPL_DOC_OPL_tranche',
      'OPL_framework_tranche_backlog_remote_readbacks_reflect_RCA_and_OPL_DOC_origin_main_sha',
      'OPL_framework_tranche_backlog_keeps_20260622c_closed_tranche_archive_separate_from_current_work_order',
      'OPL_focused_tranche_backlog_tests_and_smoke_passed',
      'OPL_main_absorbed_push_and_remote_sha_readback',
    ],
    deferred_evidence: DEFERRED_LIVE_EVIDENCE,
    forbidden_scope: [
      'MAS_MAG_RCA_OMA_domain_truth_write',
      'App_AionUI_or_Hermes_source_write',
      'AGUI_update_or_foreground_resurrection',
      'owner_receipt_signature',
      'typed_blocker_instance_creation',
      'physical_delete_authorization',
      'runtime_ready_claim',
      'domain_ready_claim',
      'App_release_ready_claim',
      'production_ready_claim',
      'Live_Evidence_claim',
      'full_Plan_Completion_Audit_claim',
    ],
  },
  {
    lane_id: 'rca-private-platform-json-readback-20260622d',
    repo: 'redcube-ai',
    priority: 'P1',
    milestone_ids: ['strict_source_purity_private_wrapper_retirement'],
    lane_status:
      'absorbed_remote_private_platform_json_transport_guard_non_live_evidence',
    write_set_class: 'rca_private_platform_json_readback_transport_guard',
    required_surfaces: [
      'source',
      'contract',
      'CLI_readback',
      'API_readback',
      'docs',
      'tests',
    ],
    non_live_completion_evidence_required: [
      'RCA_private_platform_readback_stdout_flush_before_exit_landed',
      'RCA_private_platform_direct_JSON_readback_over_64KB_is_parseable',
      'RCA_private_platform_strict_gate_payload_equals_direct_readback_payload',
      'RCA_source_morphology_policy_json_transport_guard_landed',
      'RCA_main_absorbed_push_and_remote_sha_readback_0726ef03f158a0c90484edc53536f17cfe59a42f',
    ],
    deferred_evidence: DEFERRED_LIVE_EVIDENCE,
    forbidden_scope: [
      'visual_truth_write',
      'artifact_blob_write',
      'memory_body_write',
      'review_or_export_verdict',
      'owner_receipt_signature',
      'typed_blocker_instance_creation',
      'physical_delete_authorization',
      'default_caller_cutover_claim',
      'visual_ready_or_exportable_claim',
      'domain_ready_claim',
      'production_ready_claim',
      'Live_Evidence_claim',
      'full_Plan_Completion_Audit_claim',
    ],
  },
  {
    lane_id: 'opl-doc-native-support-readback-20260622d',
    repo: 'opl-doc',
    priority: 'P2',
    milestone_ids: ['support_repo_profile_no_resurrection'],
    lane_status:
      'absorbed_remote_native_support_profile_no_resurrection_readback_non_live_evidence',
    write_set_class: 'opl_doc_native_check_support_profile_guard_readback',
    required_surfaces: [
      'source',
      'contract',
      'CLI_readback',
      'API_readback',
      'docs',
      'tests',
    ],
    non_live_completion_evidence_required: [
      'OPL_DOC_native_check_materializes_support_repo_policy',
      'OPL_DOC_native_check_materializes_support_profile_guard_and_audit',
      'OPL_DOC_native_check_false_ready_and_authority_boundary_fail_closed',
      'OPL_DOC_default_verify_uses_native_check_json_readback',
      'OPL_DOC_main_absorbed_push_and_remote_sha_readback_95b3cfaa4d35aa5791919d20052cb1c2d8d54841',
    ],
    deferred_evidence: DEFERRED_LIVE_EVIDENCE,
    forbidden_scope: [
      'OPL_family_domain_truth_write',
      'runtime_truth_write',
      'owner_receipt_signature',
      'typed_blocker_instance_creation',
      'Foundry_Agent_truth_set_membership_claim',
      'support_repo_ready_claim',
      'quality_verdict_claim',
      'production_ready_claim',
      'Live_Evidence_claim',
      'full_Plan_Completion_Audit_claim',
    ],
  },
];

export const FRAMEWORK_TRANCHE_MILESTONES: FrameworkTrancheMilestone[] = [
  {
    milestone_id: 'opl_primitive_runtime_owner_route_guard',
    priority: 'P0',
    state: 'closed_structure_gate',
    owner_repos: ['one-person-lab'],
    lane_role:
      'Upcollect OPL primitives for runtime env, owner route, typed blocker, ordinary path, and no-second-truth guard surfaces.',
    current_truth_refs: [
      'docs/active/current-state-vs-ideal-gap.md#active-planning-gap-register',
      'docs/status.md#durable-objective-current-reading',
      'contracts/opl-framework/runtime-environment-substrate-contract.json',
      'contracts/opl-framework/stage-route-scheduler-contract.json#stage_route_arbiter_substrate_contract.domain_progress_transition_runtime_first_slice',
      'contracts/opl-framework/target-operating-architecture-contract.json',
      'src/runtime-environment-substrate.ts',
      'src/family-runtime-domain-progress-transition-runtime.ts',
      'src/family-runtime-domain-progress-transition-runtime-parts/policy-adapter.ts',
      'src/family-transition-runner.ts#outcome_path_guard',
      'contracts/opl-framework/family-transition-runner-contract.json#outcome_path_guard',
      'tests/src/family-transition-runner.test.ts',
      'src/framework-readiness.ts',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: DEFERRED_LIVE_EVIDENCE,
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'domain_pack_generated_hosted_surfaces',
    priority: 'P0',
    state: 'closed_structure_gate',
    owner_repos: ['one-person-lab', 'med-autogrant', 'redcube-ai', 'opl-meta-agent'],
    lane_role:
      'Converge standard domain agents onto declarative Domain Pack input plus OPL generated/hosted surface readbacks.',
    current_truth_refs: [
      'contracts/opl-framework/domain-pack-compiler-contract.json',
      'src/domain-pack-compiler.ts',
      'src/modules/foundry-lab/standard-domain-agent-conformance-foundry-agent-os.ts#buildFoundryAgentOsConformance',
      'src/modules/foundry-lab/framework-tranche-backlog-parts/tranche-data.ts#FOUNDRY_STANDARD_AGENT_MEMBERSHIP_READBACK',
      'docs/active/current-state-vs-ideal-gap.md',
      'domain repos: contracts/private_functional_surface_policy.json',
      'redcube-ai@b0603a1a:contracts/generated_surface_handoff.json#OPL_GENERATED_SURFACE_EXIT_GATE.false_ready_guard',
      'redcube-ai@b0603a1a:contracts/functional_privatization_audit.json',
      'redcube-ai@b0603a1a:contracts/runtime-program/current-program.json',
      'redcube-ai@b0603a1a:tests/opl-agent-pack-contracts-generated-surface.test.ts',
      'redcube-ai@b0603a1a:docs/status.md',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: DEFERRED_LIVE_EVIDENCE,
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'strict_source_purity_private_wrapper_retirement',
    priority: 'P1',
    state: 'closed_structure_gate',
    owner_repos: ['med-autoscience', 'med-autogrant', 'redcube-ai', 'opl-meta-agent'],
    lane_role:
      'Thin or retire private wrapper residue with source-purity gates, no-active-caller proof, tombstone/provenance, and false-ready guards.',
    current_truth_refs: [
      'med-autoscience:contracts/runtime/legacy-active-path-tombstones.json#/legacy_control_receipt_exclusion_policy/legacy_markers',
      'med-autoscience:src/med_autoscience/controllers/progress_portal_parts/owner_delta_summary.py',
      'med-autoscience:tests/test_progress_portal.py',
      'med-autoscience:docs/runtime/display/progress_portal.md',
      'med-autoscience progress portal owner-delta residue closeout commit 092ce099b2e196e08998f5ef5725c13d5896d217',
      'OPL agents conformance family-defaults structural pass after MAS closeout commit 092ce099b2e196e08998f5ef5725c13d5896d217',
      'med-autogrant:contracts/private_functional_surface_policy.json#/physical_source_morphology_policy/retirement_readback_cleanup_guard',
      'med-autogrant:contracts/private_functional_surface_policy.json#/physical_source_morphology_policy/retirement_readback_cleanup_guard/compact_cleanup_readiness_summary',
      'med-autogrant:contracts/private_functional_surface_policy.json#/physical_source_morphology_policy/strict_source_purity_no_second_truth_guard',
      'med-autogrant:authority source-purity --format json#mag_strict_source_purity_guard_readback',
      'med-autogrant:authority source-purity --format json#compact_cleanup_readiness_summary',
      'med-autogrant:med_autogrant.product_entry_parts.source_purity_guard_readback.build_source_purity_guard_readback',
      'med-autogrant:scripts/check_source_purity_guard.py#mag_strict_source_purity_guard_readback',
      'med-autogrant:scripts/check_source_purity_guard.py#compact_cleanup_readiness_summary',
      'med-autogrant:src/med_autogrant/product_entry_parts/source_purity_guard_readback.py',
      'med-autogrant:src/med_autogrant/cli.py#source-purity-guard-readback',
      'med-autogrant:src/med_autogrant/public_cli.py#authority source-purity',
      'med-autogrant:tests/test_source_purity_guard_readback.py',
      'med-autogrant:authority morphology-guard#strict_source_purity_no_second_truth_guard',
      'med-autogrant:authority morphology-guard#source_ref_integrity_guard',
      'med-autogrant:src/med_autogrant/opl_standard_pack_source_policy.py',
      'med-autogrant:tests/product_entry_cases/test_physical_morphology_guard.py',
      'med-autogrant:docs/active/opl-private-implementation-migration-inventory.md',
      'redcube-ai:contracts/physical_source_morphology_policy.json',
      'redcube-ai:contracts/physical_source_morphology_policy.json#/default_caller_tail_thinning_gate/retirement_readback_cleanup_guard/json_transport_guard',
      'redcube-ai:scripts/check-private-platform-retirement.ts#rca_private_platform_retirement_strict_readback',
      'redcube-ai:scripts/check-private-platform-retirement.ts#default_caller_tail_compact_retirement_summary',
      'redcube-ai:package.json#scripts.private-platform:readback',
      'redcube-ai:npm run private-platform:readback',
      'redcube-ai:package.json#scripts.default-caller-tail:readback',
      'redcube-ai:npm run default-caller-tail:readback',
      'redcube-ai:npm run test:default-caller-tail:strict',
      'redcube-ai:scripts/check-private-platform-retirement.ts#rca_default_caller_tail_owner_delta_readback',
      'redcube-ai:contracts/physical_source_morphology_policy.json#/default_caller_tail_readback/compact_retirement_summary',
      'redcube-ai:tests/rca-private-platform-retirement-readback.test.ts',
      'redcube-ai:npm run test:private-platform:strict',
      'redcube-ai:tests/opl-agent-pack-contracts-source-morphology.test.ts',
      'redcube-ai:tests/rca-legacy-name-allowance.test.ts',
      'redcube-ai:docs/active/opl-private-implementation-migration-inventory.md',
      'redcube-ai:docs/active/rca-ideal-state-gap-plan.md',
      'opl-meta-agent:contracts/script_to_pack_gate_receipt.json#script_morphology_policy.retirement_readback_cleanup_guard',
      'opl-meta-agent:contracts/script_to_pack_gate_receipt.json#script_morphology_policy.generic_materializer_no_resurrection_guard',
      'opl-meta-agent:runtime/authority_functions/meta-agent-authority-functions.json#source_purity_scan_receipt.generic_script_materializer_scan',
      'opl-meta-agent:runtime/authority_functions/meta-agent-authority-functions.json#script_morphology_policy',
      'opl-meta-agent:runtime/authority_functions/meta-agent-authority-functions.parts/script_morphology_policy/root.json',
      'opl-meta-agent:contracts/script_to_pack_gate_receipt.json#/machine_gate_inputs/source_ref_integrity_guard',
      'opl-meta-agent:contracts/source_structure_policy.json#script_to_pack_receipt_guard.json_readback_command_ref',
      'opl-meta-agent:package.json#scripts.script-to-pack:readback',
      'opl-meta-agent:npm run script-to-pack:readback --silent',
      'opl-meta-agent:npm run script-to-pack:readback --silent#compact_cleanup_summary',
      'opl-meta-agent:npm run source-structure:json --silent',
      'opl-meta-agent:npm run source-structure:strict:json --silent',
      'opl-meta-agent:tests/source-purity.test.ts',
      'opl-meta-agent:tests/source-structure-lane.test.ts',
      'opl-meta-agent:docs/active/opl-private-implementation-migration-inventory.md',
      'OPL docs/active/current-state-vs-ideal-gap.md',
      'MAG morphology public readback commit 6182a75ae01eb636d639a21d674db917e77da6dc',
      'MAG strict source-purity readback commit 1f1a59c1ebcabc96c6441a72f10dea4b72ad3529',
      'MAG compact cleanup readiness readback commit 1edfc58fc10787fcdd080f1469710bc1ffe61a17',
      'MAG source-purity CLI/API readback commit 84828001957d4fd81da7948113915340b6e74d17',
      'OMA source-structure JSON readback commit b902ed0b0e1da4cf2ce559d03cb50ce2edcbe255',
      'OMA script-to-pack cleanup readback commit 20d3fce8f648d3956045b6eb7fa59805b5923b86',
      'OMA script-to-pack compact readback commit 3dfed67f4debf7f44b9b130bd9bb880500dd0340',
      'RCA active source resurrection guard commit a857539e2f045ef9d83dd83a265ede2f250982a4',
      'RCA private-platform JSON transport guard commit 0726ef03f158a0c90484edc53536f17cfe59a42f',
      'RCA private-platform compact tail readback commit 985bc5e3822018f129a94d8aa003f9bff259a59c',
      'RCA private-platform direct readback commit 10cde10b131b306e4ec41f31fe65c838aa9d41e1',
      'RCA default caller tail owner-delta readback commit 96e0dc0b9e2e3c7f7c754284810ec670d7aadd75',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: [
      'default_caller_live_scaleout',
      'App_operator_sustained_consumption',
      'physical_delete_owner_receipt',
      ...DEFERRED_LIVE_EVIDENCE,
    ],
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'standard_agent_landing_acceptance_guard',
    priority: 'P0',
    state: 'closed_structure_gate',
    owner_repos: ['one-person-lab'],
    lane_role:
      'Expose standard-agent landing acceptance, private-platform residue owner-decision, OMA target-agent guard, and negative conformance as one tranche-level readback without completion authority.',
    current_truth_refs: [
      'contracts/opl-framework/standard-agent-landing-acceptance-contract.json',
      'contracts/opl-framework/standard-agent-landing-evidence-status.json',
      'contracts/opl-framework/private-platform-residue-owner-decisions.json',
      'contracts/opl-framework/standard-agent-negative-conformance-samples.json',
      'src/modules/foundry-lab/framework-tranche-backlog-parts/standard-agent-landing-guard.ts',
      'src/private-platform-residue-owner-decisions.ts',
      'src/modules/foundry-lab/standard-domain-agent-conformance-foundry-agent-os.ts#FOUNDRY_AGENT_OS_SUPPORT_EXTENSIONS',
      'tests/src/standard-agent-landing-acceptance-contract.test.ts',
      'tests/src/cli/cases/agents-conformance-foundry-agent-os.test.ts',
      'tests/src/cli/cases/framework-readiness-cli-surface.test.ts',
      'OPL docs/active/current-state-vs-ideal-gap.md',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: [
      'generated_surface_production_consumption_owner_evidence',
      'OMA_target_agent_real_owner_closeout',
      'cross_agent_negative_conformance_scaleout',
      'long_soak_real_user_path_owner_evidence',
      ...DEFERRED_LIVE_EVIDENCE,
    ],
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'memory_artifact_lifecycle_functional_boundary',
    priority: 'P0',
    state: 'closed_structure_gate',
    owner_repos: ['one-person-lab'],
    lane_role:
      'Keep memory/artifact/lifecycle as refs-only intake, evidence readback, and owner-route work-order projection without body authority.',
    current_truth_refs: [
      'src/memory-artifact-lifecycle-evidence-ledger.ts',
      'src/memory-artifact-lifecycle-readback.ts',
      'src/runtime-tray-app-operator-drilldown-parts/memory-artifact-lifecycle-evidence.ts',
      'src/cli/cases/runtime-memory-artifact-lifecycle-evidence-command-spec.ts',
      'opl-bookforge@17d184c:contracts/artifact_lifecycle_handoff.json',
      'opl-bookforge@17d184c:contracts/workspace_lifecycle_policy.json',
      'opl-bookforge@17d184c:runtime/native_helpers/bookforge_project_hygiene.py',
      'opl-bookforge@17d184c:runtime/native_helpers/bookforge_project_hygiene_parts/opl_lifecycle.py',
      'opl-bookforge@17d184c:docs/active/bookforge-ideal-state-gap-plan.md',
      'docs/active/current-state-vs-ideal-gap.md',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: [
      'domain_memory_receipt_followthrough',
      'artifact_mutation_receipt_followthrough',
      'package_export_owner_acceptance',
      ...DEFERRED_LIVE_EVIDENCE,
    ],
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'oma_script_to_pack_hygiene',
    priority: 'P2',
    state: 'closed_structure_gate',
    owner_repos: ['opl-meta-agent'],
    lane_role:
      'Keep retained scripts machine-classified with active callers, OPL-surface consumption policy, retirement gates, and reciprocal consumption guard.',
    current_truth_refs: [
      'opl-meta-agent:contracts/script_to_pack_gate_receipt.json',
      'opl-meta-agent:runtime/authority_functions/meta-agent-authority-functions.json#script_morphology_policy',
      'opl-meta-agent:runtime/authority_functions/meta-agent-authority-functions.json#source_purity_scan_receipt.active_script_caller_scan',
      'opl-meta-agent:contracts/source_structure_policy.json#script_to_pack_receipt_guard.json_readback_command_ref',
      'opl-meta-agent:package.json#scripts.source-structure:json',
      'opl-meta-agent:package.json#scripts.source-structure:strict:json',
      'opl-meta-agent:package.json#scripts.script-to-pack:readback',
      'opl-meta-agent:scripts/check-source-structure.ts#oma_source_structure_readback',
      'opl-meta-agent:npm run script-to-pack:readback --silent',
      'opl-meta-agent:npm run script-to-pack:readback --silent#compact_cleanup_summary',
      'opl-meta-agent:npm run source-structure:json --silent',
      'opl-meta-agent:npm run source-structure:strict:json --silent',
      'opl-meta-agent:tests/source-purity.test.ts',
      'opl-meta-agent:tests/source-structure-lane.test.ts',
      'opl-meta-agent:docs/active/opl-private-implementation-migration-inventory.md',
      'opl-meta-agent script-to-pack cleanup readback commit 20d3fce8f648d3956045b6eb7fa59805b5923b86',
      'opl-meta-agent script-to-pack compact readback commit 3dfed67f4debf7f44b9b130bd9bb880500dd0340',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: [
      'OPL_primitive_parity_receipt',
      'script_physical_retirement_no_active_caller_receipt',
      'target_agent_live_patch_loop',
      ...DEFERRED_LIVE_EVIDENCE,
    ],
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'app_active_shell_hermes_convergence',
    priority: 'P2',
    state: 'closed_structure_gate',
    owner_repos: ['one-person-lab-app', 'opl-hermes-shell'],
    lane_role:
      'Keep AionUI/opl-aion-shell as the App mainline and Hermes Desktop as the only foreground alternative while AGUI remains archived technical proof.',
    current_truth_refs: [
      'one-person-lab-app@9cb0196c06d1203a33d9aad20b9299eac6f36a0e:scripts/validate-shell-convergence.ts',
      'one-person-lab-app@9cb0196c06d1203a33d9aad20b9299eac6f36a0e:contracts/app-shell-adapter.json',
      'one-person-lab-app@9cb0196c06d1203a33d9aad20b9299eac6f36a0e:contracts/app-shell-candidates.json',
      'one-person-lab-app@9cb0196c06d1203a33d9aad20b9299eac6f36a0e:tests/release/app-release-boundary-cases/shell-adapter-and-gui-contracts.ts',
      'one-person-lab-app@9cb0196c06d1203a33d9aad20b9299eac6f36a0e:docs/status.md',
      'OPL docs/status.md',
      'contracts/opl-framework/family-product-operator-projection.json',
      'opl-hermes-shell:contracts/opl-hermes-candidate-profile.json',
      'opl-hermes-shell:contracts/opl-hermes-candidate-profile.json#functional_convergence_readback',
      'opl-hermes-shell:contracts/opl-hermes-candidate-profile.json#operator_functional_surface_readback',
      'opl-hermes-shell:scripts/validate-hermes-codex-candidate.cjs',
      'opl-hermes-shell:electron/opl-codex-gateway.cjs#describeOplCodexGatewayScope',
      'opl-hermes-shell:npm run validate:candidate',
      'opl-hermes-shell functional convergence readback commit d167952981a266e4e6d1e185a6b1ee72d2b30da3',
      'opl-hermes-shell operator functional surface readback commit bd139d5e1bcb57e47defbd59f411032e0b240a60',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: [
      'App_release_cohort',
      'real_user_path',
      'packaged_gui_acceptance',
      'active_shell_adoption_decision',
      ...DEFERRED_LIVE_EVIDENCE,
    ],
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
  {
    milestone_id: 'support_repo_profile_no_resurrection',
    priority: 'P2',
    state: 'closed_structure_gate',
    owner_repos: ['opl-doc'],
    lane_role:
      'Keep support repos extension-only, outside default family repo truth, and guarded against authority resurrection.',
    current_truth_refs: [
      'opl-doc:contracts/support-repo-policy.json',
      'opl-doc:scripts/opl_doc_doctor.py support-profile-check . --format json',
      'opl-doc:scripts/opl_doc_doctor.py native-check . --format json#support_profile_guard',
      'opl-doc:scripts/opl_doc_doctor.py native-check . --format json#support_profile_guard_audit',
      'opl-doc:scripts/verify.sh support-profile:strict',
      'opl-doc:tests/test_opl_doc_doctor.py#test_support_profile_check_cli_is_direct_strict_readback',
      'opl-doc:tests/test_opl_doc_doctor.py#test_native_check_cli_materializes_support_profile_guard_readback',
      'opl-doc:scripts/opl_doc_doctor.py',
      'opl-doc support-profile strict readback commit 887f7f52483358cc219c59e32f0491e6d8836166',
      'opl-doc native support profile guard readback commit 95b3cfaa4d35aa5791919d20052cb1c2d8d54841',
      'OPL docs/active/current-state-vs-ideal-gap.md',
    ],
    non_live_evidence_acceptance: NON_LIVE_ACCEPTANCE,
    deferred_evidence: DEFERRED_LIVE_EVIDENCE,
    authority_boundary: { ...NO_SECOND_TRUTH_AUTHORITY_BOUNDARY },
  },
];
