export const SUMMARY_DRILLDOWN_KEYS = [
  'route_graph_refs',
  'decision_map_refs',
  'review_repair_queue_refs',
  'artifact_gallery_refs',
  'package_export_lifecycle_refs',
  'memory_writeback_refs',
  'quality_readiness_refs',
  'provider_slo_operator_action_refs',
  'runtime_manager_route_support',
  'route_transition_drilldown',
  'periodic_execution_refs',
  'operator_action_routing_refs',
  'owner_receipt_refs',
  'typed_blocker_refs',
  'domain_dispatch_evidence',
  'stage_production_evidence',
  'freshness_refs',
  'ref_family_refs',
  'safe_action_refs',
  'app_execution_bridge',
  'lifecycle_ledger_refs',
  'domain_projection_refs',
  'domain_owner_payload_summary_refs',
  'owner_evidence_sustained_consumption_refs',
  'domain_evidence_request_refs',
  'production_evidence_tail_ledger',
  'evidence_envelope',
  'runtime_visualization_projection',
  'domain_legacy_cleanup_plan_refs',
  'standard_agent_template_consumption_refs',
  'codex_app_runtime_role',
  'app_release_user_path_evidence',
  'developer_mode_live_closeout_evidence',
  'functional_privatization_audit_summary',
  'functional_privatization_audit_refs',
  'default_caller_deletion_evidence_refs',
] as const;

export const LAZY_LOAD_TARGETS = SUMMARY_DRILLDOWN_KEYS.map((section) => ({
  section,
  detail_args: ['--detail', 'full'],
  load_policy: 'explicit_drilldown_lazy_load',
}));
