import { STANDARD_PROGRESS_DELTA_POLICY } from './progress-delta.ts';
import { STANDARD_STAGE_COMPLETION_POLICY } from './stage-completion.ts';
import { STANDARD_TYPED_BLOCKER_LINEAGE_POLICY } from './typed-blocker.ts';
import { STANDARD_USER_STAGE_LOG_CONTRACT } from './user-stage-log.ts';
import { WORKSPACE_TOPOLOGY_PROFILE_CONTRACT } from '../../../kernel/workspace-topology-profile-contract.ts';

export const FOUNDRY_AGENT_SERIES_POLICY_RELEASE_REF =
  'contracts/opl-framework/foundry-agent-series-policy-release.json';
export const FOUNDRY_AGENT_SERIES_POLICY_EXPORT =
  'opl-framework/foundry-agent-series-policy';
export const FOUNDRY_AGENT_SERIES_CONSUMER_KIND =
  'opl_foundry_agent_series_consumer';
export const FOUNDRY_AGENT_SERIES_CONSUMER_VERSION =
  'foundry-agent-series-consumer.v1';
export const FOUNDRY_AGENT_SERIES_POLICY_BUNDLE_FINGERPRINT = 'sha256:11dae4f01d2647ba77b5bee332ceda0004be62984daab26903abe85f61e36722';

export const STANDARD_FOUNDRY_AGENT_SERIES_CONTRACT = {
  surface_kind: 'opl_foundry_agent_series_contract',
  version: 'foundry-agent-series.v1',
  owner: 'one-person-lab',
  product_layer: 'foundry_agent',
  product_model: 'OPL Framework -> One Person Lab App -> Foundry Agents',
  standard_agent_requirement:
    'foundry_agents_share_identity_stage_authority_progress_currentness_closeout_and_app_projection_packets',
  agent_membership_projection_policy: {
    surface_kind: 'opl_foundry_agent_membership_projection_policy',
    version: 'foundry-agent-membership-projection.v1',
    policy_id: 'standard_agent_membership_not_surface_origin',
    default_membership: 'standard_domain_agent',
    public_agent_list_must_not_split_by_generated_surface: true,
    public_agent_list_must_not_split_by_plugin_transport: true,
    generated_surface_is_membership_axis: false,
    generated_surface_is_status_axis: false,
    plugin_transport_is_membership_axis: false,
    plugin_transport_is_status_axis: false,
  },
  primary_skill_carrier_projection_policy: {
    surface_kind: 'opl_primary_skill_carrier_projection_policy',
    version: 'primary-skill-carrier-projection.v1',
    policy_id: 'repo_owned_primary_skill_materialized_as_codex_plugin_carrier',
    applies_to_series_membership: 'standard_domain_agent',
    canonical_primary_skill_path: 'agent/primary_skill/SKILL.md',
    codex_plugin_skill_path: 'plugins/<plugin_name>/skills/<plugin_name>/SKILL.md',
    carrier_materialization: 'materialized_full_skill_copy',
    materializer: 'opl_standard_codex_plugin_materializer',
    codex_install_requires_real_skill_md: true,
    plugin_skill_may_be_stub_or_pointer: false,
    repo_local_plugin_carrier_is_transport_only: true,
    opl_materialized_plugin_carrier_is_transport_only: true,
    carrier_can_claim_domain_ready: false,
    carrier_can_write_domain_truth: false,
    carrier_can_sign_owner_receipt: false,
    carrier_can_create_typed_blocker: false,
  },
  standard_public_projection_policy: {
    surface_kind: 'opl_foundry_agent_standard_public_projection_policy',
    version: 'foundry-agent-standard-public-projection.v1',
    policy_id: 'standard_agent_public_foundry_surface_is_opl_generated_hosted_series',
    standard_public_foundry_surface: 'opl_generated_hosted_series',
    canonical_inspect_command_pattern: 'opl agents inspect <agent_id>',
    allowed_active_public_foundry_surfaces: [
      'opl_foundry_agent_series_spine',
      'opl_family_hosted_surfaces',
    ],
    active_public_projection_allows_non_opl_foundry_cli: false,
    active_public_projection_allows_domain_owned_cli_as_standard_surface: false,
    active_public_projection_allows_forbidden_surface_roles: false,
    active_public_projection_allows_compatibility_aliases: false,
    active_public_projection_allows_legacy_json_aliases: false,
    minimal_authority_functions_are_membership_axis: false,
    domain_owned_helpers_are_membership_axis: false,
    allowed_domain_owned_helper_context: 'minimal_authority_functions_only',
    non_standard_surface_retention_contexts: [
      'history',
      'tombstone',
    ],
  },
  series_design_profile: {
    surface_kind: 'opl_foundry_agent_series_design_profile',
    version: 'foundry-agent-series-design-profile.v1',
    profile_id: 'opl_foundry_agent_series_design_profile.v1',
    profile_summary:
      'All Foundry Agents share the same OPL domain-pack to stage-led execution to gate/receipt to handoff lifecycle; domain inputs, outputs, aliases, and authority functions vary by agent.',
    shared_lifecycle_pipeline: [
      'domain_material_intake',
      'domain_pack_interpretation',
      'stage_led_agent_execution',
      'independent_quality_gate_or_owner_review',
      'consumable_artifact_progress_or_owner_answer_or_hard_stop_closeout',
      'artifact_or_deliverable_handoff',
      'opl_refs_only_projection_and_recovery',
    ],
    domain_io_profile: {
      input_slot: 'domain_materials_or_task_request',
      output_slot: 'domain_deliverable_or_owner_handoff',
      input_is_domain_specific: true,
      output_is_domain_specific: true,
      shared_runtime_interpretation:
        'OPL treats input/output as opaque domain refs and projects identity, stage, progress, closeout, evidence, and recovery metadata only.',
    },
    stage_pack_sections: [
      'prompts',
      'stages',
      'skills',
      'tools',
      'knowledge',
      'quality_gates',
      'stage_completion_policy',
    ],
    shared_closeout_contract: {
      success_shape: 'validated_consumable_artifact_progress_ref_or_domain_owner_receipt_ref',
      blocked_shape: 'domain_owned_typed_hard_blocker_ref',
      route_back_shape: 'quality_debt_repair_recommendation_or_human_gate_ref',
      provider_completion_is_closeout: false,
      quality_budget_exhaustion_blocks_route: false,
      owner_receipt_required_for_quality_or_ready_claim: true,
      completion_judgment_owner: 'domain_stage',
      opl_content_judgment_allowed: false,
    },
    authority_invariants: {
      opl_can_infer_domain_output: false,
      opl_can_read_domain_body: false,
      opl_can_write_domain_truth: false,
      opl_can_authorize_quality_or_export: false,
      domain_owns_input_truth_and_output_authority: true,
    },
  },
  workspace_topology_profile: WORKSPACE_TOPOLOGY_PROFILE_CONTRACT,
  framework_brand_taxonomy_policy: {
    surface_kind: 'opl_framework_brand_taxonomy_agent_cli_policy',
    version: 'framework-brand-taxonomy-agent-cli.v1',
    taxonomy_ref: 'contracts/opl-framework/brand-module-registry.json',
    taxonomy_scope: 'opl_framework_top_level_public_command_surface',
    top_level_modules: [
      'charter',
      'atlas',
      'workspace',
      'stagecraft',
      'runway',
      'ledger',
      'console',
      'foundry',
      'connect',
    ],
    agent_cli_public_command_surface_role: 'foundry_agent_series_spine',
    opl_nine_modules_are_framework_taxonomy: true,
    agent_cli_can_reference_framework_taxonomy: true,
    agent_cli_must_use_series_spine: true,
    agent_cli_must_not_replicate_top_level_modules_as_series_spine: true,
  },
  agent_cli_command_surface_policy: {
    surface_kind: 'opl_foundry_agent_series_cli_command_surface_policy',
    version: 'foundry-agent-cli-command-surface.v1',
    policy_id: 'foundry_agent_series_spine_public_command_surface',
    canonical_opl_command_surface: 'opl agents run',
    agent_cli_series_label: 'OPL Foundry Agent',
    ordinary_operations: ['run'],
    ordinary_public_command_surface_spine: [
      'workspace',
      'work',
      'stage',
      'run',
      'ledger',
      'handoff',
      'connect',
    ],
    required_public_surface_derivatives: [
      'cli',
      'skill',
      'mcp',
      'app_action',
    ],
    agent_cli_must_use_series_spine: true,
    agent_cli_must_not_replicate_top_level_modules: true,
  },
  non_standard_implementation_bucket_policy: {
    surface_kind: 'opl_foundry_agent_non_standard_implementation_bucket_policy',
    version: 'foundry-agent-legacy-bucket-retirement.v1',
    ordinary_public_command_surface_allowed: false,
    replacement_command_surface: 'opl agents run',
    non_standard_bucket_prefixes: [
      'runtime',
      'family-runtime',
      'index',
      'stage-artifact',
      'agents modules',
      'module',
      'modules',
      'skill',
      'packages',
      'engine',
    ],
    allowed_retained_read_surfaces: [
      'diagnostic_drilldown',
      'migration_error',
      'scoped_help_for_replacement',
      'internal_contract_validation',
    ],
    non_standard_buckets_cannot_claim_series_identity: true,
    non_standard_buckets_cannot_replace_connect_skill_mcp_command_surface: true,
  },
  skill_mcp_surface_policy: {
    surface_kind: 'opl_foundry_agent_skill_mcp_surface_policy',
    version: 'foundry-agent-skill-mcp-surface.v1',
    skill_pack_must_delegate_to_series_spine: true,
    mcp_descriptor_must_delegate_to_series_spine: true,
    canonical_skill_connect_command_surface: 'opl connect skills',
    canonical_skill_sync_command_surface: 'opl connect sync-skills',
    canonical_mcp_projection_ref: 'skill_catalog.packs[].mcp_projection',
    standard_agent_standalone_mcp_default_enabled: false,
    standard_agent_plugin_manifest_must_not_expose_mcp_servers: true,
    opl_unified_mcp_projection_owner: 'one-person-lab',
    future_unified_mcp_server_strategy: 'opl_owned_unified_server_when_runtime_verified',
    domain_repo_mcp_server_role: 'direct_protocol_adapter_or_proof_lane_only',
    cli_mcp_relationship_policy: {
      surface_kind: 'opl_cli_mcp_relationship_policy',
      cli_surface_role: 'authoritative_broad_operator_control_debug_and_admin_surface',
      mcp_surface_role: 'curated_agent_facing_discovery_and_invocation_surface',
      all_cli_commands_are_mcp_tools: false,
      mcp_must_not_mirror_full_cli_by_default: true,
      cli_remains_source_for_broad_control_and_diagnostics: true,
      mcp_tools_must_delegate_to_cli_or_contract_owner_surface: true,
      mcp_tool_existence_does_not_create_domain_authority: true,
      mutating_mcp_tools_require_owner_or_human_gate: true,
    },
    mcp_context_budget_policy: {
      surface_kind: 'opl_mcp_context_budget_policy',
      progressive_discovery_required_for_large_catalogs: true,
      toolset_filtering_required_for_broad_surfaces: true,
      descriptor_first_lazy_schema_required: true,
      search_describe_execute_pattern_allowed: true,
      full_cli_mirror_forbidden: true,
      concise_tool_schema_required: true,
      list_changed_refresh_required: true,
      preferred_patterns: [
        'toolsets',
        'search_tools',
        'describe_tools',
        'execute_tool',
        'read_only_default',
        'explicit_mutation_gate',
      ],
    },
    legacy_skill_command_retired: true,
    legacy_standalone_mcp_servers_retired: true,
    derived_surface_refs: [
      'opl agents run --domain <agent_id> --action <action_id> --json',
      'opl connect skills --json',
      'opl connect sync-skills --json',
    ],
  },
  contract_version_policy: {
    current_version: 'foundry-agent-series.v1',
    domain_contract_ref: 'contracts/foundry_agent_series.json',
    exact_version_pin_required: true,
    compatible_version_range: ['foundry-agent-series.v1'],
    breaking_change_requires_new_version: true,
    domain_descriptor_must_reference_domain_contract: true,
  },
  shared_policy_release: {
    policy_release_contract_ref: FOUNDRY_AGENT_SERIES_POLICY_RELEASE_REF,
    policy_bundle_fingerprint: FOUNDRY_AGENT_SERIES_POLICY_BUNDLE_FINGERPRINT,
    fingerprint_algorithm: 'sha256:stable-json',
    domain_contract_policy_release_pin_required: true,
    domain_adapter_must_not_copy_policy_body_as_authority: true,
    consumer_alignment_check: 'foundry:policy-release',
  },
  required_identity_fields: [
    'domain_id',
    'foundry_agent_id',
    'product_layer',
    'domain_label',
    'authority_owner',
    'stage_manifest_ref',
  ],
  required_stage_packets: [
    'stage_completion_policy',
    'user_stage_log_contract',
    'progress_delta_policy',
    'typed_blocker_lineage_policy',
    'effective_current_context',
    'consumable_artifact_progress_or_owner_answer_or_hard_stop_closeout',
  ],
  shared_progress_projection_fields: [
    'progress_delta_classification',
    'deliverable_progress_delta',
    'platform_repair_delta',
    'next_forced_delta',
  ],
  domain_adapter_policy: {
    domain_specific_aliases_only: true,
    no_parallel_progress_schema: true,
    no_parallel_blocker_lineage_schema: true,
    no_domain_runtime_fork: true,
  },
  app_projection_policy: {
    app_consumes_shared_progress_projection_only: true,
    app_can_read_domain_body: false,
    app_can_write_domain_truth: false,
    app_can_claim_quality_or_export: false,
    display_policy: 'classification_only_no_domain_artifact_body',
  },
  authority_boundary: {
    opl_owns_series_contract: true,
    domain_owns_truth_quality_artifact_memory_and_receipts: true,
    app_owns_display_and_user_action_shell: true,
    generated_surface_can_claim_domain_ready: false,
    generated_surface_can_claim_quality_or_export: false,
    generated_surface_can_write_domain_truth: false,
    generated_surface_can_create_owner_receipt: false,
    generated_surface_can_create_typed_blocker: false,
  },
} as const;

export const STANDARD_FOUNDRY_AGENT_GOLDEN_PATH_POLICY = {
  surface_kind: 'opl_foundry_agent_golden_path_default_surface_budget_policy',
  version: 'foundry-agent-golden-path.v1',
  owner: 'one-person-lab',
  policy_id: 'golden_path_single_default',
  default_surface_budget_id: 'default_surface_budget',
  stage_control_plane_ref: 'opl-generated:family_stage_control_plane',
  ordinary_default_route_budget: 1,
  default_route_selector: 'stages[] without explicit lane kind + selected_executor.default_executor',
  explicit_lane_kinds: [
    'variant',
    'variants',
    'proof',
    'diagnostic',
    'cleanup',
    'long-soak',
    'long_soak',
  ],
  explicit_lane_default_allowed: false,
  authority_boundary: {
    guard_can_write_domain_truth: false,
    guard_can_write_memory_body: false,
    guard_can_authorize_quality_or_export: false,
    guard_can_claim_domain_ready: false,
  },
} as const;

export const FOUNDRY_AGENT_SERIES_LEGACY_POLICY_BODY_FIELDS = [
  'agent_membership_projection_policy',
  'app_projection_policy',
  'contract_version_policy',
  'domain_adapter_policy',
  'required_identity_fields',
  'required_stage_packets',
  'series_design_profile',
  'shared_progress_projection_fields',
  'standard_feedback_self_evolution_trigger_policy',
  'standard_public_projection_policy',
  'workspace_topology_profile',
] as const;

export const FOUNDRY_AGENT_SERIES_CONSUMER_REQUIRED_AUTHORITY_BOUNDARY_FIELDS = [
  'domain_can_write_other_domain_truth',
  'domain_can_write_other_domain_memory_body',
  'domain_can_mutate_other_domain_artifact_body',
  'domain_can_authorize_other_domain_quality_or_export',
  'generated_surface_can_claim_domain_ready',
] as const;

export const STANDARD_FOUNDRY_AGENT_SERIES_CONSUMER_CONTRACT = {
  surface_kind: FOUNDRY_AGENT_SERIES_CONSUMER_KIND,
  version: FOUNDRY_AGENT_SERIES_CONSUMER_VERSION,
  canonical_policy_export: FOUNDRY_AGENT_SERIES_POLICY_EXPORT,
  canonical_series_contract_ref: 'contracts/opl-framework/foundry-agent-series-contract.json',
  canonical_skeleton_contract_ref: 'contracts/opl-framework/standard-domain-agent-skeleton-contract.json',
  shared_policy_release: STANDARD_FOUNDRY_AGENT_SERIES_CONTRACT.shared_policy_release,
  required_domain_fields: [
    'domain_id',
    'foundry_agent_id',
    'product_layer',
    'authority_owner',
    'stage_manifest_ref',
    'stage_control_plane_ref',
    'authority_boundary',
  ],
  legacy_policy_body_fields_forbidden: FOUNDRY_AGENT_SERIES_LEGACY_POLICY_BODY_FIELDS,
  authority_boundary: {
    consumer_contract_can_write_domain_truth: false,
    consumer_contract_can_authorize_quality_or_export: false,
    consumer_contract_can_replace_canonical_policy: false,
  },
} as const;

export const FOUNDRY_AGENT_SERIES_POLICY_BUNDLE = {
  surface_kind: 'opl_foundry_agent_series_policy_bundle',
  version: 'foundry-agent-series-policy-bundle.v1',
  owner: 'one-person-lab',
  bundle_id: 'opl.progress_first.foundry_agent_series_policy_bundle.v1',
  series_contract_ref: 'contracts/opl-framework/foundry-agent-series-contract.json',
  included_policy_surfaces: [
    {
      surface_id: 'foundry_agent_series_contract',
      ref: 'contracts/opl-framework/foundry-agent-series-contract.json',
      version: STANDARD_FOUNDRY_AGENT_SERIES_CONTRACT.version,
      domain_pin_ref: 'contracts/foundry_agent_series.json#/shared_policy_release',
    },
    {
      surface_id: 'stage_completion_policy',
      ref: 'contracts/opl-framework/standard-domain-agent-skeleton-contract.json#/new_agent_scaffold/stage_completion_policy',
      version: STANDARD_STAGE_COMPLETION_POLICY.version,
      completion_judgment_owner: STANDARD_STAGE_COMPLETION_POLICY.completion_judgment_owner,
      closeout_packet_required: STANDARD_STAGE_COMPLETION_POLICY.closeout_packet_required,
      raw_artifact_sufficient_for_progress: STANDARD_STAGE_COMPLETION_POLICY.raw_artifact_sufficient_for_progress,
      semantic_route_decision_owner: STANDARD_STAGE_COMPLETION_POLICY.semantic_route_decision_owner,
      stage_transition_materialization_owner:
        STANDARD_STAGE_COMPLETION_POLICY.stage_transition_materialization_owner,
      required_closeout_outcomes: STANDARD_STAGE_COMPLETION_POLICY.required_closeout_outcomes,
      accepted_closeout_ref_fields: STANDARD_STAGE_COMPLETION_POLICY.accepted_closeout_ref_fields,
    },
    {
      surface_id: 'user_stage_log_contract',
      ref: 'contracts/opl-framework/standard-domain-agent-skeleton-contract.json#/new_agent_scaffold/user_stage_log_contract',
      version: STANDARD_USER_STAGE_LOG_CONTRACT.version,
      required_fields: STANDARD_USER_STAGE_LOG_CONTRACT.required_domain_semantic_fields,
    },
    {
      surface_id: 'progress_delta_policy',
      ref: 'contracts/opl-framework/standard-domain-agent-skeleton-contract.json#/new_agent_scaffold/progress_delta_policy',
      version: STANDARD_PROGRESS_DELTA_POLICY.version,
      required_fields: STANDARD_PROGRESS_DELTA_POLICY.required_fields,
      classification_values: STANDARD_PROGRESS_DELTA_POLICY.classification_values,
    },
    {
      surface_id: 'typed_blocker_lineage_policy',
      ref: 'contracts/opl-framework/standard-domain-agent-skeleton-contract.json#/new_agent_scaffold/typed_blocker_lineage_policy',
      version: STANDARD_TYPED_BLOCKER_LINEAGE_POLICY.version,
      required_fields: STANDARD_TYPED_BLOCKER_LINEAGE_POLICY.required_fields,
      repeat_budget: STANDARD_TYPED_BLOCKER_LINEAGE_POLICY.repeat_budget,
    },
    {
      surface_id: 'effective_current_context',
      ref: 'contracts/opl-framework/family-runtime-attempt-contract.json#/required_projection_fields/effective_current_context',
      version: 'effective_current_context.v1',
      required_fields: [
        'owner_route',
        'source_fingerprint',
        'stage_packet',
        'workspace_or_session_identity',
        'latest_closeout',
        'running_attempt',
        'superseded_lineage',
      ],
    },
    {
      surface_id: 'app_progress_projection',
      ref: 'contracts/opl-framework/foundry-agent-series-contract.json#/shared_progress_projection_fields',
      version: 'foundry-agent-series-app-progress-projection.v1',
      required_fields: STANDARD_FOUNDRY_AGENT_SERIES_CONTRACT.shared_progress_projection_fields,
    },
  ],
  domain_alias_policy: {
    aliases_are_domain_specific_only: true,
    deliverable_delta_aliases: STANDARD_PROGRESS_DELTA_POLICY.deliverable_delta_aliases,
    platform_delta_aliases: STANDARD_PROGRESS_DELTA_POLICY.platform_delta_aliases,
  },
  authority_boundary: {
    opl_owns_policy_contract: true,
    domains_own_truth_quality_artifact_memory_and_receipts: true,
    app_consumes_projection_only: true,
    policy_release_can_claim_domain_ready: false,
  },
} as const;

export const FOUNDRY_AGENT_SERIES_POLICY_RELEASE = {
  surface_kind: 'opl_foundry_agent_series_policy_release',
  version: 'foundry-agent-series-policy-release.v1',
  owner: 'one-person-lab',
  release_contract_ref: FOUNDRY_AGENT_SERIES_POLICY_RELEASE_REF,
  series_contract_ref: 'contracts/opl-framework/foundry-agent-series-contract.json',
  policy_bundle: FOUNDRY_AGENT_SERIES_POLICY_BUNDLE,
  policy_bundle_fingerprint: FOUNDRY_AGENT_SERIES_POLICY_BUNDLE_FINGERPRINT,
  fingerprint_algorithm: 'sha256:stable-json',
  domain_pin_contract_ref: 'contracts/foundry_agent_series.json#/shared_policy_release',
  domain_pin_requirements: {
    exact_policy_release_ref_required: true,
    exact_policy_bundle_fingerprint_required: true,
    domain_adapter_must_not_copy_policy_body_as_authority: true,
    policy_body_authority_owner: 'one-person-lab',
  },
  authority_boundary: {
    release_can_claim_domain_ready: false,
    release_can_write_domain_truth: false,
    release_can_authorize_quality_or_export: false,
    release_can_replace_domain_owner_receipt: false,
  },
} as const;
