export const FORBIDDEN_DOMAIN_GENERIC_OWNER_ROLES = [
  'generic_scheduler_owner',
  'generic_daemon_owner',
  'generic_lifecycle_owner',
  'generic_queue_owner',
  'generic_attempt_ledger_owner',
  'generic_state_machine_runner_owner',
  'generic_cli_mcp_product_wrapper_owner',
  'generic_sidecar_owner',
  'generic_session_store_owner',
  'generic_status_workbench_owner',
  'generic_workspace_source_intake_owner',
  'generic_memory_transport_owner',
  'generic_artifact_gallery_owner',
  'generic_operator_workbench_owner',
  'generic_observability_slo_owner',
  'generic_persistence_engine_owner',
  'generic_sqlite_lifecycle_owner',
  'generic_native_helper_envelope_owner',
  'generic_review_repair_transport_owner',
  'generated_surface_owner_in_domain_repo',
] as const;

export const REQUIRED_CONTRACT_SURFACES = [
  'domain_agent_descriptor',
  'pack_compiler_input',
  'generated_surface_handoff',
  'product_entry_manifest',
  'stage_control_plane',
  'family_action_catalog',
  'domain_memory_descriptor_locator',
  'artifact_locator_contract',
  'owner_receipt_contract',
  'foundry_agent_series_contract',
  'standard_agent_principles_adoption',
  'capability_map',
  'user_stage_log_contract',
  'progress_delta_policy',
  'typed_blocker_lineage_policy',
  'stage_operating_principles',
  'quality_or_export_gate_refs',
  'physical_skeleton_follow_through',
  'legacy_retirement_tombstone_proof',
  'functional_privatization_audit',
  'workspace_lifecycle_policy',
  'stage_artifact_kernel_adoption',
  'stage_run_kernel_profile',
  'stage_run_canary_evidence',
  'state_index_kernel_adoption',
] as const;

export const REQUIRED_VERIFICATION = [
  'direct_skill_path_parity',
  'opl_hosted_path_parity',
  'no_forbidden_write',
  'no_active_generic_owner_caller',
  'replacement_or_no_regression_evidence',
  'receipt_ref_reconciliation',
  'user_stage_log_semantics_or_progress_diagnostic',
  'git_diff_check',
  'agent_pack_required_paths_resolve',
  'capability_map_refs_resolve',
  'stage_prompt_skill_knowledge_quality_gate_refs_resolve',
  'pack_compiler_input_schema_check',
  'generated_surface_handoff_parity',
  'generated_surface_no_domain_owner',
  'functional_privatization_audit_no_generic_owner',
  'workspace_file_lifecycle_policy_declared',
  'stage_artifact_kernel_adoption_declared',
  'stage_operating_principles_declared',
  'standard_agent_principles_adopted',
  'stage_run_kernel_profile_declared',
  'stage_run_controlled_canary_evidence_declared',
  'state_index_kernel_adoption_declared',
] as const;

export const REQUIRED_AGENT_PACK_SECTIONS = [
  { section: 'principles', prefix: 'agent/principles/' },
  { section: 'prompts', prefix: 'agent/prompts/' },
  { section: 'stages', prefix: 'agent/stages/' },
  { section: 'skills', prefix: 'agent/skills/' },
  { section: 'tools', prefix: 'agent/tools/' },
  { section: 'quality_gates', prefix: 'agent/quality_gates/' },
  { section: 'knowledge', prefix: 'agent/knowledge/' },
] as const;
export const FORBIDDEN_AGENT_PACK_TEXT = /\b(TODO|TBD)\b/i;
