export const STANDARD_AGENT_DEFAULT_RUNTIME_POLICY = {
  surface_kind: 'opl_standard_agent_default_runtime_policy',
  owner: 'one-person-lab',
  default_runtime_path: 'opl_temporal_hosted_autonomous',
  temporal_hosted_autonomy_default_enabled: true,
  runtime_owner: 'one-person-lab',
  provider_owner: 'one-person-lab',
  provider_kind_required_for_production: 'temporal',
  default_executor_kind: 'codex_cli',
  codex_app_drives_long_running_tasks: false,
  codex_app_role: 'start_observe_intervene_project_only',
  provider_managed_surfaces: [
    'stage_attempt_runtime',
    'stage_attempt_request_projection',
    'wakeup',
    'resume_requery',
    'retry_dead_letter',
    'attempt_ledger',
    'stage_progress_log',
    'operator_projection',
  ],
  required_user_stage_log: {
    surface_kind: 'opl_user_stage_log_requirement',
    stage_progress_log_owner: 'one-person-lab',
    domain_semantics_owner: 'domain_agent',
    canonical_domain_fields: [
      'stage_name',
      'problem_summary',
      'stage_goal',
      'stage_work_done',
      'changed_stage_surfaces',
      'progress_delta_classification',
      'deliverable_progress_delta',
      'platform_repair_delta',
      'next_forced_delta',
      'outcome',
      'remaining_blockers',
    ],
    platform_only_is_not_deliverable_progress: true,
    accepted_domain_semantic_sources: [
      'user_stage_log',
      'stage_log_summary',
      'human_stage_log',
    ],
    missing_semantic_summary_status: 'missing_domain_semantic_summary',
    completion_transparency_rule:
      'stage attempts without domain-provided user-readable semantics remain visible as a semantic gap and cannot be treated as user-transparent closeout',
    authority_boundary: {
      opl_can_infer_domain_semantics: false,
      opl_can_read_artifact_body: false,
      opl_can_claim_quality_or_export_verdict: false,
    },
  },
  domain_agent_internal_daemon_allowed: false,
  domain_agent_internal_scheduler_allowed: false,
  domain_agent_internal_attempt_loop_allowed: false,
  domain_agent_retained_authority: [
    'domain_truth',
    'quality_or_export_verdict',
    'artifact_authority',
    'memory_body_accept_reject',
    'owner_receipt',
    'typed_blocker',
  ],
  authority_boundary: {
    provider_completion_can_claim_domain_ready: false,
    provider_completion_can_claim_quality_or_export_verdict: false,
    provider_completion_can_write_domain_truth: false,
    provider_completion_can_issue_owner_receipt: false,
    domain_agent_can_install_generic_daemon: false,
  },
} as const;
