export const STAGE_ARTIFACT_KERNEL_ADOPTION_POLICY = {
  surface_kind: 'opl_stage_artifact_kernel_adoption',
  version: 'opl-stage-artifact-kernel-adoption.v1',
  kernel_contract_ref: 'contracts/opl-framework/stage-artifact-runtime-contract.json',
  stage_folder_unit: [
    'Stage Folder',
    'Manifest',
    'Receipt',
    'current pointer',
  ],
  terminal_states: [
    'success',
    'blocked',
    'skipped',
    'deferred',
  ],
  required_ref_fields: [
    'stage_folder_contract_ref',
    'stage_json_ref',
    'attempt_json_ref',
    'manifest_ref',
    'receipt_ref',
    'current_pointer_ref',
    'canonical_artifact_ref',
    'export_ref',
    'lineage_ref',
    'retention_ref',
  ],
  kernel_refs: {
    physical_stage_folder_source_of_truth: true,
    derived_index_rebuildable: true,
    manifest_receipt_hash_required: true,
  },
  domain_pack_binding: {
    accepted_source_refs: [
      'agent/stages/manifest.json',
      'contracts/foundry_agent_series.json',
    ],
    domain_output_roles_are_interface: true,
    file_name_is_not_interface: true,
  },
  projection_boundary: {
    derived_projection_refs: [
      'stage_artifact_index',
      'stage_operating_layer',
      'app_workbench_artifact_drilldown',
    ],
    file_presence_only_counts_as: 'orphan_or_historical',
    provider_completion_counts_as_progress: false,
  },
  authority_boundary: {
    opl_can_create_domain_owner_receipt: false,
    opl_can_write_domain_truth: false,
    opl_can_write_memory_body: false,
    opl_can_mutate_domain_artifact_body: false,
    opl_can_authorize_quality_or_export: false,
  },
} as const;

export const STAGE_RUN_KERNEL_PROFILE = {
  surface_kind: 'opl_stage_run_kernel_profile',
  version: 'stage-run-kernel-profile.v1',
  state: 'active_contract',
  kernel_contract_ref: 'contracts/opl-framework/stage-run-kernel-contract.json',
  stage_manifest_schema_ref: 'contracts/opl-framework/stage-manifest.schema.json',
  role_artifact_ref_schema_ref: 'contracts/opl-framework/role-artifact-ref.schema.json',
  owner_receipt_schema_ref: 'contracts/opl-framework/stage-owner-receipt.schema.json',
  typed_blocker_schema_ref: 'contracts/opl-framework/stage-typed-blocker.schema.json',
  kernel_role: 'minimal_state_shell_not_domain_controller_system',
  stage_native_unit: [
    'stage_folder',
    'stage_manifest',
    'role_artifacts',
    'progress_receipt_or_owner_answer_or_hard_stop',
  ],
  required_object_models: [
    'StageRun',
    'RoleArtifactRef',
    'ProgressDeltaReceipt',
    'OwnerReceipt',
    'TypedBlocker',
    'ReadModel',
  ],
  stage_run_state_machine: {
    provider_completion_counts_as_domain_accepted: false,
    file_presence_counts_as_stage_complete: false,
    latest_json_counts_as_domain_accepted: false,
    read_model_counts_as_transition_authority: false,
    validated_consumable_artifact_progress_counts_as_transition: true,
    quality_debt_counts_as_quality_acceptance: false,
  },
  launch_admission_policy: {
    hard_blockers: [
      'identity',
      'owner',
      'scope',
      'selected_executor',
      'authority_boundary',
      'required_role_artifacts',
      'receipt_or_blocker_shape',
      'forbidden_write',
      'replay_audit_lineage',
    ],
    advisory_refs: [
      'prompt_refs',
      'skill_refs',
      'tool_affordance_refs',
      'knowledge_refs',
      'rubric_refs',
      'evaluation_refs',
    ],
    advisory_refs_can_block_launch: false,
  },
  default_read_surface: {
    root: 'stage_run_current_owner_delta',
    raw_worklist_default: false,
    readiness_default: false,
    replay_packet_default: false,
  },
  transition_authority: {
    terminal_transition_authority: 'consumable_artifact_progress_or_owner_answer_or_hard_stop',
    provider_completion_counts_as_transition: false,
    file_presence_counts_as_transition: false,
    quality_budget_exhaustion_blocks_transition: false,
    owner_receipt_required_for_quality_or_ready_claim: true,
  },
  authority_boundary: {
    opl_can_write_domain_truth: false,
    opl_can_mutate_artifact_body: false,
    opl_can_sign_domain_owner_receipt: false,
    opl_can_create_typed_blocker: false,
    opl_can_authorize_quality_or_export: false,
    provider_completion_counts_as_domain_accepted: false,
    read_model_can_be_truth_source: false,
  },
} as const;
