import type {
  BrandCliGovernanceContract,
  BrandModuleL5OperatingEvidenceContract,
  BrandModuleRegistryContract,
  BrandModuleSurfacesContract,
  BrandSystemProfileContract,
  SourceModuleMapContract,
} from '../../../../../src/types.ts';

const MINIMAL_BRAND_MODULE_IDS = [
  'charter',
  'atlas',
  'workspace',
  'pack',
  'stagecraft',
  'runway',
  'ledger',
  'console',
  'foundry-lab',
  'connect',
] as const;

const MINIMAL_BRAND_MODULE_GATES = [
  'brand_doc_ref',
  'registry_entry',
  'contract_or_policy_ref',
  'cli_surface_ref',
  'app_or_operator_surface_ref',
  'descriptor_surface_ref',
  'validation_surface_ref',
  'status_or_maturity_doc_ref',
  'authority_boundary',
  'forbidden_claims',
];

const MINIMAL_BRAND_MODULE_L5_EVIDENCE_CLASSES = [
  'live_user_path',
  'cross_agent_scaleout',
  'long_soak_recovery',
  'release_install_evidence',
  'operator_repair_loop',
  'owner_acceptance',
  'no_second_truth_regression',
  'pack_compile_parity',
  'current_owner_delta_default_read',
  'capability_fail_open_boundary',
  'domain_authority_false_boundary',
  'cross_agent_foundry_agent_os_adoption',
] as const;

export const MINIMAL_BRAND_MODULE_REGISTRY_CONTRACT: BrandModuleRegistryContract = {
  version: 'brand-modules.test',
  scope: 'opl_brand_module_registry',
  owner: 'one-person-lab',
  purpose: 'test fixture',
  state: 'test_fixture',
  machine_boundary: 'test fixture',
  baseline_module_id: 'workspace',
  maturity_model: [
    {
      level: 'L4_structural_baseline',
      definition: 'test fixture',
      required_gates: MINIMAL_BRAND_MODULE_GATES,
    },
  ],
  external_reference_principles: ['test fixture'],
  modules: MINIMAL_BRAND_MODULE_IDS.map((moduleId) => ({
    module_id: moduleId,
    brand_name: `OPL ${moduleId}`,
    owner: 'one-person-lab',
    purpose: 'test fixture',
    state: 'test_fixture',
    machine_boundary: 'test fixture',
    module_doc_ref: `human_doc:opl_brand_module_${moduleId.replace(/-/g, '_')}`,
    contract_refs: [
      'contracts/opl-framework/brand-module-surfaces.json',
      'contracts/opl-framework/brand-module-registry.json',
    ],
    cli_surfaces: [
      `opl ${moduleId} status --json`,
      `opl ${moduleId} inspect --json`,
      `opl ${moduleId} interfaces --json`,
      `opl ${moduleId} validate --json`,
      `opl ${moduleId} doctor --json`,
      'opl brand-modules list --json',
    ],
    app_surfaces: [
      `app_action:${moduleId.replace(/-/g, '_')}_status`,
      `app_action:${moduleId.replace(/-/g, '_')}_inspect`,
      'opl brand-modules interfaces --json#app',
    ],
    descriptor_surfaces: [
      `opl ${moduleId} interfaces --json`,
      `contracts/opl-framework/brand-module-surfaces.json#modules.${moduleId}`,
      'opl brand-modules interfaces --json#descriptor',
    ],
    validation_surfaces: [
      `opl ${moduleId} validate --json`,
      `opl ${moduleId} doctor --json`,
      'opl brand-modules validate --json',
    ],
    status_doc_refs: ['human_doc:opl_brand_module_maturity_against_workspace'],
    l4_gates: MINIMAL_BRAND_MODULE_GATES,
    maturity_level: 'L4_structural_baseline',
    authority_boundary: {
      can_claim_domain_ready: false,
      can_claim_quality_verdict: false,
      can_claim_artifact_authority: false,
      can_claim_production_ready: false,
      can_write_domain_truth: false,
      can_write_memory_body: false,
      can_mutate_artifact_body: false,
      can_sign_owner_receipt: false,
      can_create_typed_blocker: false,
      can_replace_domain_owner: false,
      can_replace_ai_executor_planning: false,
    },
    forbidden_claims: ['domain_ready'],
  })),
};

export const MINIMAL_SOURCE_MODULE_MAP_CONTRACT: SourceModuleMapContract = {
  version: 'source-module-map.test',
  scope: 'opl_framework_source_module_map',
  owner: 'one-person-lab',
  purpose: 'test fixture',
  state: 'test_fixture',
  machine_boundary: 'test fixture',
  source_root: 'src',
  physical_module_root: 'src/modules',
  alignment_rules: ['test fixture'],
  modules: MINIMAL_BRAND_MODULE_IDS.map((moduleId) => ({
    module_id: moduleId,
    brand_name: `OPL ${moduleId}`,
    physical_root: `src/modules/${moduleId}`,
    public_entrypoint: `src/modules/${moduleId}/index.ts`,
    primary_source_globs: [`src/${moduleId}/**`],
    shared_source_globs: [],
    owner_note: 'test fixture',
  })),
  shared_kernel: [
    {
      path: 'src/types.ts',
      primary_module_id: 'charter',
      consumer_module_ids: [...MINIMAL_BRAND_MODULE_IDS],
      role: 'test fixture',
    },
  ],
};

export const MINIMAL_BRAND_MODULE_SURFACES_CONTRACT: BrandModuleSurfacesContract = {
  version: 'brand-module-surfaces.test',
  scope: 'opl_brand_module_executable_surfaces',
  owner: 'one-person-lab',
  purpose: 'test fixture',
  state: 'test_fixture',
  machine_boundary: 'test fixture',
  baseline_module_id: 'workspace',
  required_native_subcommands: ['status', 'inspect', 'interfaces', 'validate', 'doctor'],
  required_gates: [
    'object_model',
    'native_cli_family',
    'app_read_model',
    'descriptor_surface',
    'validation',
    'doctor',
    'status',
    'authority_boundary',
    'forbidden_claims',
  ],
  modules: MINIMAL_BRAND_MODULE_IDS.map((moduleId) => ({
    module_id: moduleId,
    brand_name: `OPL ${moduleId}`,
    command_prefix: moduleId,
    surface_kind_prefix: `opl_${moduleId.replace(/-/g, '_')}`,
    state: 'L4_module_surface_baseline',
    module_doc_ref: `human_doc:opl_brand_module_${moduleId.replace(/-/g, '_')}`,
    object_model: {
      primary_objects: ['test_object'],
      canonical_contract_refs: ['contracts/opl-framework/brand-module-registry.json'],
      read_model_refs: [`opl ${moduleId} status --json`, `opl ${moduleId} inspect --json`],
    },
    native_cli_family: {
      status: `opl ${moduleId} status --json`,
      inspect: `opl ${moduleId} inspect --json`,
      interfaces: `opl ${moduleId} interfaces --json`,
      validate: `opl ${moduleId} validate --json`,
      doctor: `opl ${moduleId} doctor --json`,
      additional_commands: ['opl brand-modules list --json'],
    },
    app_read_model: {
      descriptors: [
        {
          action_id: `${moduleId.replace(/-/g, '_')}_status`,
          command: `opl ${moduleId} status --json`,
          mutation: false,
          descriptor_only: true,
        },
        {
          action_id: `${moduleId.replace(/-/g, '_')}_inspect`,
          command: `opl ${moduleId} inspect --json`,
          mutation: false,
          descriptor_only: true,
        },
        {
          action_id: `${moduleId.replace(/-/g, '_')}_doctor`,
          command: `opl ${moduleId} doctor --json`,
          mutation: false,
          descriptor_only: true,
        },
      ],
      projection_refs: ['opl brand-modules interfaces --json#app'],
    },
    descriptor_surface: {
      delegate_ids: [`${moduleId.replace(/-/g, '_')}_surface_contract`],
      descriptor_refs: [`opl ${moduleId} interfaces --json`],
    },
    validation: {
      commands: [`opl ${moduleId} validate --json`, `opl ${moduleId} doctor --json`],
      checks: ['module_surface_contract'],
      required_refs: [`contracts/opl-framework/brand-module-surfaces.json#modules.${moduleId}`],
    },
    doctor: {
      checks: ['surface_contract_loaded'],
      fail_closed_on: ['missing_surface_contract'],
    },
    status: {
      completion_level: 'L4_structural_baseline',
      evidence_refs: [`opl ${moduleId} validate --json`],
      not_claims: ['domain_ready'],
    },
    authority_boundary: {
      can_claim_domain_ready: false,
      can_claim_quality_verdict: false,
      can_claim_artifact_authority: false,
      can_claim_production_ready: false,
      can_write_domain_truth: false,
      can_write_memory_body: false,
      can_mutate_artifact_body: false,
      can_sign_owner_receipt: false,
      can_create_typed_blocker: false,
      can_replace_domain_owner: false,
      can_replace_ai_executor_planning: false,
    },
    forbidden_claims: ['domain_ready'],
    notes: 'test fixture',
  })),
};

export const MINIMAL_BRAND_MODULE_L5_OPERATING_EVIDENCE_CONTRACT: BrandModuleL5OperatingEvidenceContract = {
  version: 'brand-module-l5-operating-evidence.test',
  scope: 'opl_brand_module_l5_operating_evidence',
  owner: 'one-person-lab',
  purpose: 'test fixture',
  state: 'test_fixture',
  machine_boundary: 'test fixture',
  baseline_level: 'L4_structural_baseline',
  target_level: 'L5_production_operating_maturity',
  l5_claim_policy: {
    all_required_evidence_must_be_satisfied: true,
    docs_foldback_counts_as_l5: false,
    contract_validation_counts_as_l5: false,
    provider_completion_counts_as_l5: false,
    app_projection_counts_as_l5: false,
    conformance_pass_counts_as_l5: false,
  },
  owner_route_work_order_policy: {
    surface_kind: 'opl_brand_module_l5_owner_route_work_order_policy',
    work_orders_are_refs_only: true,
    work_orders_close_l5: false,
    work_orders_can_create_owner_receipt: false,
    work_orders_can_create_typed_blocker: false,
    work_orders_can_claim_production_ready: false,
    accepted_route_ref_shapes: [
      'owner_acceptance_ref',
      'owner_receipt_ref',
      'typed_blocker_ref',
      'human_gate_ref',
    ],
    non_closing_inputs: [
      'contract_validation',
      'docs_foldback',
      'conformance_pass',
      'provider_completion',
      'app_projection',
      'verified_refs_only_ledger',
    ],
  },
  evidence_ledger_surfaces: {
    record_command: 'opl runtime brand-module-l5-evidence record',
    verify_command: 'opl runtime brand-module-l5-evidence verify',
    list_command: 'opl runtime brand-module-l5-evidence list',
    ledger_file_name: 'brand-module-l5-evidence-ledger.json',
    refs_only: true,
    can_claim_l5_complete: false,
    can_create_owner_receipt: false,
    can_create_typed_blocker: false,
  },
  evidence_classes: MINIMAL_BRAND_MODULE_L5_EVIDENCE_CLASSES.map((classId) => ({
    class_id: classId,
    definition: 'test fixture',
    accepted_ref_shapes: ['typed_blocker_ref'],
  })),
  modules: MINIMAL_BRAND_MODULE_IDS.map((moduleId) => ({
    module_id: moduleId,
    brand_name: `OPL ${moduleId}`,
    current_level: 'L4_structural_baseline',
    l5_completion_status: 'evidence_required',
    l5_can_be_claimed: false,
    immediate_enabling_surfaces: [`${moduleId}_l5_fixture_gate`],
    evidence_requirements: MINIMAL_BRAND_MODULE_L5_EVIDENCE_CLASSES.map((classId) => ({
      class_id: classId,
      owner: 'one-person-lab',
      owner_route_ref: `opl-owner-route:brand-module/${moduleId}/${classId}/test-owner`,
      owner_repo_ref: `/tmp/opl-test#brand-module:${moduleId}`,
      current_state: 'open',
    })),
    not_claims: ['production_ready'],
  })),
};

export const MINIMAL_BRAND_SYSTEM_PROFILE_CONTRACT: BrandSystemProfileContract = {
  version: 'brand-system-profile.test',
  scope: 'opl_brand_system_freeze_profile',
  owner: 'one-person-lab',
  purpose: 'test fixture',
  state: 'test_fixture',
  machine_boundary: 'test fixture',
  source_refs: ['contracts/opl-framework/brand-system-profile.json'],
  product_cognition_layers: [
    {
      layer_id: 'opl_framework',
      product_name: 'OPL Framework',
      user_understanding: 'test fixture',
      maintainer_understanding: 'test fixture',
      owner: 'one-person-lab',
      authority_boundary: ['test fixture'],
    },
    {
      layer_id: 'one_person_lab_app',
      product_name: 'One Person Lab App',
      user_understanding: 'test fixture',
      maintainer_understanding: 'test fixture',
      owner: 'one-person-lab-app',
      authority_boundary: ['test fixture'],
    },
    {
      layer_id: 'foundry_agents',
      product_name: 'Foundry Agents',
      user_understanding: 'test fixture',
      maintainer_understanding: 'test fixture',
      owner: 'domain-agent repositories',
      authority_boundary: ['test fixture'],
    },
  ],
  brand_module_product_grammar: {
    module_ids: [...MINIMAL_BRAND_MODULE_IDS],
    module_role_refs: MINIMAL_BRAND_MODULE_IDS.map((moduleId) => ({
      module_id: moduleId,
      product_grammar_role: 'test fixture',
      registry_ref: `contracts/opl-framework/brand-module-registry.json#modules.${moduleId}`,
      surface_contract_ref: `contracts/opl-framework/brand-module-surfaces.json#modules.${moduleId}`,
    })),
  },
  agent_naming: {
    family_label: 'One Person Lab Foundry Agent',
    public_name_policy: 'test fixture',
    machine_id_policy: 'test fixture',
    required_agent_ids: ['mas', 'mag', 'rca', 'oma'],
    foundry_series_contract_ref: 'contracts/opl-framework/foundry-agent-series-contract.json',
  },
  app_status_language: {
    default_terms: [
      'current owner',
      'next action',
      'artifact',
      'receipt',
      'typed blocker',
      'human gate',
    ],
    diagnostic_only_terms: ['ledger', 'provider'],
    forbidden_default_terms: ['domain ready'],
    default_state_ref: 'contracts/opl-framework/family-product-operator-projection.json',
    full_detail_policy_ref: 'contracts/opl-framework/family-product-operator-projection.json',
  },
  visual_system: {
    pattern_groups: [
      {
        group_id: 'design_tokens',
        purpose: 'test fixture',
        required_patterns: ['semantic_color_tokens'],
      },
      {
        group_id: 'icons',
        purpose: 'test fixture',
        required_patterns: ['module_icon_family'],
      },
      {
        group_id: 'cards',
        purpose: 'test fixture',
        required_patterns: ['agent_card'],
      },
      {
        group_id: 'status_patterns',
        purpose: 'test fixture',
        required_patterns: ['current_owner_status'],
      },
    ],
  },
  ordinary_app_experience: {
    surface_kind: 'opl_brand_ordinary_app_experience_profile',
    default_read_surface_ref: 'app_state.operator.ordinary_cockpit',
    experience_axes: [
      {
        axis_id: 'running_fluency',
        user_visible_goal: 'test fixture',
        app_projection_ref: 'app_state.operator.ordinary_cockpit.display_payload',
        l5_evidence_class_ref: 'contracts/opl-framework/brand-module-l5-operating-evidence.json#evidence_classes.ordinary_app_experience',
        must_not_claim: ['production_ready'],
      },
      {
        axis_id: 'output_quality',
        user_visible_goal: 'test fixture',
        app_projection_ref: 'app_state.operator.brand_experience_profile.display_language_refs',
        l5_evidence_class_ref: 'contracts/opl-framework/brand-module-l5-operating-evidence.json#evidence_classes.ordinary_app_experience',
        must_not_claim: ['quality_verdict'],
      },
      {
        axis_id: 'brand_feel',
        user_visible_goal: 'test fixture',
        app_projection_ref: 'app_state.operator.brand_experience_profile.display_language_refs',
        l5_evidence_class_ref: 'contracts/opl-framework/brand-module-l5-operating-evidence.json#evidence_classes.ordinary_app_experience',
        must_not_claim: ['app_release_ready'],
      },
    ],
    l5_evidence_refs_only: true,
    authority_boundary: {
      can_claim_l5: false,
      can_claim_app_release_ready: false,
      can_authorize_quality_verdict: false,
      can_create_owner_receipt: false,
      can_create_typed_blocker: false,
    },
  },
  receipt_blocker_language: {
    success_shape: 'domain_owner_receipt_ref',
    blocked_shape: 'domain_owned_typed_blocker_ref',
    route_back_shape: 'route_back_or_human_gate_ref',
    owner_answer_schema_ref: 'contracts/opl-framework/owner-answer.schema.json',
    owner_receipt_schema_ref: 'contracts/opl-framework/stage-owner-receipt.schema.json',
    typed_blocker_schema_ref: 'contracts/opl-framework/stage-typed-blocker.schema.json',
    wording_rules: ['test fixture'],
  },
  authority_boundary: {
    can_claim_domain_ready: false,
    can_claim_quality_verdict: false,
    can_claim_artifact_authority: false,
    can_claim_production_ready: false,
    can_write_domain_truth: false,
    can_write_memory_body: false,
    can_mutate_artifact_body: false,
    can_sign_owner_receipt: false,
    can_create_typed_blocker: false,
    can_replace_domain_owner: false,
    can_replace_ai_executor_planning: false,
  },
  forbidden_claims: ['domain_ready'],
};

export const MINIMAL_BRAND_CLI_GOVERNANCE_CONTRACT: BrandCliGovernanceContract = {
  version: 'brand-cli-governance.test',
  scope: 'opl_brand_cli_governance',
  owner: 'one-person-lab',
  purpose: 'test fixture',
  state: 'test_fixture',
  machine_boundary: 'test fixture',
  platform_command_surfaces: MINIMAL_BRAND_MODULE_IDS.map((moduleId) => ({
    module_id: moduleId,
    command: `opl ${moduleId}`,
    operations: moduleId === 'workspace' ? ['status', 'inspect'] : ['status', 'inspect', 'interfaces', 'validate', 'doctor'],
  })),
  agent_internal_modules: {
    canonical_command_surface: 'opl agents modules',
    required_operations: ['list', 'inspect', 'interfaces', 'validate', 'doctor'],
    module_spine: MINIMAL_BRAND_MODULE_IDS.map((moduleId) => ({
      agent_module_id: `agent-${moduleId}`,
      platform_analogue_module_id: moduleId,
      purpose: 'test fixture',
      command_pattern: `opl agents modules inspect --domain <domain_id> --module agent-${moduleId}`,
    })),
    authority_boundary: {
      can_claim_domain_ready: false,
      can_claim_quality_verdict: false,
      can_claim_artifact_authority: false,
      can_claim_production_ready: false,
      can_write_domain_truth: false,
      can_write_memory_body: false,
      can_mutate_artifact_body: false,
      can_sign_owner_receipt: false,
      can_create_typed_blocker: false,
      can_replace_domain_owner: false,
      can_replace_ai_executor_planning: false,
    },
  },
  legacy_command_ownership: [
    {
      command_prefix: 'opl brand-modules',
      primary_module_id: 'charter',
      secondary_module_ids: ['atlas', 'workspace', 'stagecraft', 'runway', 'ledger', 'console', 'foundry-lab', 'connect'],
      status: 'test_fixture',
      migration_target: 'test fixture',
      command_refs: ['opl brand-modules list --json'],
      rationale: 'test fixture',
    },
  ],
  drift_guards: ['test fixture'],
};
