import type { TargetOperatingArchitectureContract } from '../../../../../src/kernel/types.ts';

export const MINIMAL_TARGET_OPERATING_ARCHITECTURE_CONTRACT: TargetOperatingArchitectureContract = {
  contract_kind: 'opl_target_operating_architecture_contract.v1',
  schema_version: 'target-operating-architecture.v1',
  owner: 'one-person-lab',
  purpose: 'test fixture',
  state: 'active_contract',
  machine_boundary: 'test fixture',
  source_refs: ['human_doc:test_fixture'],
  design_principles: [
    'grip_big_release_small',
    'current_owner_delta_first',
    'single_writer_stage_transition_authority',
    'declarative_domain_pack_generated_surfaces_authority_abi',
    'passive_evidence_ledger',
    'one_ordinary_golden_path_per_agent',
    'small_idempotent_reconcilers',
    'app_console_thin_default_surface',
    'agent_lab_refs_only_improvement_control_plane',
    'runway_control_loop_runtime_module',
  ],
  resource_model: {
    resource_shape: {
      required_fields: ['apiVersion', 'kind', 'metadata', 'spec', 'status', 'conditions', 'ownerRefs', 'finalizers'],
      spec_status_split_required: true,
      status_can_define_desired_state: false,
      conditions_are_status_not_truth: true,
    },
    resource_kinds: [
      { kind: 'Agent', owner: 'domain_owner', default_lane: 'ordinary', truth_boundary: 'test fixture' },
      { kind: 'DomainPack', owner: 'domain_owner', default_lane: 'ordinary', truth_boundary: 'test fixture' },
      { kind: 'WorkspaceGroup', owner: 'one-person-lab', default_lane: 'ordinary', truth_boundary: 'test fixture' },
      { kind: 'ProjectUnit', owner: 'domain_owner', default_lane: 'ordinary', truth_boundary: 'test fixture' },
      { kind: 'StageRun', owner: 'one-person-lab', default_lane: 'ordinary', truth_boundary: 'test fixture' },
      { kind: 'StageArtifactUnit', owner: 'domain_owner', default_lane: 'ordinary', truth_boundary: 'test fixture' },
      { kind: 'OwnerAnswer', owner: 'domain_or_human_owner', default_lane: 'ordinary', truth_boundary: 'test fixture' },
      { kind: 'EvidenceRef', owner: 'one-person-lab', default_lane: 'audit', truth_boundary: 'test fixture' },
      { kind: 'ReleaseCohort', owner: 'app_release_owner', default_lane: 'production_evidence', truth_boundary: 'test fixture' },
      { kind: 'ImprovementWorkOrder', owner: 'agent_lab', default_lane: 'advisory', truth_boundary: 'test fixture' },
      { kind: 'RunwayControlLoop', owner: 'one-person-lab', default_lane: 'ordinary', truth_boundary: 'test fixture' },
      { kind: 'ProgressReconciler', owner: 'one-person-lab', default_lane: 'ordinary', truth_boundary: 'test fixture' },
    ],
  },
  stage_transition_authority: {
    authority_owner: 'one-person-lab',
    single_writer: true,
    event_log_policy: 'append_only_authority_event_log',
    derived_state: [
      'stage_current_pointer',
      'stage_run_terminal_state',
      'current_owner_delta',
      'runway_control_loop_status',
      'progress_reconciler_projection',
    ],
    accepted_inputs: [
      'transition_intent',
      'provider_observation',
      'owner_answer',
      'typed_blocker',
      'human_gate_decision',
      'agent_lab_observation',
      'evidence_observation',
      'runtime_intent',
      'progress_reconciler_observation',
      'handoff_gate_decision',
      'recovery_repair_observation',
    ],
    forbidden_direct_writers: [
      'domain_agent',
      'runtime_provider',
      'one_person_lab_app',
      'agent_lab',
      'read_model',
      'evidence_ledger',
      'worklist',
      'runway_control_loop',
      'progress_reconciler',
      'worker_supervisor',
      'temporal_workflow_history',
    ],
  },
  domain_pack_authority_abi: {
    default_agent_shape: 'declarative_domain_pack_plus_opl_generated_hosted_surfaces_plus_standard_authority_functions',
    domain_pack_must_declare: [
      'stage_graph',
      'ordinary_golden_path',
      'prompt_refs',
      'skill_refs',
      'tool_affordance_boundary_refs',
      'knowledge_refs',
      'quality_gate_refs',
      'artifact_policy',
      'memory_policy',
      'owner_answer_schema',
      'authority_functions',
      'fixtures',
      'tests',
    ],
    opl_generated_or_hosted_surfaces: [
      'cli',
      'mcp',
      'skill_plugin',
      'product_entry',
      'openai_tool',
      'ai_sdk',
      'status_read_model',
      'workbench',
      'functional_harness',
      'operator_projection',
    ],
    authority_functions: [
      'quality_or_export_verdict',
      'artifact_authority',
      'memory_accept_reject',
      'owner_receipt_signer',
      'typed_blocker_signer',
      'human_gate_signer',
    ],
    private_platform_residue_default_disposition: 'absorb_to_opl_primitive_or_tombstone_after_owner_decision',
  },
  surface_budget_compiler_policy: {
    ordinary_path_root: 'current_owner_delta',
    ordinary_progress_spine: {
      default_planning_root: 'current_owner_delta',
      default_next_action_derives_from: 'current_owner_delta',
      lightweight_receipt: 'ProgressDeltaReceipt',
      lightweight_receipt_tier: 'T0_progress_delta',
      audit_sidecar_role: 'passive_evidence_ledger_and_drilldown',
    },
    artifact_tiers: ['T0_progress_delta', 'T1_stage_transition', 'T2_delivery_artifact', 'T3_production_evidence'],
    progress_delta_receipt_cannot_authorize: [
      'stage_complete',
      'publication_ready',
      'package_ready',
      'artifact_mutation',
      'memory_accept_reject',
      'production_ready',
    ],
    audit_sidecar_must_not_generate_default_next_action: true,
    surface_plane_binding_required: true,
    default_surface_requires_plane_ref: true,
    ordinary_surface_allowed_planes: [
      'ordinary_progress_plane',
      'durable_runway_plane',
      'authority_decision_plane',
      'reconciler_plane',
      'app_cockpit_plane',
    ],
    non_authority_surface_forbidden_outputs: [
      'domain_owner_answer',
      'domain_typed_blocker',
      'quality_or_export_verdict',
      'artifact_body_mutation',
      'memory_body_mutation',
      'domain_ready_declaration',
      'production_ready_declaration',
    ],
    allowed_lanes: ['ordinary', 'advisory', 'audit', 'diagnostic', 'cleanup', 'production_evidence'],
    small_detail_default_lanes: ['advisory', 'audit', 'diagnostic', 'cleanup', 'production_evidence'],
    hard_blocker_upgrade_conditions: [
      'wrong_launch',
      'authority_violation',
      'not_recoverable',
      'not_auditable',
      'cannot_closeout',
      'invalid_owner_answer_shape',
      'irreversible_mutation',
    ],
    ordinary_path_must_not_be_overridden_by: [
      'raw_worklist',
      'evidence_ledger',
      'provider_trace',
      'route_variant_menu',
      'private_residue_inventory',
      'cleanup_delete_gate',
      'l5_evidence_ledger',
      'release_diagnostics',
    ],
    accepted_owner_answer_shapes: [
      'owner_receipt_ref',
      'domain_owner_receipt_ref',
      'quality_gate_receipt_ref',
      'human_gate_ref',
      'typed_blocker_ref',
      'no_regression_ref',
      'long_soak_ref',
      'route_back_ref',
      'route_back_evidence_ref',
      'physical_delete_authorization_ref',
      'keep_as_authority_adapter_ref',
    ],
  },
  multi_plane_operating_system: {
    plane_model_id: 'opl_family_multi_plane_operating_system.v1',
    default_ordinary_route: 'current_owner_delta',
    planes: [
      {
        plane_id: 'purpose_pack_plane',
        owner_modules: ['charter', 'pack', 'atlas'],
        default_lane: 'ordinary',
        inputs: ['domain_purpose'],
        outputs: ['domain_pack_contract'],
        forbidden_claims: ['domain_ready_declaration', 'quality_or_export_verdict', 'owner_receipt_signature', 'typed_blocker_signature'],
        ordinary_path_eligible: true,
      },
      {
        plane_id: 'ordinary_progress_plane',
        owner_modules: ['console', 'stagecraft', 'runway'],
        default_lane: 'ordinary',
        inputs: ['stage_goal'],
        outputs: ['current_owner_delta'],
        forbidden_claims: ['domain_ready_declaration', 'quality_or_export_verdict', 'owner_receipt_signature', 'typed_blocker_signature'],
        ordinary_path_eligible: true,
      },
      {
        plane_id: 'stage_artifact_plane',
        owner_modules: ['stagecraft', 'ledger', 'workspace'],
        default_lane: 'ordinary',
        inputs: ['physical_output_ref'],
        outputs: ['stage_artifact_unit_projection'],
        forbidden_claims: ['domain_ready_declaration', 'quality_or_export_verdict', 'owner_receipt_signature', 'typed_blocker_signature', 'current_owner_delta_write'],
        ordinary_path_eligible: false,
      },
      {
        plane_id: 'durable_runway_plane',
        owner_modules: ['runway', 'stagecraft', 'ledger'],
        default_lane: 'ordinary',
        inputs: ['runtime_intent'],
        outputs: ['provider_observation'],
        forbidden_claims: ['domain_ready_declaration', 'quality_or_export_verdict', 'owner_receipt_signature', 'typed_blocker_signature', 'provider_completion_is_domain_completion'],
        ordinary_path_eligible: true,
      },
      {
        plane_id: 'authority_decision_plane',
        owner_modules: ['stagecraft', 'console', 'runway'],
        default_lane: 'ordinary',
        inputs: ['owner_answer'],
        outputs: ['accepted_owner_answer_ref'],
        forbidden_claims: ['domain_ready_declaration', 'quality_or_export_verdict', 'owner_receipt_signature', 'typed_blocker_signature'],
        ordinary_path_eligible: true,
      },
      {
        plane_id: 'evidence_telemetry_plane',
        owner_modules: ['ledger', 'atlas', 'runway'],
        default_lane: 'audit',
        inputs: ['evidence_refs'],
        outputs: ['refs_only_evidence_stream'],
        forbidden_claims: ['domain_ready_declaration', 'quality_or_export_verdict', 'owner_receipt_signature', 'typed_blocker_signature'],
        ordinary_path_eligible: false,
      },
      {
        plane_id: 'reconciler_plane',
        owner_modules: ['runway', 'console', 'stagecraft'],
        default_lane: 'ordinary',
        inputs: ['desired_owner_delta'],
        outputs: ['exactly_one_safe_action'],
        forbidden_claims: ['domain_ready_declaration', 'quality_or_export_verdict', 'owner_receipt_signature', 'typed_blocker_signature'],
        ordinary_path_eligible: true,
      },
      {
        plane_id: 'app_cockpit_plane',
        owner_modules: ['console', 'connect', 'runway'],
        default_lane: 'ordinary',
        inputs: ['current_owner_delta'],
        outputs: ['ordinary_cockpit_projection'],
        forbidden_claims: ['domain_ready_declaration', 'quality_or_export_verdict', 'owner_receipt_signature', 'typed_blocker_signature'],
        ordinary_path_eligible: true,
      },
      {
        plane_id: 'improvement_plane',
        owner_modules: ['foundry-lab', 'atlas', 'pack'],
        default_lane: 'advisory',
        inputs: ['eval_ref'],
        outputs: ['work_order_ref'],
        forbidden_claims: ['domain_ready_declaration', 'quality_or_export_verdict', 'owner_receipt_signature', 'typed_blocker_signature'],
        ordinary_path_eligible: false,
      },
    ],
    cross_plane_authority_boundary: {
      plane_projection_can_write_domain_truth: false,
      plane_projection_can_sign_owner_receipt: false,
      plane_projection_can_create_typed_blocker: false,
      plane_projection_can_claim_quality_or_export_verdict: false,
      plane_projection_can_claim_domain_ready: false,
      plane_projection_can_claim_production_ready: false,
    },
  },
  reconciler_model: {
    loop_granularity: 'small_idempotent_reconcilers_with_runway_control_loop_runtime',
    required_loops: [
      'recovery_repair',
      'handoff_gate',
      'progress_reconciliation',
      'runtime_intent_admission',
      'admission',
      'execution_authorization',
      'provider_attempt',
      'closeout_binding',
      'owner_answer_intake',
      'evidence_verify',
      'cleanup_finalizer',
      'release_cohort_verify',
    ],
    loop_authority_boundary: {
      reconciler_can_generate_candidates: false,
      reconciler_can_evaluate_or_rank_candidates: false,
      reconciler_can_complete_stage: false,
      reconciler_can_sign_receipts: false,
      reconciler_can_create_typed_blocker: false,
      reconciler_can_write_domain_truth: false,
    },
    substrate_policy: {
      temporal_role: 'durable_workflow_history_activity_heartbeat_visibility_and_retry_substrate_only',
      worker_supervisor_role: 'process_liveness_restart_and_host_health_only',
      progress_reconciler_role: 'semantic_execution_loop_desired_current_reconciliation_and_next_owner_projection',
      false_authority_boundary: 'no_domain_truth_no_owner_receipt_no_typed_blocker_no_quality_verdict_no_artifact_or_memory_body',
    },
  },
  catalog_and_telemetry: {
    atlas_catalogs: ['agents', 'domain_packs', 'resources', 'surfaces', 'contracts', 'skills', 'mcp_tools', 'app_pages', 'release_channels'],
    ledger_ref_streams: ['evidence_refs', 'receipt_refs', 'typed_blocker_refs', 'trace_refs', 'metric_refs', 'log_refs', 'artifact_lineage_refs'],
    ledger_policy: 'record_everything_plan_from_nothing',
    telemetry_body_policy: 'refs_only_no_artifact_or_memory_body',
  },
  app_console_policy: {
    default_screen_fields: ['task', 'stage', 'current_owner', 'next_action', 'running_or_blocked_status', 'artifact_or_blocker', 'accepted_answer_shape'],
    drilldown_only_fields: ['provider_trace', 'attempt_ledger', 'release_diagnostics', 'cleanup_inventory', 'l5_evidence', 'raw_evidence', 'route_variant_menu'],
    gui_truth_owner: 'one-person-lab-app',
    framework_role: 'state_action_projection_producer_only',
  },
  experience_operating_model: {
    model_id: 'opl_family_ideal_experience_operating_model.v1',
    purpose: 'test fixture',
    default_user_path: {
      planning_root: 'current_owner_delta',
      first_screen_policy: 'owner_delta_action_artifact_or_blocker_first',
      primary_read_surface: 'opl app state --profile fast --json',
      drilldown_policy: 'explicit_full_detail_only',
    },
    target_axes: [
      {
        axis_id: 'running_smoothness',
        owner_modules: ['runway', 'stagecraft', 'console'],
        success_policy: 'test fixture',
        machine_checks: ['exactly_one_default_next_action_or_owner_wait'],
        forbidden_regressions: ['ready_claim_without_owner_evidence', 'diagnostic_tail_becomes_default_route'],
      },
      {
        axis_id: 'output_quality',
        owner_modules: ['pack', 'stagecraft', 'ledger'],
        success_policy: 'test fixture',
        machine_checks: ['owner_answer_or_typed_blocker_required_for_semantic_closeout'],
        forbidden_regressions: ['ready_claim_without_owner_evidence', 'diagnostic_tail_becomes_default_route'],
      },
      {
        axis_id: 'brand_feel',
        owner_modules: ['charter', 'console', 'connect'],
        success_policy: 'test fixture',
        machine_checks: ['brand_module_profile_applies_to_default_surfaces'],
        forbidden_regressions: ['ready_claim_without_owner_evidence', 'diagnostic_tail_becomes_default_route'],
      },
    ],
    flagship_agent_default: {
      agent_id: 'mas',
      expected_path: 'declarative_domain_pack_plus_opl_generated_hosted_surfaces_plus_minimal_domain_authority_kernel',
      domain_pack_role: 'medical_research_stage_semantics_quality_gate_refs_artifact_policy_memory_policy_and_owner_answer_schema',
      opl_role: 'activation_runtime_projection_app_cockpit_pack_generated_surfaces_refs_only_evidence_and_reconciler',
      private_runtime_disposition: 'migration_input_not_target_architecture',
    },
    authority_boundary: {
      can_claim_domain_ready: false,
      can_claim_quality_verdict: false,
      can_claim_artifact_authority: false,
      can_claim_production_ready: false,
      can_claim_app_release_ready: false,
      can_claim_brand_l5_ready: false,
    },
    forbidden_claims: [
      'ideal_experience_contract_is_l5_ready',
      'smooth_runtime_is_domain_ready',
      'quality_axis_is_quality_verdict',
      'brand_profile_is_release_ready',
      'mas_flagship_mapping_is_paper_done',
    ],
  },
  agent_lab_improvement_plane: {
    role: 'refs_only_improvement_control_plane',
    may_produce: ['eval_ref', 'root_cause_ref', 'candidate_fix_ref', 'work_order_ref', 'promotion_proposal_ref', 'rollback_ref', 'reevaluation_ref'],
    must_not_produce: ['domain_quality_verdict', 'artifact_authority', 'memory_body', 'owner_receipt', 'typed_blocker', 'production_acceptance'],
  },
  foundry_agent_os_standard: {
    pattern_id: 'foundry_agent_os_standard.v1',
    source_pattern_ref: 'human_doc:mas_opl_agent_os_target_operating_architecture',
    standard_agent_registry_ref: 'src/modules/charter/standard-agent-registry.ts',
    target_shape: 'OPL Agent OS + Domain Declarative Pack + Domain Minimal Authority Kernel + Domain Capability Registry',
    applies_to_domain_agents: ['mas', 'mag', 'rca', 'oma', 'obf'],
    framework_capability_packages: [
      {
        agent_id: 'mas-scholar-skills',
        package_scope: 'framework_capability_package',
        capability_contract_ref: 'contracts/opl-framework/scholar-skills-capability-modules.json',
        public_projection: 'opl_foundry_agent_series_refs_only_capability_package',
        capability_pack_example: 'Scholar Capability Pack',
        authority_ref_examples: ['candidate scientific capability refs', 'domain owner consumption handoff refs'],
        authority_boundary: {
          can_claim_domain_ready: false,
          can_claim_runtime_ready: false,
          can_claim_quality_verdict: false,
          can_claim_artifact_authority: false,
          can_claim_publication_readiness: false,
          can_write_domain_truth: false,
          can_sign_owner_receipt: false,
          can_create_typed_blocker: false,
          can_schedule_runtime: false,
        },
      },
    ],
    domain_pack_examples: {
      mas: 'Medical Research Pack',
      mag: 'Grant Pack',
      rca: 'Visual Deliverable Pack',
      oma: 'Agent-Building Pack',
      obf: 'Book Manuscript Pack',
    },
    domain_authority_kernel_examples: {
      mas: ['medical research truth', 'owner receipt signer'],
      mag: ['grant truth', 'owner receipt signer'],
      rca: ['visual truth', 'owner receipt signer'],
      oma: ['agent-building semantics', 'target-agent typed blocker signer'],
      obf: ['book manuscript truth', 'owner receipt signer'],
    },
    new_agent_baseline_handoff_policy: {
      surface_kind: 'opl_foundry_new_agent_baseline_handoff_policy',
      policy_id: 'opl.foundry.new_agent_baseline_handoff.v1',
      owner: 'one-person-lab',
      oma_owner: 'opl-meta-agent',
      required_gates: [
        'scaffold_validation',
        'generated_interface_projection',
        'agent_lab_baseline_or_takeover_suite',
        'independent_reviewer_assessment',
        'oma_improvement_or_no_patch_loop',
        'delivery_receipt_or_work_order_or_typed_blocker',
      ],
      scaffold_or_generated_interface_can_claim_complete: false,
      conformance_or_suite_pass_can_claim_complete: false,
      exactly_one_terminal_outcome_required: true,
      accepted_terminal_outcomes: [
        'delivery_receipt',
        'no_patch_coordination_receipt',
        'developer_patch_work_order',
        'typed_blocker',
      ],
      authority_boundary: {
        opl_can_write_target_domain_truth: false,
        opl_can_sign_target_owner_receipt: false,
        opl_can_create_target_typed_blocker: false,
        oma_can_claim_target_domain_ready: false,
        oma_can_promote_default_agent_without_gate: false,
      },
    },
    opl_module_mapping: [
      {
        target_capability: 'pack_compiler_generated_surfaces',
        primary_module: 'pack',
        supporting_modules: ['atlas', 'connect'],
        ordinary_lane: 'ordinary',
        authority_boundary: 'test fixture',
      },
      {
        target_capability: 'domain_capability_registry',
        primary_module: 'atlas',
        supporting_modules: ['pack', 'stagecraft'],
        ordinary_lane: 'advisory',
        authority_boundary: 'test fixture',
      },
      {
        target_capability: 'current_owner_delta_default_read_root',
        primary_module: 'console',
        supporting_modules: ['runway', 'ledger'],
        ordinary_lane: 'ordinary',
        authority_boundary: 'test fixture',
      },
      {
        target_capability: 'stage_run_durable_execution',
        primary_module: 'runway',
        supporting_modules: ['stagecraft', 'ledger'],
        ordinary_lane: 'ordinary',
        authority_boundary: 'test fixture',
      },
      {
        target_capability: 'refs_only_evidence_and_lineage',
        primary_module: 'ledger',
        supporting_modules: ['console', 'runway'],
        ordinary_lane: 'audit',
        authority_boundary: 'test fixture',
      },
    ],
    capability_registry_boundary: {
      owner_modules: ['atlas', 'pack', 'stagecraft'],
      default_behavior: 'current_owner_delta_bound_jit_or_fail_open',
      resolver_abi_ref: 'contracts/opl-framework/capability-registry-resolver.schema.json',
      selector_helper_ref: 'src/capability-registry-resolver.ts',
      fail_open_policy: 'test fixture',
      optional_ref_missing_default: 'advisory_or_audit',
      route_required_ref_missing: 'typed_blocker_candidate_only_from_current_owner_delta_hard_boundary',
      must_not_create: ['domain authority verdict', 'owner receipt', 'typed blocker'],
    },
    cross_agent_conformance_required_claims: [
      'default_read_root_is_current_owner_delta',
      'domain_authority_false_flags_on_opl_modules',
      'generated_surfaces_do_not_write_domain_truth',
      'conformance_pass_does_not_claim_domain_ready',
      'ledger_console_runway_do_not_sign_owner_answer',
      'capability_registry_fails_open_unless_current_delta_requires_ref',
    ],
    os_readback_contract: {
      surface_kind: 'foundry_agent_os_readback_contract',
      completion_audit_contract_ref: 'contracts/opl-framework/opl-flow-completion-audit-contract.json',
      claim_scope: 'thorough_landing',
      requires_lane_to_plan_mapping: true,
      requires_main_session_fresh_verification: true,
      docs_refs_tests_commit_only_can_score_100: false,
      readback_contract_landed_can_claim_complete: false,
      accepted_100_percent_evidence_kinds: [
        'cli_output_ref',
        'runtime_artifact_ref',
        'run_receipt_ref',
        'owner_receipt_ref',
        'typed_blocker_ref',
        'end_to_end_acceptance_ref',
      ],
      insufficient_100_percent_evidence_kinds: [
        'docs_updated',
        'refs_only_surface_landed',
        'contract_landed',
        'tests_passed_only',
        'commit_pushed_only',
        'subagent_reported_complete',
        'worktree_merged_only',
      ],
    },
    implementation_lane_refs: ['human_doc:foundry_agent_os_family_target_implementation_plan'],
    authority_boundary: {
      can_claim_domain_ready: false,
      can_claim_quality_verdict: false,
      can_claim_artifact_authority: false,
      can_claim_production_ready: false,
      can_write_domain_truth: false,
      can_write_memory_body: false,
      can_mutate_artifact_body: false,
      can_sign_owner_receipt: false,
      can_create_typed_blocker: false,
      can_replace_domain_owner: false,
      can_replace_ai_executor_planning: false,
    },
    forbidden_claims: [
      'agent_os_contract_is_domain_ready',
      'capability_registry_owns_domain_authority',
      'pack_compile_is_quality_verdict',
      'generated_surface_writes_domain_truth',
      'current_owner_delta_projection_signs_owner_answer',
      'ledger_ref_is_owner_receipt_authority',
      'runway_provider_completion_is_domain_completion',
      'console_view_is_app_release_ready',
    ],
  },
  flagship_experience_mapping: {
    mapping_id: 'mas_research_foundry_flagship_experience.v1',
    flagship_agent_id: 'mas',
    standard_agent_shape: 'Declarative Domain Pack + OPL generated/hosted surfaces + minimal authority functions',
    journey_artifacts: [
      'Evidence Map',
      'Analysis Pack',
      'Manuscript Draft',
      'Reviewer Letter',
      'Revision Packet',
      'Publication Handoff',
    ],
    private_platform_residue_inputs: [
      'private_scheduler',
      'private_runner',
      'private_workbench',
      'private_status_shell',
    ],
    opl_contract_surfaces: [
      'target_operating_architecture_contract',
      'standard_domain_agent_conformance',
      'foundry_agent_os_conformance',
      'pack_compiler_projection',
    ],
    false_ready_claims: [
      'mas_ready',
      'paper_done',
      'brand_l5_done',
      'production_ready',
    ],
    authority_boundary: {
      can_claim_mas_ready: false,
      can_claim_paper_done: false,
      can_claim_brand_l5_done: false,
      can_claim_production_ready: false,
      can_write_mas_truth: false,
      can_sign_mas_owner_receipt: false,
      can_create_mas_typed_blocker: false,
      can_authorize_publication_readiness: false,
    },
  },
  one_shot_plan_landing_model: {
    model_id: 'opl_family_one_shot_plan_landing.v1',
    purpose: 'test fixture',
    source_plan_ref: 'attachment:test',
    default_completion_semantics: 'test fixture',
    implementation_slices: [
      {
        plan_id: 'P0',
        title: 'freeze_target_contracts',
        status: 'opl_landed',
        opl_landed_surfaces: ['contracts/opl-framework/target-operating-architecture-contract.json'],
        validation_commands: ['rtk npm run test:meta'],
        remaining_owner_gate: 'none',
        false_completion_claims: ['contract_validation_is_domain_ready'],
      },
      {
        plan_id: 'P1',
        title: 'narrow_default_read_surface',
        status: 'opl_landed',
        opl_landed_surfaces: ['opl app state --profile fast --json'],
        validation_commands: ['rtk npm run test:fast'],
        remaining_owner_gate: 'none',
        false_completion_claims: ['raw_worklist_is_default_planning_root'],
      },
      {
        plan_id: 'P2',
        title: 'runway_and_anti_spin',
        status: 'opl_landed_owner_gated',
        opl_landed_surfaces: ['src/family-runtime-progress-first-anti-spin-gate.ts'],
        validation_commands: ['rtk npm run test:fast'],
        remaining_owner_gate: 'runtime_owner_long_soak_ref',
        false_completion_claims: ['provider_completion_is_domain_closeout'],
      },
      {
        plan_id: 'P3',
        title: 'stage_artifact_and_progress_delta_receipt',
        status: 'opl_landed_owner_gated',
        opl_landed_surfaces: ['src/stage-artifact-runtime.ts'],
        validation_commands: ['rtk npm run test:fast'],
        remaining_owner_gate: 'domain_owner_receipt_ref',
        false_completion_claims: ['progress_delta_receipt_is_owner_receipt'],
      },
      {
        plan_id: 'P4',
        title: 'quality_gate_runtime',
        status: 'opl_landed_owner_gated',
        opl_landed_surfaces: ['contracts/opl-framework/family-domain-quality-projection-contract.json'],
        validation_commands: ['rtk npm run test:fast'],
        remaining_owner_gate: 'quality_or_export_verdict_ref',
        false_completion_claims: ['opl_quality_gate_projection_is_quality_verdict'],
      },
      {
        plan_id: 'P5',
        title: 'app_and_brand_experience',
        status: 'opl_landed_owner_gated',
        opl_landed_surfaces: ['app_state.operator.brand_experience_profile'],
        validation_commands: ['rtk npm run test:fast'],
        remaining_owner_gate: 'app_release_owner_verdict_ref',
        false_completion_claims: ['app_projection_is_release_ready'],
      },
      {
        plan_id: 'P6',
        title: 'foundry_agent_pack_and_wrapper_retirement',
        status: 'opl_landed_owner_gated',
        opl_landed_surfaces: ['contracts/opl-framework/wrapper-retirement-gate-policy.json'],
        validation_commands: ['rtk npm run test:fast'],
        remaining_owner_gate: 'physical_delete_authorization_ref',
        false_completion_claims: ['generated_descriptor_ready_is_active_caller_migration_done'],
      },
      {
        plan_id: 'P7',
        title: 'brand_l5_evidence_route',
        status: 'opl_landed_owner_gated',
        opl_landed_surfaces: ['opl brand-modules l5-status --json'],
        validation_commands: ['rtk npm run test:fast'],
        remaining_owner_gate: 'brand_module_owner_acceptance_ref',
        false_completion_claims: ['verified_l5_ledger_is_l5_complete'],
      },
      {
        plan_id: 'P8',
        title: 'final_scaleout_and_release',
        status: 'external_owner_gated',
        opl_landed_surfaces: ['opl framework operating-maturity --family-defaults --json'],
        validation_commands: ['rtk npm run test:fast'],
        remaining_owner_gate: 'owner_chain_release_and_long_soak_refs',
        false_completion_claims: ['zero_worklist_count_is_domain_ready'],
      },
    ],
    summary: {
      total_plan_count: 9,
      opl_landed_count: 2,
      opl_landed_owner_gated_count: 6,
      external_owner_gated_count: 1,
      all_opl_controlled_surfaces_landed: true,
      external_owner_evidence_still_required: true,
      ready_claim_authorized: false,
    },
    authority_boundary: {
      can_claim_domain_ready: false,
      can_claim_quality_verdict: false,
      can_claim_artifact_authority: false,
      can_claim_app_release_ready: false,
      can_claim_brand_l5_ready: false,
      can_claim_production_ready: false,
      can_claim_mas_paper_done: false,
      can_write_domain_truth: false,
      can_sign_owner_receipt: false,
      can_create_typed_blocker: false,
      can_authorize_physical_delete: false,
    },
  },
  authority_boundary: {
    can_claim_domain_ready: false,
    can_claim_quality_verdict: false,
    can_claim_artifact_authority: false,
    can_claim_production_ready: false,
    can_write_domain_truth: false,
    can_write_memory_body: false,
    can_mutate_artifact_body: false,
    can_sign_owner_receipt: false,
    can_create_typed_blocker: false,
    can_replace_domain_owner: false,
    can_replace_ai_executor_planning: false,
    can_replace_app_release_truth: false,
  },
  forbidden_claims: ['contract_validation_is_domain_ready'],
};
