export const DEFAULT_CODEX_STAGE_RUNNER_TIMEOUT_MS = 3_600_000;
export const DEFAULT_CODEX_STAGE_RUNNER_NO_OUTPUT_TIMEOUT_MS = 300_000;
export const DEFAULT_CODEX_STAGE_ACTIVITY_HEARTBEAT_INTERVAL_MS = 30_000;
export const CODEX_STAGE_ACTIVITY_START_TO_CLOSE_TIMEOUT = '65 minutes';
export const CODEX_STAGE_ACTIVITY_HEARTBEAT_TIMEOUT = '5 minutes';
export const SHORT_STAGE_ACTIVITY_START_TO_CLOSE_TIMEOUT = '10 minutes';
export const SHORT_STAGE_ACTIVITY_HEARTBEAT_TIMEOUT = '10 minutes';
